import { createRoute, type OpenAPIHono } from "@hono/zod-openapi";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { apiErrorResponse } from "../../../http/api-error";
import type { AuthenticatedApiEnv } from "../../../http/authenticated-actor";
import type { ResolveSession } from "../../../http/middleware/require-session";
import type { CreateDirectConversationService } from "./create-direct-conversation/create-direct-conversation.service";
import type { ConversationReader } from "./conversation.repository";
import { MessagingError } from "../shared/messaging-error";
import { changesQuerySchema, changesSchema, conversationFolderSchema, conversationListSchema, conversationParamsSchema, conversationSchema, directConversationBodySchema, directConversationResponseSchema, markReadBodySchema, messagingReadErrors, messageListSchema, messagesQuerySchema, readSchema, resolveRequestBodySchema, unreadSchema } from "./conversation.contract";
import { messageParamsSchema, messageSchema } from "../messages/message.contract";
import { scheduleImmediateDispatch, type ImmediateDispatchDependencies } from "../shared/immediate-dispatch";

export interface ConversationRouteDependencies extends ImmediateDispatchDependencies { resolveSession: ResolveSession; direct?: CreateDirectConversationService; reader?: ConversationReader; }
const security: Array<Record<string, string[]>> = [{ BearerAuth: [] }, { cookieAuth: [] }];
const directRoute = createRoute({ method: "post", path: "/api/v1/conversations/direct", tags: ["Messaging"], operationId: "createDirectConversation", security, request: { body: { required: true, content: { "application/json": { schema: directConversationBodySchema } } } }, responses: { 201: { description: "Created direct conversation and initial message.", content: { "application/json": { schema: directConversationResponseSchema } } }, 200: { description: "Identical replay.", content: { "application/json": { schema: directConversationResponseSchema } } }, ...messagingReadErrors } });
const listRoute = createRoute({ method: "get", path: "/api/v1/conversations", tags: ["Messaging"], operationId: "listConversations", security, request: { query: conversationFolderSchema }, responses: { 200: { description: "Authorized inbox page.", content: { "application/json": { schema: conversationListSchema } } }, ...messagingReadErrors } });
const getRoute = createRoute({ method: "get", path: "/api/v1/conversations/{conversationId}", tags: ["Messaging"], operationId: "getConversation", security, request: { params: conversationParamsSchema }, responses: { 200: { description: "Conversation state.", content: { "application/json": { schema: conversationSchema } } }, ...messagingReadErrors } });
const unreadRoute = createRoute({ method: "get", path: "/api/v1/messaging/unread", tags: ["Messaging"], operationId: "getMessagingUnread", security, responses: { 200: { description: "Incoming unread message totals.", content: { "application/json": { schema: unreadSchema } } }, ...messagingReadErrors } });
const historyRoute = createRoute({ method: "get", path: "/api/v1/conversations/{conversationId}/messages", tags: ["Messaging"], operationId: "listMessages", security, request: { params: conversationParamsSchema, query: messagesQuerySchema }, responses: { 200: { description: "Authorized history page.", content: { "application/json": { schema: messageListSchema } } }, ...messagingReadErrors } });
const messageRoute = createRoute({ method: "get", path: "/api/v1/conversations/{conversationId}/messages/{messageId}", tags: ["Messaging"], operationId: "getMessage", security, request: { params: messageParamsSchema }, responses: { 200: { description: "Canonical message.", content: { "application/json": { schema: messageSchema } } }, ...messagingReadErrors } });
const resolveRoute = createRoute({ method: "put", path: "/api/v1/conversations/{conversationId}/request", tags: ["Messaging"], operationId: "resolveMessageRequest", security, request: { params: conversationParamsSchema, body: { required: true, content: { "application/json": { schema: resolveRequestBodySchema } } } }, responses: { 200: { description: "Resolved conversation.", content: { "application/json": { schema: conversationSchema } } }, ...messagingReadErrors } });
const readRoute = createRoute({ method: "put", path: "/api/v1/conversations/{conversationId}/read", tags: ["Messaging"], operationId: "markConversationRead", security, request: { params: conversationParamsSchema, body: { required: true, content: { "application/json": { schema: markReadBodySchema } } } }, responses: { 200: { description: "Current read positions.", content: { "application/json": { schema: readSchema } } }, ...messagingReadErrors } });
const changesRoute = createRoute({ method: "get", path: "/api/v1/conversations/{conversationId}/changes", tags: ["Messaging"], operationId: "listConversationChanges", security, request: { params: conversationParamsSchema, query: changesQuerySchema }, responses: { 200: { description: "Durable changes.", content: { "application/json": { schema: changesSchema } } }, ...messagingReadErrors } });
function unavailable(context: any) { return apiErrorResponse(context, 503, "SERVICE_UNAVAILABLE", "Messaging is temporarily unavailable.") as never; }
function fail(context: any, error: MessagingError) { const status = error.code === "NOT_FOUND" ? 404 : error.code === "VALIDATION_FAILED" ? 422 : error.code === "BLOCKED" || error.code === "FORBIDDEN" ? 403 : 409; return apiErrorResponse(context, status, status === 404 ? "NOT_FOUND" : status === 422 ? "VALIDATION_FAILED" : status === 403 ? "FORBIDDEN" : "CONFLICT", error.message, { reason: error.code }) as never; }
export function registerConversationRoutes(app: OpenAPIHono<AuthenticatedApiEnv>, dependencies: ConversationRouteDependencies) {
  const action = (callback: (actorId: string, context: any) => Promise<unknown>, dispatch = false) => async (context: any) => { context.header("Cache-Control", "no-store"); if (!dependencies.reader) return unavailable(context); try { const result = await callback(context.get("actor").userId, context); if (dispatch) scheduleImmediateDispatch(context, dependencies); return context.json(result, 200); } catch (error) { if (error instanceof MessagingError) return fail(context, error); throw error; } };
  app.openapi(directRoute, async (context) => { context.header("Cache-Control", "no-store"); if (!dependencies.direct) return unavailable(context); try { const result = await dependencies.direct.create(context.get("actor").userId, context.req.valid("json")); scheduleImmediateDispatch(context, dependencies); return context.json({ conversation: { id: result.conversation.id, peer: { id: result.conversation.peerId, name: null }, requestState: result.conversation.requestState }, message: result.message }, result.replayed ? 200 : 201); } catch (error) { if (error instanceof MessagingError) return fail(context, error); throw error; } });
  app.openapi(listRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); const query = context.req.valid("query"); return dependencies.reader.list(actor, query.folder, query.cursor, query.limit); }));
  app.openapi(getRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); return dependencies.reader.get(actor, context.req.valid("param").conversationId); }));
  app.openapi(unreadRoute, action(async (actor) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); return dependencies.reader.unread(actor); }));
  app.openapi(historyRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); const query = context.req.valid("query"); return dependencies.reader.messages(actor, context.req.valid("param").conversationId, query.beforeSequence, query.afterSequence, query.limit); }));
  app.openapi(messageRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); const p = context.req.valid("param"); return dependencies.reader.message(actor, p.conversationId, p.messageId); }));
  app.openapi(resolveRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); return dependencies.reader.resolve(actor, context.req.valid("param").conversationId, context.req.valid("json").decision); }, true));
  app.openapi(readRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); return dependencies.reader.markRead(actor, context.req.valid("param").conversationId, context.req.valid("json").throughSequence); }, true));
  app.openapi(changesRoute, action(async (actor, context) => { if (!dependencies.reader) throw new MessagingError("CONFLICT"); const query = context.req.valid("query"); return dependencies.reader.changes(actor, context.req.valid("param").conversationId, query.afterChangeSequence, query.limit); }));
}
