/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountGoogleProofBeginRequest
 */
export interface AccountGoogleProofBeginRequest {
    /**
     *
     */
    action: AccountGoogleProofBeginRequestActionEnum;
}


/**
 * @export
 */
export const AccountGoogleProofBeginRequestActionEnum = {
    RequestDeletion: 'request_deletion',
    CancelDeletion: 'cancel_deletion',
} as const;
export type AccountGoogleProofBeginRequestActionEnum = typeof AccountGoogleProofBeginRequestActionEnum[keyof typeof AccountGoogleProofBeginRequestActionEnum];


/**
 * Check if a given object implements the AccountGoogleProofBeginRequest interface.
 */
export function instanceOfAccountGoogleProofBeginRequest(value: object): value is AccountGoogleProofBeginRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function AccountGoogleProofBeginRequestFromJSON(json: any): AccountGoogleProofBeginRequest {
    return AccountGoogleProofBeginRequestFromJSONTyped(json, false);
}

export function AccountGoogleProofBeginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountGoogleProofBeginRequest {
    if (json == null) {
        return json;
    }
    return {

        'action': json['action'],
    };
}

export function AccountGoogleProofBeginRequestToJSON(json: any): AccountGoogleProofBeginRequest {
    return AccountGoogleProofBeginRequestToJSONTyped(json, false);
}

export function AccountGoogleProofBeginRequestToJSONTyped(value?: AccountGoogleProofBeginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'action': value['action'],
    };
}
