/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface AccountRequestDataExport202Response
 */
export interface AccountRequestDataExport202Response {
    /**
     *
     */
    id: string;
    /**
     *
     */
    status: AccountRequestDataExport202ResponseStatusEnum;
    /**
     *
     */
    requestedAt: Date;
    /**
     *
     */
    readyAt: Date;
    /**
     *
     */
    expiresAt: Date;
    /**
     *
     */
    downloadable: boolean;
}


/**
 * @export
 */
export const AccountRequestDataExport202ResponseStatusEnum = {
    Requested: 'requested',
    Building: 'building',
    Ready: 'ready',
    Failed: 'failed',
    Cancelled: 'cancelled',
    Expired: 'expired',
} as const;
export type AccountRequestDataExport202ResponseStatusEnum = typeof AccountRequestDataExport202ResponseStatusEnum[keyof typeof AccountRequestDataExport202ResponseStatusEnum];


/**
 * Check if a given object implements the AccountRequestDataExport202Response interface.
 */
export function instanceOfAccountRequestDataExport202Response(value: object): value is AccountRequestDataExport202Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('requestedAt' in value) || value['requestedAt'] === undefined) return false;
    if (!('readyAt' in value) || value['readyAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('downloadable' in value) || value['downloadable'] === undefined) return false;
    return true;
}

export function AccountRequestDataExport202ResponseFromJSON(json: any): AccountRequestDataExport202Response {
    return AccountRequestDataExport202ResponseFromJSONTyped(json, false);
}

export function AccountRequestDataExport202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRequestDataExport202Response {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'status': json['status'],
        'requestedAt': (json['requestedAt'] == null ? json['requestedAt'] : parseDateTime(json['requestedAt'])),
        'readyAt': (json['readyAt'] == null ? json['readyAt'] : parseDateTime(json['readyAt'])),
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
        'downloadable': json['downloadable'],
    };
}

export function AccountRequestDataExport202ResponseToJSON(json: any): AccountRequestDataExport202Response {
    return AccountRequestDataExport202ResponseToJSONTyped(json, false);
}

export function AccountRequestDataExport202ResponseToJSONTyped(value?: AccountRequestDataExport202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'status': value['status'],
        'requestedAt': value['requestedAt'] == null ? value['requestedAt'] : serializeDateTime(value['requestedAt']),
        'readyAt': value['readyAt'] == null ? value['readyAt'] : serializeDateTime(value['readyAt']),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'downloadable': value['downloadable'],
    };
}
