/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface AccountExportRequestResult
 */
export interface AccountExportRequestResult {
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    status: AccountExportRequestResultStatusEnum;
    /**
     *
     */
    requestedAt: Date;
}


/**
 * @export
 */
export const AccountExportRequestResultStatusEnum = {
    Requested: 'requested',
    Building: 'building',
    Ready: 'ready',
    Expired: 'expired',
} as const;
export type AccountExportRequestResultStatusEnum = typeof AccountExportRequestResultStatusEnum[keyof typeof AccountExportRequestResultStatusEnum];


/**
 * Check if a given object implements the AccountExportRequestResult interface.
 */
export function instanceOfAccountExportRequestResult(value: object): value is AccountExportRequestResult {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('requestedAt' in value) || value['requestedAt'] === undefined) return false;
    return true;
}

export function AccountExportRequestResultFromJSON(json: any): AccountExportRequestResult {
    return AccountExportRequestResultFromJSONTyped(json, false);
}

export function AccountExportRequestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountExportRequestResult {
    if (json == null) {
        return json;
    }
    return {

        'requestId': json['requestId'],
        'status': json['status'],
        'requestedAt': (json['requestedAt'] == null ? json['requestedAt'] : parseDateTime(json['requestedAt'])),
    };
}

export function AccountExportRequestResultToJSON(json: any): AccountExportRequestResult {
    return AccountExportRequestResultToJSONTyped(json, false);
}

export function AccountExportRequestResultToJSONTyped(value?: AccountExportRequestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'requestId': value['requestId'],
        'status': value['status'],
        'requestedAt': value['requestedAt'] == null ? value['requestedAt'] : serializeDateTime(value['requestedAt']),
    };
}
