/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountDeletionCancellationResult
 */
export interface AccountDeletionCancellationResult {
    /**
     *
     */
    status: AccountDeletionCancellationResultStatusEnum;
    /**
     *
     */
    generation: number;
}


/**
 * @export
 */
export const AccountDeletionCancellationResultStatusEnum = {
    Cancelled: 'cancelled',
} as const;
export type AccountDeletionCancellationResultStatusEnum = typeof AccountDeletionCancellationResultStatusEnum[keyof typeof AccountDeletionCancellationResultStatusEnum];


/**
 * Check if a given object implements the AccountDeletionCancellationResult interface.
 */
export function instanceOfAccountDeletionCancellationResult(value: object): value is AccountDeletionCancellationResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'cancelled') return false;

    if (!('generation' in value) || value['generation'] === undefined) return false;
    return true;
}

export function AccountDeletionCancellationResultFromJSON(json: any): AccountDeletionCancellationResult {
    return AccountDeletionCancellationResultFromJSONTyped(json, false);
}

export function AccountDeletionCancellationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDeletionCancellationResult {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'],
        'generation': json['generation'],
    };
}

export function AccountDeletionCancellationResultToJSON(json: any): AccountDeletionCancellationResult {
    return AccountDeletionCancellationResultToJSONTyped(json, false);
}

export function AccountDeletionCancellationResultToJSONTyped(value?: AccountDeletionCancellationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status': value['status'],
        'generation': value['generation'],
    };
}
