/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface AccountDeletionStatus
 */
export interface AccountDeletionStatus {
    /**
     *
     */
    state: AccountDeletionStatusStateEnum;
    /**
     *
     */
    generation: number;
    /**
     *
     */
    requestId: string | null;
    /**
     *
     */
    requestedAt: Date | null;
    /**
     *
     */
    cancelUntil: Date | null;
    /**
     *
     */
    purgeDueAt: Date | null;
}


/**
 * @export
 */
export const AccountDeletionStatusStateEnum = {
    Active: 'active',
    PendingDeletion: 'pending_deletion',
    Purging: 'purging',
    PurgeFailed: 'purge_failed',
} as const;
export type AccountDeletionStatusStateEnum = typeof AccountDeletionStatusStateEnum[keyof typeof AccountDeletionStatusStateEnum];


/**
 * Check if a given object implements the AccountDeletionStatus interface.
 */
export function instanceOfAccountDeletionStatus(value: object): value is AccountDeletionStatus {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('generation' in value) || value['generation'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('requestedAt' in value) || value['requestedAt'] === undefined) return false;
    if (!('cancelUntil' in value) || value['cancelUntil'] === undefined) return false;
    if (!('purgeDueAt' in value) || value['purgeDueAt'] === undefined) return false;
    return true;
}

export function AccountDeletionStatusFromJSON(json: any): AccountDeletionStatus {
    return AccountDeletionStatusFromJSONTyped(json, false);
}

export function AccountDeletionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDeletionStatus {
    if (json == null) {
        return json;
    }
    return {

        'state': json['state'],
        'generation': json['generation'],
        'requestId': json['requestId'],
        'requestedAt': (json['requestedAt'] == null ? null : parseDateTime(json['requestedAt'])),
        'cancelUntil': (json['cancelUntil'] == null ? null : parseDateTime(json['cancelUntil'])),
        'purgeDueAt': (json['purgeDueAt'] == null ? null : parseDateTime(json['purgeDueAt'])),
    };
}

export function AccountDeletionStatusToJSON(json: any): AccountDeletionStatus {
    return AccountDeletionStatusToJSONTyped(json, false);
}

export function AccountDeletionStatusToJSONTyped(value?: AccountDeletionStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'state': value['state'],
        'generation': value['generation'],
        'requestId': value['requestId'],
        'requestedAt': value['requestedAt'] == null ? value['requestedAt'] : serializeDateTime(value['requestedAt']),
        'cancelUntil': value['cancelUntil'] == null ? value['cancelUntil'] : serializeDateTime(value['cancelUntil']),
        'purgeDueAt': value['purgeDueAt'] == null ? value['purgeDueAt'] : serializeDateTime(value['purgeDueAt']),
    };
}
