/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface AccountExportStatus
 */
export interface AccountExportStatus {
    /**
     *
     */
    requestId: string | null;
    /**
     *
     */
    status: AccountExportStatusStatusEnum;
    /**
     *
     */
    requestedAt: Date | null;
    /**
     *
     */
    readyAt: Date | null;
    /**
     *
     */
    expiresAt: Date | null;
}


/**
 * @export
 */
export const AccountExportStatusStatusEnum = {
    None: 'none',
    Requested: 'requested',
    Building: 'building',
    Ready: 'ready',
    Failed: 'failed',
    Cancelled: 'cancelled',
    Expired: 'expired',
} as const;
export type AccountExportStatusStatusEnum = typeof AccountExportStatusStatusEnum[keyof typeof AccountExportStatusStatusEnum];


/**
 * Check if a given object implements the AccountExportStatus interface.
 */
export function instanceOfAccountExportStatus(value: object): value is AccountExportStatus {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('requestedAt' in value) || value['requestedAt'] === undefined) return false;
    if (!('readyAt' in value) || value['readyAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function AccountExportStatusFromJSON(json: any): AccountExportStatus {
    return AccountExportStatusFromJSONTyped(json, false);
}

export function AccountExportStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountExportStatus {
    if (json == null) {
        return json;
    }
    return {

        'requestId': json['requestId'],
        'status': json['status'],
        'requestedAt': (json['requestedAt'] == null ? null : parseDateTime(json['requestedAt'])),
        'readyAt': (json['readyAt'] == null ? null : parseDateTime(json['readyAt'])),
        'expiresAt': (json['expiresAt'] == null ? null : parseDateTime(json['expiresAt'])),
    };
}

export function AccountExportStatusToJSON(json: any): AccountExportStatus {
    return AccountExportStatusToJSONTyped(json, false);
}

export function AccountExportStatusToJSONTyped(value?: AccountExportStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'requestId': value['requestId'],
        'status': value['status'],
        'requestedAt': value['requestedAt'] == null ? value['requestedAt'] : serializeDateTime(value['requestedAt']),
        'readyAt': value['readyAt'] == null ? value['readyAt'] : serializeDateTime(value['readyAt']),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}
