/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface AccountGoogleProofComplete200Response
 */
export interface AccountGoogleProofComplete200Response {
    /**
     *
     */
    grant: string;
    /**
     *
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the AccountGoogleProofComplete200Response interface.
 */
export function instanceOfAccountGoogleProofComplete200Response(value: object): value is AccountGoogleProofComplete200Response {
    if (!('grant' in value) || value['grant'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function AccountGoogleProofComplete200ResponseFromJSON(json: any): AccountGoogleProofComplete200Response {
    return AccountGoogleProofComplete200ResponseFromJSONTyped(json, false);
}

export function AccountGoogleProofComplete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountGoogleProofComplete200Response {
    if (json == null) {
        return json;
    }
    return {

        'grant': json['grant'],
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
    };
}

export function AccountGoogleProofComplete200ResponseToJSON(json: any): AccountGoogleProofComplete200Response {
    return AccountGoogleProofComplete200ResponseToJSONTyped(json, false);
}

export function AccountGoogleProofComplete200ResponseToJSONTyped(value?: AccountGoogleProofComplete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'grant': value['grant'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}
