/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountGetDataExport200ResponseExport } from './AccountGetDataExport200ResponseExport';
import {
    AccountGetDataExport200ResponseExportFromJSON,
    AccountGetDataExport200ResponseExportFromJSONTyped,
    AccountGetDataExport200ResponseExportToJSON,
    AccountGetDataExport200ResponseExportToJSONTyped,
} from './AccountGetDataExport200ResponseExport';

/**
 *
 * @export
 * @interface AccountGetDataExport200Response
 */
export interface AccountGetDataExport200Response {
    /**
     *
     */
    _export: AccountGetDataExport200ResponseExport;
}

/**
 * Check if a given object implements the AccountGetDataExport200Response interface.
 */
export function instanceOfAccountGetDataExport200Response(value: object): value is AccountGetDataExport200Response {
    if ((!('_export' in (value as Record<string, any>)) && !('export' in (value as Record<string, any>))) || ((value as Record<string, any>)['_export'] === undefined && (value as Record<string, any>)['export'] === undefined)) return false;
    return true;
}

export function AccountGetDataExport200ResponseFromJSON(json: any): AccountGetDataExport200Response {
    return AccountGetDataExport200ResponseFromJSONTyped(json, false);
}

export function AccountGetDataExport200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountGetDataExport200Response {
    if (json == null) {
        return json;
    }
    return {

        '_export': AccountGetDataExport200ResponseExportFromJSON(json['export']),
    };
}

export function AccountGetDataExport200ResponseToJSON(json: any): AccountGetDataExport200Response {
    return AccountGetDataExport200ResponseToJSONTyped(json, false);
}

export function AccountGetDataExport200ResponseToJSONTyped(value?: AccountGetDataExport200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'export': AccountGetDataExport200ResponseExportToJSON(value['_export']),
    };
}
