/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface AccountRequestDeletion200Response
 */
export interface AccountRequestDeletion200Response {
    /**
     *
     */
    state: AccountRequestDeletion200ResponseStateEnum;
    /**
     *
     */
    generation: number;
    /**
     *
     */
    requestId?: string;
    /**
     *
     */
    requestedAt?: Date;
    /**
     *
     */
    cancelUntil?: Date;
    /**
     *
     */
    purgeDueAt?: Date;
    /**
     *
     */
    restrictedSession: AccountRequestDeletion200ResponseRestrictedSessionEnum;
}


/**
 * @export
 */
export const AccountRequestDeletion200ResponseStateEnum = {
    Active: 'active',
    PendingDeletion: 'pending_deletion',
    Purging: 'purging',
    PurgeFailed: 'purge_failed',
} as const;
export type AccountRequestDeletion200ResponseStateEnum = typeof AccountRequestDeletion200ResponseStateEnum[keyof typeof AccountRequestDeletion200ResponseStateEnum];

/**
 * @export
 */
export const AccountRequestDeletion200ResponseRestrictedSessionEnum = {
    True: true,
} as const;
export type AccountRequestDeletion200ResponseRestrictedSessionEnum = typeof AccountRequestDeletion200ResponseRestrictedSessionEnum[keyof typeof AccountRequestDeletion200ResponseRestrictedSessionEnum];


/**
 * Check if a given object implements the AccountRequestDeletion200Response interface.
 */
export function instanceOfAccountRequestDeletion200Response(value: object): value is AccountRequestDeletion200Response {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('generation' in value) || value['generation'] === undefined) return false;
    if (!('restrictedSession' in value) || value['restrictedSession'] === undefined) return false;

    if (value['restrictedSession'] !== true) return false;
    return true;
}

export function AccountRequestDeletion200ResponseFromJSON(json: any): AccountRequestDeletion200Response {
    return AccountRequestDeletion200ResponseFromJSONTyped(json, false);
}

export function AccountRequestDeletion200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRequestDeletion200Response {
    if (json == null) {
        return json;
    }
    return {

        'state': json['state'],
        'generation': json['generation'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'requestedAt': json['requestedAt'] == null ? undefined : (parseDateTime(json['requestedAt'])),
        'cancelUntil': json['cancelUntil'] == null ? undefined : (parseDateTime(json['cancelUntil'])),
        'purgeDueAt': json['purgeDueAt'] == null ? undefined : (parseDateTime(json['purgeDueAt'])),
        'restrictedSession': json['restrictedSession'],
    };
}

export function AccountRequestDeletion200ResponseToJSON(json: any): AccountRequestDeletion200Response {
    return AccountRequestDeletion200ResponseToJSONTyped(json, false);
}

export function AccountRequestDeletion200ResponseToJSONTyped(value?: AccountRequestDeletion200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'state': value['state'],
        'generation': value['generation'],
        'requestId': value['requestId'],
        'requestedAt': value['requestedAt'] == null ? value['requestedAt'] : serializeDateTime(value['requestedAt']),
        'cancelUntil': value['cancelUntil'] == null ? value['cancelUntil'] : serializeDateTime(value['cancelUntil']),
        'purgeDueAt': value['purgeDueAt'] == null ? value['purgeDueAt'] : serializeDateTime(value['purgeDueAt']),
        'restrictedSession': value['restrictedSession'],
    };
}
