/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface ChangeUsernameResponse
 */
export interface ChangeUsernameResponse {
    /**
     *
     */
    username: string;
    /**
     * When the username can next change, or null when it can change now.
     */
    usernameChangeAvailableAt: Date | null;
}

/**
 * Check if a given object implements the ChangeUsernameResponse interface.
 */
export function instanceOfChangeUsernameResponse(value: object): value is ChangeUsernameResponse {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('usernameChangeAvailableAt' in value) || value['usernameChangeAvailableAt'] === undefined) return false;
    return true;
}

export function ChangeUsernameResponseFromJSON(json: any): ChangeUsernameResponse {
    return ChangeUsernameResponseFromJSONTyped(json, false);
}

export function ChangeUsernameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUsernameResponse {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'],
        'usernameChangeAvailableAt': (json['usernameChangeAvailableAt'] == null ? null : parseDateTime(json['usernameChangeAvailableAt'])),
    };
}

export function ChangeUsernameResponseToJSON(json: any): ChangeUsernameResponse {
    return ChangeUsernameResponseToJSONTyped(json, false);
}

export function ChangeUsernameResponseToJSONTyped(value?: ChangeUsernameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'username': value['username'],
        'usernameChangeAvailableAt': value['usernameChangeAvailableAt'] == null ? value['usernameChangeAvailableAt'] : serializeDateTime(value['usernameChangeAvailableAt']),
    };
}
