/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChangeUsernameRequest
 */
export interface ChangeUsernameRequest {
    /**
     *
     */
    username: string;
}

/**
 * Check if a given object implements the ChangeUsernameRequest interface.
 */
export function instanceOfChangeUsernameRequest(value: object): value is ChangeUsernameRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ChangeUsernameRequestFromJSON(json: any): ChangeUsernameRequest {
    return ChangeUsernameRequestFromJSONTyped(json, false);
}

export function ChangeUsernameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUsernameRequest {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'],
    };
}

export function ChangeUsernameRequestToJSON(json: any): ChangeUsernameRequest {
    return ChangeUsernameRequestToJSONTyped(json, false);
}

export function ChangeUsernameRequestToJSONTyped(value?: ChangeUsernameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'username': value['username'],
    };
}
