/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';
import type { ConversationCapabilities } from './ConversationCapabilities';
import {
    ConversationCapabilitiesFromJSON,
    ConversationCapabilitiesFromJSONTyped,
    ConversationCapabilitiesToJSON,
    ConversationCapabilitiesToJSONTyped,
} from './ConversationCapabilities';
import type { CreateDirectConversation200ResponseConversationPeer } from './CreateDirectConversation200ResponseConversationPeer';
import {
    CreateDirectConversation200ResponseConversationPeerFromJSON,
    CreateDirectConversation200ResponseConversationPeerFromJSONTyped,
    CreateDirectConversation200ResponseConversationPeerToJSON,
    CreateDirectConversation200ResponseConversationPeerToJSONTyped,
} from './CreateDirectConversation200ResponseConversationPeer';

/**
 *
 * @export
 * @interface Conversation
 */
export interface Conversation {
    /**
     *
     */
    id: string;
    /**
     *
     */
    peer: CreateDirectConversation200ResponseConversationPeer;
    /**
     *
     */
    requestState: ConversationRequestStateEnum;
    /**
     *
     */
    latestMessage: Message | null;
    /**
     *
     */
    unreadCount: number;
    /**
     *
     */
    lastMessageSequence: string;
    /**
     *
     */
    lastChangeSequence: string;
    /**
     *
     */
    lastReadSequence: string;
    /**
     *
     */
    receiptSequence: string;
    /**
     *
     */
    capabilities: ConversationCapabilities;
    /**
     *
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const ConversationRequestStateEnum = {
    Pending: 'pending',
    Active: 'active',
    Declined: 'declined',
} as const;
export type ConversationRequestStateEnum = typeof ConversationRequestStateEnum[keyof typeof ConversationRequestStateEnum];


/**
 * Check if a given object implements the Conversation interface.
 */
export function instanceOfConversation(value: object): value is Conversation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('peer' in value) || value['peer'] === undefined) return false;
    if (!('requestState' in value) || value['requestState'] === undefined) return false;
    if (!('latestMessage' in value) || value['latestMessage'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    if (!('lastMessageSequence' in value) || value['lastMessageSequence'] === undefined) return false;
    if (!('lastChangeSequence' in value) || value['lastChangeSequence'] === undefined) return false;
    if (!('lastReadSequence' in value) || value['lastReadSequence'] === undefined) return false;
    if (!('receiptSequence' in value) || value['receiptSequence'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ConversationFromJSON(json: any): Conversation {
    return ConversationFromJSONTyped(json, false);
}

export function ConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conversation {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'peer': CreateDirectConversation200ResponseConversationPeerFromJSON(json['peer']),
        'requestState': json['requestState'],
        'latestMessage': MessageFromJSON(json['latestMessage']),
        'unreadCount': json['unreadCount'],
        'lastMessageSequence': json['lastMessageSequence'],
        'lastChangeSequence': json['lastChangeSequence'],
        'lastReadSequence': json['lastReadSequence'],
        'receiptSequence': json['receiptSequence'],
        'capabilities': ConversationCapabilitiesFromJSON(json['capabilities']),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function ConversationToJSON(json: any): Conversation {
    return ConversationToJSONTyped(json, false);
}

export function ConversationToJSONTyped(value?: Conversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'peer': CreateDirectConversation200ResponseConversationPeerToJSON(value['peer']),
        'requestState': value['requestState'],
        'latestMessage': MessageToJSON(value['latestMessage']),
        'unreadCount': value['unreadCount'],
        'lastMessageSequence': value['lastMessageSequence'],
        'lastChangeSequence': value['lastChangeSequence'],
        'lastReadSequence': value['lastReadSequence'],
        'receiptSequence': value['receiptSequence'],
        'capabilities': ConversationCapabilitiesToJSON(value['capabilities']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}
