/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConversationCapabilities
 */
export interface ConversationCapabilities {
    /**
     *
     */
    canSend: boolean;
    /**
     *
     */
    canResolveRequest: boolean;
}

/**
 * Check if a given object implements the ConversationCapabilities interface.
 */
export function instanceOfConversationCapabilities(value: object): value is ConversationCapabilities {
    if (!('canSend' in value) || value['canSend'] === undefined) return false;
    if (!('canResolveRequest' in value) || value['canResolveRequest'] === undefined) return false;
    return true;
}

export function ConversationCapabilitiesFromJSON(json: any): ConversationCapabilities {
    return ConversationCapabilitiesFromJSONTyped(json, false);
}

export function ConversationCapabilitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationCapabilities {
    if (json == null) {
        return json;
    }
    return {

        'canSend': json['canSend'],
        'canResolveRequest': json['canResolveRequest'],
    };
}

export function ConversationCapabilitiesToJSON(json: any): ConversationCapabilities {
    return ConversationCapabilitiesToJSONTyped(json, false);
}

export function ConversationCapabilitiesToJSONTyped(value?: ConversationCapabilities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'canSend': value['canSend'],
        'canResolveRequest': value['canResolveRequest'],
    };
}
