/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateDirectConversation200ResponseConversationPeer
 */
export interface CreateDirectConversation200ResponseConversationPeer {
    /**
     *
     */
    id: string;
    /**
     *
     */
    name: string | null;
}

/**
 * Check if a given object implements the CreateDirectConversation200ResponseConversationPeer interface.
 */
export function instanceOfCreateDirectConversation200ResponseConversationPeer(value: object): value is CreateDirectConversation200ResponseConversationPeer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateDirectConversation200ResponseConversationPeerFromJSON(json: any): CreateDirectConversation200ResponseConversationPeer {
    return CreateDirectConversation200ResponseConversationPeerFromJSONTyped(json, false);
}

export function CreateDirectConversation200ResponseConversationPeerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDirectConversation200ResponseConversationPeer {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
    };
}

export function CreateDirectConversation200ResponseConversationPeerToJSON(json: any): CreateDirectConversation200ResponseConversationPeer {
    return CreateDirectConversation200ResponseConversationPeerToJSONTyped(json, false);
}

export function CreateDirectConversation200ResponseConversationPeerToJSONTyped(value?: CreateDirectConversation200ResponseConversationPeer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
    };
}
