/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateDirectConversationRequest
 */
export interface CreateDirectConversationRequest {
    /**
     *
     */
    recipientId: string;
    /**
     *
     */
    clientMessageId: string;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the CreateDirectConversationRequest interface.
 */
export function instanceOfCreateDirectConversationRequest(value: object): value is CreateDirectConversationRequest {
    if (!('recipientId' in value) || value['recipientId'] === undefined) return false;
    if (!('clientMessageId' in value) || value['clientMessageId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreateDirectConversationRequestFromJSON(json: any): CreateDirectConversationRequest {
    return CreateDirectConversationRequestFromJSONTyped(json, false);
}

export function CreateDirectConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDirectConversationRequest {
    if (json == null) {
        return json;
    }
    return {

        'recipientId': json['recipientId'],
        'clientMessageId': json['clientMessageId'],
        'text': json['text'],
    };
}

export function CreateDirectConversationRequestToJSON(json: any): CreateDirectConversationRequest {
    return CreateDirectConversationRequestToJSONTyped(json, false);
}

export function CreateDirectConversationRequestToJSONTyped(value?: CreateDirectConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'recipientId': value['recipientId'],
        'clientMessageId': value['clientMessageId'],
        'text': value['text'],
    };
}
