/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAudience } from './PostAudience';
import {
    PostAudienceFromJSON,
    PostAudienceFromJSONTyped,
    PostAudienceToJSON,
    PostAudienceToJSONTyped,
} from './PostAudience';

/**
 *
 * @export
 * @interface CreateDailyPostRequest
 */
export interface CreateDailyPostRequest {
    /**
     * The Auckland day the draft was written for. It must still be the server's current day when the post is accepted.
     */
    localDate: string;
    /**
     * The prompt ID returned by GET /api/v1/posting-days/current for localDate.
     */
    promptId: string;
    /**
     *
     */
    reflectiveAnswer: string;
    /**
     *
     */
    caption?: string;
    /**
     *
     */
    rating: number;
    /**
     *
     */
    audience: PostAudience;
    /**
     * An author-only note that becomes readable on the following Auckland day. It is never echoed back.
     */
    tomorrowNote?: string;
    /**
     * Validated media reservation IDs from POST /api/v1/media-reservations, in display order. Up to 3 photos or 1 video, never both, up to 25 MB in total. Omit it or send an empty list for a text-only post.
     */
    attachments?: Array<string>;
}



/**
 * Check if a given object implements the CreateDailyPostRequest interface.
 */
export function instanceOfCreateDailyPostRequest(value: object): value is CreateDailyPostRequest {
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('reflectiveAnswer' in value) || value['reflectiveAnswer'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('audience' in value) || value['audience'] === undefined) return false;
    return true;
}

export function CreateDailyPostRequestFromJSON(json: any): CreateDailyPostRequest {
    return CreateDailyPostRequestFromJSONTyped(json, false);
}

export function CreateDailyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDailyPostRequest {
    if (json == null) {
        return json;
    }
    return {

        'localDate': json['localDate'],
        'promptId': json['promptId'],
        'reflectiveAnswer': json['reflectiveAnswer'],
        'caption': json['caption'] == null ? undefined : json['caption'],
        'rating': json['rating'],
        'audience': PostAudienceFromJSON(json['audience']),
        'tomorrowNote': json['tomorrowNote'] == null ? undefined : json['tomorrowNote'],
        'attachments': json['attachments'] == null ? undefined : json['attachments'],
    };
}

export function CreateDailyPostRequestToJSON(json: any): CreateDailyPostRequest {
    return CreateDailyPostRequestToJSONTyped(json, false);
}

export function CreateDailyPostRequestToJSONTyped(value?: CreateDailyPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'localDate': value['localDate'],
        'promptId': value['promptId'],
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'rating': value['rating'],
        'audience': PostAudienceToJSON(value['audience']),
        'tomorrowNote': value['tomorrowNote'],
        'attachments': value['attachments'],
    };
}
