/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreatePostCommentRequest
 */
export interface CreatePostCommentRequest {
    /**
     * A client-generated ID, such as a UUID, reused for every retry of this comment. A retry returns the comment already made.
     */
    clientCommentId: string;
    /**
     *
     */
    text: string;
    /**
     * Replies to this top-level comment on the same post. Replies to replies are not allowed.
     */
    parentCommentId?: string;
}

/**
 * Check if a given object implements the CreatePostCommentRequest interface.
 */
export function instanceOfCreatePostCommentRequest(value: object): value is CreatePostCommentRequest {
    if (!('clientCommentId' in value) || value['clientCommentId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreatePostCommentRequestFromJSON(json: any): CreatePostCommentRequest {
    return CreatePostCommentRequestFromJSONTyped(json, false);
}

export function CreatePostCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostCommentRequest {
    if (json == null) {
        return json;
    }
    return {

        'clientCommentId': json['clientCommentId'],
        'text': json['text'],
        'parentCommentId': json['parentCommentId'] == null ? undefined : json['parentCommentId'],
    };
}

export function CreatePostCommentRequestToJSON(json: any): CreatePostCommentRequest {
    return CreatePostCommentRequestToJSONTyped(json, false);
}

export function CreatePostCommentRequestToJSONTyped(value?: CreatePostCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'clientCommentId': value['clientCommentId'],
        'text': value['text'],
        'parentCommentId': value['parentCommentId'],
    };
}
