/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface CreateRealtimeTicket201Response
 */
export interface CreateRealtimeTicket201Response {
    /**
     *
     */
    ticket: string;
    /**
     *
     */
    expiresAt: Date;
    /**
     *
     */
    webSocketUrl: string;
}

/**
 * Check if a given object implements the CreateRealtimeTicket201Response interface.
 */
export function instanceOfCreateRealtimeTicket201Response(value: object): value is CreateRealtimeTicket201Response {
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('webSocketUrl' in value) || value['webSocketUrl'] === undefined) return false;
    return true;
}

export function CreateRealtimeTicket201ResponseFromJSON(json: any): CreateRealtimeTicket201Response {
    return CreateRealtimeTicket201ResponseFromJSONTyped(json, false);
}

export function CreateRealtimeTicket201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRealtimeTicket201Response {
    if (json == null) {
        return json;
    }
    return {

        'ticket': json['ticket'],
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
        'webSocketUrl': json['webSocketUrl'],
    };
}

export function CreateRealtimeTicket201ResponseToJSON(json: any): CreateRealtimeTicket201Response {
    return CreateRealtimeTicket201ResponseToJSONTyped(json, false);
}

export function CreateRealtimeTicket201ResponseToJSONTyped(value?: CreateRealtimeTicket201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'ticket': value['ticket'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'webSocketUrl': value['webSocketUrl'],
    };
}
