/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';
import type { CreateDirectConversation200ResponseConversation } from './CreateDirectConversation200ResponseConversation';
import {
    CreateDirectConversation200ResponseConversationFromJSON,
    CreateDirectConversation200ResponseConversationFromJSONTyped,
    CreateDirectConversation200ResponseConversationToJSON,
    CreateDirectConversation200ResponseConversationToJSONTyped,
} from './CreateDirectConversation200ResponseConversation';

/**
 *
 * @export
 * @interface CreateDirectConversation200Response
 */
export interface CreateDirectConversation200Response {
    /**
     *
     */
    conversation: CreateDirectConversation200ResponseConversation;
    /**
     *
     */
    message: Message;
}

/**
 * Check if a given object implements the CreateDirectConversation200Response interface.
 */
export function instanceOfCreateDirectConversation200Response(value: object): value is CreateDirectConversation200Response {
    if (!('conversation' in value) || value['conversation'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateDirectConversation200ResponseFromJSON(json: any): CreateDirectConversation200Response {
    return CreateDirectConversation200ResponseFromJSONTyped(json, false);
}

export function CreateDirectConversation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDirectConversation200Response {
    if (json == null) {
        return json;
    }
    return {

        'conversation': CreateDirectConversation200ResponseConversationFromJSON(json['conversation']),
        'message': MessageFromJSON(json['message']),
    };
}

export function CreateDirectConversation200ResponseToJSON(json: any): CreateDirectConversation200Response {
    return CreateDirectConversation200ResponseToJSONTyped(json, false);
}

export function CreateDirectConversation200ResponseToJSONTyped(value?: CreateDirectConversation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'conversation': CreateDirectConversation200ResponseConversationToJSON(value['conversation']),
        'message': MessageToJSON(value['message']),
    };
}
