/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { DailyPromptResponse } from './DailyPromptResponse';
import {
    DailyPromptResponseFromJSON,
    DailyPromptResponseFromJSONTyped,
    DailyPromptResponseToJSON,
    DailyPromptResponseToJSONTyped,
} from './DailyPromptResponse';

/**
 *
 * @export
 * @interface CurrentPostingDayResponse
 */
export interface CurrentPostingDayResponse {
    /**
     *
     */
    serverNow: Date;
    /**
     *
     */
    localDate: string;
    /**
     *
     */
    deadlineAt: Date;
    /**
     *
     */
    releaseAt: Date;
    /**
     *
     */
    prompt: DailyPromptResponse;
    /**
     *
     */
    hasPosted: boolean;
}

/**
 * Check if a given object implements the CurrentPostingDayResponse interface.
 */
export function instanceOfCurrentPostingDayResponse(value: object): value is CurrentPostingDayResponse {
    if (!('serverNow' in value) || value['serverNow'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('deadlineAt' in value) || value['deadlineAt'] === undefined) return false;
    if (!('releaseAt' in value) || value['releaseAt'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('hasPosted' in value) || value['hasPosted'] === undefined) return false;
    return true;
}

export function CurrentPostingDayResponseFromJSON(json: any): CurrentPostingDayResponse {
    return CurrentPostingDayResponseFromJSONTyped(json, false);
}

export function CurrentPostingDayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentPostingDayResponse {
    if (json == null) {
        return json;
    }
    return {

        'serverNow': (json['serverNow'] == null ? json['serverNow'] : parseDateTime(json['serverNow'])),
        'localDate': json['localDate'],
        'deadlineAt': (json['deadlineAt'] == null ? json['deadlineAt'] : parseDateTime(json['deadlineAt'])),
        'releaseAt': (json['releaseAt'] == null ? json['releaseAt'] : parseDateTime(json['releaseAt'])),
        'prompt': DailyPromptResponseFromJSON(json['prompt']),
        'hasPosted': json['hasPosted'],
    };
}

export function CurrentPostingDayResponseToJSON(json: any): CurrentPostingDayResponse {
    return CurrentPostingDayResponseToJSONTyped(json, false);
}

export function CurrentPostingDayResponseToJSONTyped(value?: CurrentPostingDayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'serverNow': value['serverNow'] == null ? value['serverNow'] : serializeDateTime(value['serverNow']),
        'localDate': value['localDate'],
        'deadlineAt': value['deadlineAt'] == null ? value['deadlineAt'] : serializeDateTime(value['deadlineAt']),
        'releaseAt': value['releaseAt'] == null ? value['releaseAt'] : serializeDateTime(value['releaseAt']),
        'prompt': DailyPromptResponseToJSON(value['prompt']),
        'hasPosted': value['hasPosted'],
    };
}
