/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DailyPostPrompt
 */
export interface DailyPostPrompt {
    /**
     *
     */
    id: string;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the DailyPostPrompt interface.
 */
export function instanceOfDailyPostPrompt(value: object): value is DailyPostPrompt {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function DailyPostPromptFromJSON(json: any): DailyPostPrompt {
    return DailyPostPromptFromJSONTyped(json, false);
}

export function DailyPostPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyPostPrompt {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'text': json['text'],
    };
}

export function DailyPostPromptToJSON(json: any): DailyPostPrompt {
    return DailyPostPromptToJSONTyped(json, false);
}

export function DailyPostPromptToJSONTyped(value?: DailyPostPrompt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'text': value['text'],
    };
}
