/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeletionGrantRequest
 */
export interface DeletionGrantRequest {
    /**
     *
     */
    grantToken: string;
}

/**
 * Check if a given object implements the DeletionGrantRequest interface.
 */
export function instanceOfDeletionGrantRequest(value: object): value is DeletionGrantRequest {
    if (!('grantToken' in value) || value['grantToken'] === undefined) return false;
    return true;
}

export function DeletionGrantRequestFromJSON(json: any): DeletionGrantRequest {
    return DeletionGrantRequestFromJSONTyped(json, false);
}

export function DeletionGrantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletionGrantRequest {
    if (json == null) {
        return json;
    }
    return {

        'grantToken': json['grantToken'],
    };
}

export function DeletionGrantRequestToJSON(json: any): DeletionGrantRequest {
    return DeletionGrantRequestToJSONTyped(json, false);
}

export function DeletionGrantRequestToJSONTyped(value?: DeletionGrantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'grantToken': value['grantToken'],
    };
}
