/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DirectMessageSendQuotaErrorErrorDetails } from './DirectMessageSendQuotaErrorErrorDetails';
import {
    DirectMessageSendQuotaErrorErrorDetailsFromJSON,
    DirectMessageSendQuotaErrorErrorDetailsFromJSONTyped,
    DirectMessageSendQuotaErrorErrorDetailsToJSON,
    DirectMessageSendQuotaErrorErrorDetailsToJSONTyped,
} from './DirectMessageSendQuotaErrorErrorDetails';

/**
 *
 * @export
 * @interface DirectMessageSendQuotaErrorError
 */
export interface DirectMessageSendQuotaErrorError {
    /**
     *
     */
    code: DirectMessageSendQuotaErrorErrorCodeEnum;
    /**
     *
     */
    message: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    details: DirectMessageSendQuotaErrorErrorDetails;
}


/**
 * @export
 */
export const DirectMessageSendQuotaErrorErrorCodeEnum = {
    RateLimited: 'RATE_LIMITED',
} as const;
export type DirectMessageSendQuotaErrorErrorCodeEnum = typeof DirectMessageSendQuotaErrorErrorCodeEnum[keyof typeof DirectMessageSendQuotaErrorErrorCodeEnum];


/**
 * Check if a given object implements the DirectMessageSendQuotaErrorError interface.
 */
export function instanceOfDirectMessageSendQuotaErrorError(value: object): value is DirectMessageSendQuotaErrorError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (value['code'] !== 'RATE_LIMITED') return false;

    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function DirectMessageSendQuotaErrorErrorFromJSON(json: any): DirectMessageSendQuotaErrorError {
    return DirectMessageSendQuotaErrorErrorFromJSONTyped(json, false);
}

export function DirectMessageSendQuotaErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectMessageSendQuotaErrorError {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'requestId': json['requestId'],
        'details': DirectMessageSendQuotaErrorErrorDetailsFromJSON(json['details']),
    };
}

export function DirectMessageSendQuotaErrorErrorToJSON(json: any): DirectMessageSendQuotaErrorError {
    return DirectMessageSendQuotaErrorErrorToJSONTyped(json, false);
}

export function DirectMessageSendQuotaErrorErrorToJSONTyped(value?: DirectMessageSendQuotaErrorError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'requestId': value['requestId'],
        'details': DirectMessageSendQuotaErrorErrorDetailsToJSON(value['details']),
    };
}
