/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DirectMessageSendQuotaErrorErrorDetails
 */
export interface DirectMessageSendQuotaErrorErrorDetails {
    /**
     *
     */
    retryAfterSeconds: number;
}

/**
 * Check if a given object implements the DirectMessageSendQuotaErrorErrorDetails interface.
 */
export function instanceOfDirectMessageSendQuotaErrorErrorDetails(value: object): value is DirectMessageSendQuotaErrorErrorDetails {
    if (!('retryAfterSeconds' in value) || value['retryAfterSeconds'] === undefined) return false;
    return true;
}

export function DirectMessageSendQuotaErrorErrorDetailsFromJSON(json: any): DirectMessageSendQuotaErrorErrorDetails {
    return DirectMessageSendQuotaErrorErrorDetailsFromJSONTyped(json, false);
}

export function DirectMessageSendQuotaErrorErrorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectMessageSendQuotaErrorErrorDetails {
    if (json == null) {
        return json;
    }
    return {

        'retryAfterSeconds': json['retryAfterSeconds'],
    };
}

export function DirectMessageSendQuotaErrorErrorDetailsToJSON(json: any): DirectMessageSendQuotaErrorErrorDetails {
    return DirectMessageSendQuotaErrorErrorDetailsToJSONTyped(json, false);
}

export function DirectMessageSendQuotaErrorErrorDetailsToJSONTyped(value?: DirectMessageSendQuotaErrorErrorDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'retryAfterSeconds': value['retryAfterSeconds'],
    };
}
