/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DirectPairLookup
 */
export interface DirectPairLookup {
    /**
     *
     */
    conversationId: string;
}

/**
 * Check if a given object implements the DirectPairLookup interface.
 */
export function instanceOfDirectPairLookup(value: object): value is DirectPairLookup {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    return true;
}

export function DirectPairLookupFromJSON(json: any): DirectPairLookup {
    return DirectPairLookupFromJSONTyped(json, false);
}

export function DirectPairLookupFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectPairLookup {
    if (json == null) {
        return json;
    }
    return {

        'conversationId': json['conversationId'],
    };
}

export function DirectPairLookupToJSON(json: any): DirectPairLookup {
    return DirectPairLookupToJSONTyped(json, false);
}

export function DirectPairLookupToJSONTyped(value?: DirectPairLookup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'conversationId': value['conversationId'],
    };
}
