/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DirectMessageSendQuotaErrorError } from './DirectMessageSendQuotaErrorError';
import {
    DirectMessageSendQuotaErrorErrorFromJSON,
    DirectMessageSendQuotaErrorErrorFromJSONTyped,
    DirectMessageSendQuotaErrorErrorToJSON,
    DirectMessageSendQuotaErrorErrorToJSONTyped,
} from './DirectMessageSendQuotaErrorError';

/**
 *
 * @export
 * @interface DirectMessageSendQuotaError
 */
export interface DirectMessageSendQuotaError {
    /**
     *
     */
    error: DirectMessageSendQuotaErrorError;
}

/**
 * Check if a given object implements the DirectMessageSendQuotaError interface.
 */
export function instanceOfDirectMessageSendQuotaError(value: object): value is DirectMessageSendQuotaError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function DirectMessageSendQuotaErrorFromJSON(json: any): DirectMessageSendQuotaError {
    return DirectMessageSendQuotaErrorFromJSONTyped(json, false);
}

export function DirectMessageSendQuotaErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectMessageSendQuotaError {
    if (json == null) {
        return json;
    }
    return {

        'error': DirectMessageSendQuotaErrorErrorFromJSON(json['error']),
    };
}

export function DirectMessageSendQuotaErrorToJSON(json: any): DirectMessageSendQuotaError {
    return DirectMessageSendQuotaErrorToJSONTyped(json, false);
}

export function DirectMessageSendQuotaErrorToJSONTyped(value?: DirectMessageSendQuotaError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': DirectMessageSendQuotaErrorErrorToJSON(value['error']),
    };
}
