/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { PostMedia } from './PostMedia';
import {
    PostMediaFromJSON,
    PostMediaFromJSONTyped,
    PostMediaToJSON,
    PostMediaToJSONTyped,
} from './PostMedia';
import type { FeedPostAuthor } from './FeedPostAuthor';
import {
    FeedPostAuthorFromJSON,
    FeedPostAuthorFromJSONTyped,
    FeedPostAuthorToJSON,
    FeedPostAuthorToJSONTyped,
} from './FeedPostAuthor';
import type { FeedPostPrompt } from './FeedPostPrompt';
import {
    FeedPostPromptFromJSON,
    FeedPostPromptFromJSONTyped,
    FeedPostPromptToJSON,
    FeedPostPromptToJSONTyped,
} from './FeedPostPrompt';

/**
 * A released post from an active friend. Tomorrow notes are not part of the feed projection.
 * @export
 * @interface FeedPost
 */
export interface FeedPost {
    /**
     *
     */
    id: string;
    /**
     *
     */
    author: FeedPostAuthor;
    /**
     *
     */
    localDate: string;
    /**
     *
     */
    prompt: FeedPostPrompt;
    /**
     *
     */
    reflectiveAnswer: string;
    /**
     *
     */
    caption: string;
    /**
     *
     */
    rating: number;
    /**
     * Always `friends`: solo posts never appear in another user's feed.
     */
    audience: FeedPostAudienceEnum;
    /**
     *
     */
    acceptedAt: Date;
    /**
     *
     */
    releasedAt: Date;
    /**
     * True when the author has edited the post since it was accepted.
     */
    edited: boolean;
    /**
     * Attached photos or video in display order, each with a private download URL that expires after 5 minutes.
     */
    media: Array<PostMedia>;
}


/**
 * @export
 */
export const FeedPostAudienceEnum = {
    Friends: 'friends',
} as const;
export type FeedPostAudienceEnum = typeof FeedPostAudienceEnum[keyof typeof FeedPostAudienceEnum];


/**
 * Check if a given object implements the FeedPost interface.
 */
export function instanceOfFeedPost(value: object): value is FeedPost {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('reflectiveAnswer' in value) || value['reflectiveAnswer'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if (value['audience'] !== 'friends') return false;

    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    if (!('releasedAt' in value) || value['releasedAt'] === undefined) return false;
    if (!('edited' in value) || value['edited'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function FeedPostFromJSON(json: any): FeedPost {
    return FeedPostFromJSONTyped(json, false);
}

export function FeedPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedPost {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'author': FeedPostAuthorFromJSON(json['author']),
        'localDate': json['localDate'],
        'prompt': FeedPostPromptFromJSON(json['prompt']),
        'reflectiveAnswer': json['reflectiveAnswer'],
        'caption': json['caption'],
        'rating': json['rating'],
        'audience': json['audience'],
        'acceptedAt': (json['acceptedAt'] == null ? json['acceptedAt'] : parseDateTime(json['acceptedAt'])),
        'releasedAt': (json['releasedAt'] == null ? json['releasedAt'] : parseDateTime(json['releasedAt'])),
        'edited': json['edited'],
        'media': ((json['media'] as Array<any>).map(PostMediaFromJSON)),
    };
}

export function FeedPostToJSON(json: any): FeedPost {
    return FeedPostToJSONTyped(json, false);
}

export function FeedPostToJSONTyped(value?: FeedPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'author': FeedPostAuthorToJSON(value['author']),
        'localDate': value['localDate'],
        'prompt': FeedPostPromptToJSON(value['prompt']),
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'rating': value['rating'],
        'audience': value['audience'],
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : serializeDateTime(value['acceptedAt']),
        'releasedAt': value['releasedAt'] == null ? value['releasedAt'] : serializeDateTime(value['releasedAt']),
        'edited': value['edited'],
        'media': ((value['media'] as Array<any>).map(PostMediaToJSON)),
    };
}
