/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedPost } from './FeedPost';
import {
    FeedPostFromJSON,
    FeedPostFromJSONTyped,
    FeedPostToJSON,
    FeedPostToJSONTyped,
} from './FeedPost';

/**
 *
 * @export
 * @interface FeedPage
 */
export interface FeedPage {
    /**
     *
     */
    items: Array<FeedPost>;
    /**
     *
     */
    nextCursor: string | null;
    /**
     *
     */
    hasMore: boolean;
    /**
     * The Auckland day the page shows: yesterday, released at the most recent midnight.
     */
    feedDate: string;
}

/**
 * Check if a given object implements the FeedPage interface.
 */
export function instanceOfFeedPage(value: object): value is FeedPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('feedDate' in value) || value['feedDate'] === undefined) return false;
    return true;
}

export function FeedPageFromJSON(json: any): FeedPage {
    return FeedPageFromJSONTyped(json, false);
}

export function FeedPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(FeedPostFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
        'feedDate': json['feedDate'],
    };
}

export function FeedPageToJSON(json: any): FeedPage {
    return FeedPageToJSONTyped(json, false);
}

export function FeedPageToJSONTyped(value?: FeedPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(FeedPostToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
        'feedDate': value['feedDate'],
    };
}
