/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FeedPostPrompt
 */
export interface FeedPostPrompt {
    /**
     *
     */
    id: string;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the FeedPostPrompt interface.
 */
export function instanceOfFeedPostPrompt(value: object): value is FeedPostPrompt {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function FeedPostPromptFromJSON(json: any): FeedPostPrompt {
    return FeedPostPromptFromJSONTyped(json, false);
}

export function FeedPostPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedPostPrompt {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'text': json['text'],
    };
}

export function FeedPostPromptToJSON(json: any): FeedPostPrompt {
    return FeedPostPromptToJSONTyped(json, false);
}

export function FeedPostPromptToJSONTyped(value?: FeedPostPrompt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'text': value['text'],
    };
}
