/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FutureSelfNote } from './FutureSelfNote';
import {
    FutureSelfNoteFromJSON,
    FutureSelfNoteFromJSONTyped,
    FutureSelfNoteToJSON,
    FutureSelfNoteToJSONTyped,
} from './FutureSelfNote';

/**
 *
 * @export
 * @interface FutureSelfNotePage
 */
export interface FutureSelfNotePage {
    /**
     *
     */
    items: Array<FutureSelfNote>;
    /**
     *
     */
    nextCursor: string;
    /**
     *
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the FutureSelfNotePage interface.
 */
export function instanceOfFutureSelfNotePage(value: object): value is FutureSelfNotePage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function FutureSelfNotePageFromJSON(json: any): FutureSelfNotePage {
    return FutureSelfNotePageFromJSONTyped(json, false);
}

export function FutureSelfNotePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): FutureSelfNotePage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(FutureSelfNoteFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function FutureSelfNotePageToJSON(json: any): FutureSelfNotePage {
    return FutureSelfNotePageToJSONTyped(json, false);
}

export function FutureSelfNotePageToJSONTyped(value?: FutureSelfNotePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(FutureSelfNoteToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
