/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetMessagingUnread200Response
 */
export interface GetMessagingUnread200Response {
    /**
     *
     */
    inboxCount: number;
    /**
     *
     */
    requestCount: number;
}

/**
 * Check if a given object implements the GetMessagingUnread200Response interface.
 */
export function instanceOfGetMessagingUnread200Response(value: object): value is GetMessagingUnread200Response {
    if (!('inboxCount' in value) || value['inboxCount'] === undefined) return false;
    if (!('requestCount' in value) || value['requestCount'] === undefined) return false;
    return true;
}

export function GetMessagingUnread200ResponseFromJSON(json: any): GetMessagingUnread200Response {
    return GetMessagingUnread200ResponseFromJSONTyped(json, false);
}

export function GetMessagingUnread200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMessagingUnread200Response {
    if (json == null) {
        return json;
    }
    return {

        'inboxCount': json['inboxCount'],
        'requestCount': json['requestCount'],
    };
}

export function GetMessagingUnread200ResponseToJSON(json: any): GetMessagingUnread200Response {
    return GetMessagingUnread200ResponseToJSONTyped(json, false);
}

export function GetMessagingUnread200ResponseToJSONTyped(value?: GetMessagingUnread200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'inboxCount': value['inboxCount'],
        'requestCount': value['requestCount'],
    };
}
