/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GoogleReauthenticationRequest
 */
export interface GoogleReauthenticationRequest {
    /**
     *
     */
    action: GoogleReauthenticationRequestActionEnum;
}


/**
 * @export
 */
export const GoogleReauthenticationRequestActionEnum = {
    RequestDeletion: 'request_deletion',
    CancelDeletion: 'cancel_deletion',
} as const;
export type GoogleReauthenticationRequestActionEnum = typeof GoogleReauthenticationRequestActionEnum[keyof typeof GoogleReauthenticationRequestActionEnum];


/**
 * Check if a given object implements the GoogleReauthenticationRequest interface.
 */
export function instanceOfGoogleReauthenticationRequest(value: object): value is GoogleReauthenticationRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function GoogleReauthenticationRequestFromJSON(json: any): GoogleReauthenticationRequest {
    return GoogleReauthenticationRequestFromJSONTyped(json, false);
}

export function GoogleReauthenticationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleReauthenticationRequest {
    if (json == null) {
        return json;
    }
    return {

        'action': json['action'],
    };
}

export function GoogleReauthenticationRequestToJSON(json: any): GoogleReauthenticationRequest {
    return GoogleReauthenticationRequestToJSONTyped(json, false);
}

export function GoogleReauthenticationRequestToJSONTyped(value?: GoogleReauthenticationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'action': value['action'],
    };
}
