/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LegalIssueRegistrationIntent201ResponseTerms } from './LegalIssueRegistrationIntent201ResponseTerms';
import {
    LegalIssueRegistrationIntent201ResponseTermsFromJSON,
    LegalIssueRegistrationIntent201ResponseTermsFromJSONTyped,
    LegalIssueRegistrationIntent201ResponseTermsToJSON,
    LegalIssueRegistrationIntent201ResponseTermsToJSONTyped,
} from './LegalIssueRegistrationIntent201ResponseTerms';

/**
 *
 * @export
 * @interface LegalAcceptCurrentTerms200Response
 */
export interface LegalAcceptCurrentTerms200Response {
    /**
     *
     */
    terms: LegalIssueRegistrationIntent201ResponseTerms;
    /**
     *
     */
    ageDeclarationVersion: LegalAcceptCurrentTerms200ResponseAgeDeclarationVersionEnum;
}


/**
 * @export
 */
export const LegalAcceptCurrentTerms200ResponseAgeDeclarationVersionEnum = {
    Age16V1: 'age-16-v1',
} as const;
export type LegalAcceptCurrentTerms200ResponseAgeDeclarationVersionEnum = typeof LegalAcceptCurrentTerms200ResponseAgeDeclarationVersionEnum[keyof typeof LegalAcceptCurrentTerms200ResponseAgeDeclarationVersionEnum];


/**
 * Check if a given object implements the LegalAcceptCurrentTerms200Response interface.
 */
export function instanceOfLegalAcceptCurrentTerms200Response(value: object): value is LegalAcceptCurrentTerms200Response {
    if (!('terms' in value) || value['terms'] === undefined) return false;
    if (!('ageDeclarationVersion' in value) || value['ageDeclarationVersion'] === undefined) return false;
    if (value['ageDeclarationVersion'] !== 'age-16-v1') return false;

    return true;
}

export function LegalAcceptCurrentTerms200ResponseFromJSON(json: any): LegalAcceptCurrentTerms200Response {
    return LegalAcceptCurrentTerms200ResponseFromJSONTyped(json, false);
}

export function LegalAcceptCurrentTerms200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalAcceptCurrentTerms200Response {
    if (json == null) {
        return json;
    }
    return {

        'terms': LegalIssueRegistrationIntent201ResponseTermsFromJSON(json['terms']),
        'ageDeclarationVersion': json['ageDeclarationVersion'],
    };
}

export function LegalAcceptCurrentTerms200ResponseToJSON(json: any): LegalAcceptCurrentTerms200Response {
    return LegalAcceptCurrentTerms200ResponseToJSONTyped(json, false);
}

export function LegalAcceptCurrentTerms200ResponseToJSONTyped(value?: LegalAcceptCurrentTerms200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'terms': LegalIssueRegistrationIntent201ResponseTermsToJSON(value['terms']),
        'ageDeclarationVersion': value['ageDeclarationVersion'],
    };
}
