/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LegalAcceptanceRequest
 */
export interface LegalAcceptanceRequest {
    /**
     *
     */
    termsVersionId: string;
    /**
     *
     */
    termsContentDigest: string;
    /**
     *
     */
    acceptedTermsAndDeclaredAge16: boolean;
}

/**
 * Check if a given object implements the LegalAcceptanceRequest interface.
 */
export function instanceOfLegalAcceptanceRequest(value: object): value is LegalAcceptanceRequest {
    if (!('termsVersionId' in value) || value['termsVersionId'] === undefined) return false;
    if (!('termsContentDigest' in value) || value['termsContentDigest'] === undefined) return false;
    if (!('acceptedTermsAndDeclaredAge16' in value) || value['acceptedTermsAndDeclaredAge16'] === undefined) return false;
    return true;
}

export function LegalAcceptanceRequestFromJSON(json: any): LegalAcceptanceRequest {
    return LegalAcceptanceRequestFromJSONTyped(json, false);
}

export function LegalAcceptanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalAcceptanceRequest {
    if (json == null) {
        return json;
    }
    return {

        'termsVersionId': json['termsVersionId'],
        'termsContentDigest': json['termsContentDigest'],
        'acceptedTermsAndDeclaredAge16': json['acceptedTermsAndDeclaredAge16'],
    };
}

export function LegalAcceptanceRequestToJSON(json: any): LegalAcceptanceRequest {
    return LegalAcceptanceRequestToJSONTyped(json, false);
}

export function LegalAcceptanceRequestToJSONTyped(value?: LegalAcceptanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'termsVersionId': value['termsVersionId'],
        'termsContentDigest': value['termsContentDigest'],
        'acceptedTermsAndDeclaredAge16': value['acceptedTermsAndDeclaredAge16'],
    };
}
