/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LegalGetCurrentTermsContent200ResponseTerms } from './LegalGetCurrentTermsContent200ResponseTerms';
import {
    LegalGetCurrentTermsContent200ResponseTermsFromJSON,
    LegalGetCurrentTermsContent200ResponseTermsFromJSONTyped,
    LegalGetCurrentTermsContent200ResponseTermsToJSON,
    LegalGetCurrentTermsContent200ResponseTermsToJSONTyped,
} from './LegalGetCurrentTermsContent200ResponseTerms';

/**
 *
 * @export
 * @interface LegalGetCurrentTermsContent200Response
 */
export interface LegalGetCurrentTermsContent200Response {
    /**
     *
     */
    terms: LegalGetCurrentTermsContent200ResponseTerms;
    /**
     *
     */
    canonicalContent: string;
}

/**
 * Check if a given object implements the LegalGetCurrentTermsContent200Response interface.
 */
export function instanceOfLegalGetCurrentTermsContent200Response(value: object): value is LegalGetCurrentTermsContent200Response {
    if (!('terms' in value) || value['terms'] === undefined) return false;
    if (!('canonicalContent' in value) || value['canonicalContent'] === undefined) return false;
    return true;
}

export function LegalGetCurrentTermsContent200ResponseFromJSON(json: any): LegalGetCurrentTermsContent200Response {
    return LegalGetCurrentTermsContent200ResponseFromJSONTyped(json, false);
}

export function LegalGetCurrentTermsContent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalGetCurrentTermsContent200Response {
    if (json == null) {
        return json;
    }
    return {

        'terms': LegalGetCurrentTermsContent200ResponseTermsFromJSON(json['terms']),
        'canonicalContent': json['canonicalContent'],
    };
}

export function LegalGetCurrentTermsContent200ResponseToJSON(json: any): LegalGetCurrentTermsContent200Response {
    return LegalGetCurrentTermsContent200ResponseToJSONTyped(json, false);
}

export function LegalGetCurrentTermsContent200ResponseToJSONTyped(value?: LegalGetCurrentTermsContent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'terms': LegalGetCurrentTermsContent200ResponseTermsToJSON(value['terms']),
        'canonicalContent': value['canonicalContent'],
    };
}
