/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface LegalGetCurrentTermsContent200ResponseTerms
 */
export interface LegalGetCurrentTermsContent200ResponseTerms {
    /**
     *
     */
    id: string;
    /**
     *
     */
    version: number;
    /**
     *
     */
    contentDigest: string;
    /**
     *
     */
    status: LegalGetCurrentTermsContent200ResponseTermsStatusEnum;
    /**
     *
     */
    effectiveAt: Date;
    /**
     *
     */
    documentUrl: LegalGetCurrentTermsContent200ResponseTermsDocumentUrlEnum;
}


/**
 * @export
 */
export const LegalGetCurrentTermsContent200ResponseTermsStatusEnum = {
    Effective: 'effective',
} as const;
export type LegalGetCurrentTermsContent200ResponseTermsStatusEnum = typeof LegalGetCurrentTermsContent200ResponseTermsStatusEnum[keyof typeof LegalGetCurrentTermsContent200ResponseTermsStatusEnum];

/**
 * @export
 */
export const LegalGetCurrentTermsContent200ResponseTermsDocumentUrlEnum = {
    ApiV1LegalTermsCurrentContent: '/api/v1/legal/terms/current/content',
} as const;
export type LegalGetCurrentTermsContent200ResponseTermsDocumentUrlEnum = typeof LegalGetCurrentTermsContent200ResponseTermsDocumentUrlEnum[keyof typeof LegalGetCurrentTermsContent200ResponseTermsDocumentUrlEnum];


/**
 * Check if a given object implements the LegalGetCurrentTermsContent200ResponseTerms interface.
 */
export function instanceOfLegalGetCurrentTermsContent200ResponseTerms(value: object): value is LegalGetCurrentTermsContent200ResponseTerms {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('contentDigest' in value) || value['contentDigest'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'effective') return false;

    if (!('effectiveAt' in value) || value['effectiveAt'] === undefined) return false;
    if (!('documentUrl' in value) || value['documentUrl'] === undefined) return false;
    if (value['documentUrl'] !== '/api/v1/legal/terms/current/content') return false;

    return true;
}

export function LegalGetCurrentTermsContent200ResponseTermsFromJSON(json: any): LegalGetCurrentTermsContent200ResponseTerms {
    return LegalGetCurrentTermsContent200ResponseTermsFromJSONTyped(json, false);
}

export function LegalGetCurrentTermsContent200ResponseTermsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalGetCurrentTermsContent200ResponseTerms {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'version': json['version'],
        'contentDigest': json['contentDigest'],
        'status': json['status'],
        'effectiveAt': (json['effectiveAt'] == null ? json['effectiveAt'] : parseDateTime(json['effectiveAt'])),
        'documentUrl': json['documentUrl'],
    };
}

export function LegalGetCurrentTermsContent200ResponseTermsToJSON(json: any): LegalGetCurrentTermsContent200ResponseTerms {
    return LegalGetCurrentTermsContent200ResponseTermsToJSONTyped(json, false);
}

export function LegalGetCurrentTermsContent200ResponseTermsToJSONTyped(value?: LegalGetCurrentTermsContent200ResponseTerms | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'version': value['version'],
        'contentDigest': value['contentDigest'],
        'status': value['status'],
        'effectiveAt': value['effectiveAt'] == null ? value['effectiveAt'] : serializeDateTime(value['effectiveAt']),
        'documentUrl': value['documentUrl'],
    };
}
