/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LegalGetCurrentTermsContent200ResponseTerms } from './LegalGetCurrentTermsContent200ResponseTerms';
import {
    LegalGetCurrentTermsContent200ResponseTermsFromJSON,
    LegalGetCurrentTermsContent200ResponseTermsFromJSONTyped,
    LegalGetCurrentTermsContent200ResponseTermsToJSON,
    LegalGetCurrentTermsContent200ResponseTermsToJSONTyped,
} from './LegalGetCurrentTermsContent200ResponseTerms';

/**
 *
 * @export
 * @interface LegalGetCurrentTerms200Response
 */
export interface LegalGetCurrentTerms200Response {
    /**
     *
     */
    terms: LegalGetCurrentTermsContent200ResponseTerms;
}

/**
 * Check if a given object implements the LegalGetCurrentTerms200Response interface.
 */
export function instanceOfLegalGetCurrentTerms200Response(value: object): value is LegalGetCurrentTerms200Response {
    if (!('terms' in value) || value['terms'] === undefined) return false;
    return true;
}

export function LegalGetCurrentTerms200ResponseFromJSON(json: any): LegalGetCurrentTerms200Response {
    return LegalGetCurrentTerms200ResponseFromJSONTyped(json, false);
}

export function LegalGetCurrentTerms200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalGetCurrentTerms200Response {
    if (json == null) {
        return json;
    }
    return {

        'terms': LegalGetCurrentTermsContent200ResponseTermsFromJSON(json['terms']),
    };
}

export function LegalGetCurrentTerms200ResponseToJSON(json: any): LegalGetCurrentTerms200Response {
    return LegalGetCurrentTerms200ResponseToJSONTyped(json, false);
}

export function LegalGetCurrentTerms200ResponseToJSONTyped(value?: LegalGetCurrentTerms200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'terms': LegalGetCurrentTermsContent200ResponseTermsToJSON(value['terms']),
    };
}
