/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface LegalGetPublishedTermsContent200ResponseTerms
 */
export interface LegalGetPublishedTermsContent200ResponseTerms {
    /**
     *
     */
    id: string;
    /**
     *
     */
    version: number;
    /**
     *
     */
    contentDigest: string;
    /**
     *
     */
    status: LegalGetPublishedTermsContent200ResponseTermsStatusEnum;
    /**
     *
     */
    effectiveAt: Date;
    /**
     *
     */
    documentUrl: string;
}


/**
 * @export
 */
export const LegalGetPublishedTermsContent200ResponseTermsStatusEnum = {
    Notice: 'notice',
    Effective: 'effective',
} as const;
export type LegalGetPublishedTermsContent200ResponseTermsStatusEnum = typeof LegalGetPublishedTermsContent200ResponseTermsStatusEnum[keyof typeof LegalGetPublishedTermsContent200ResponseTermsStatusEnum];


/**
 * Check if a given object implements the LegalGetPublishedTermsContent200ResponseTerms interface.
 */
export function instanceOfLegalGetPublishedTermsContent200ResponseTerms(value: object): value is LegalGetPublishedTermsContent200ResponseTerms {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('contentDigest' in value) || value['contentDigest'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('effectiveAt' in value) || value['effectiveAt'] === undefined) return false;
    if (!('documentUrl' in value) || value['documentUrl'] === undefined) return false;
    return true;
}

export function LegalGetPublishedTermsContent200ResponseTermsFromJSON(json: any): LegalGetPublishedTermsContent200ResponseTerms {
    return LegalGetPublishedTermsContent200ResponseTermsFromJSONTyped(json, false);
}

export function LegalGetPublishedTermsContent200ResponseTermsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalGetPublishedTermsContent200ResponseTerms {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'version': json['version'],
        'contentDigest': json['contentDigest'],
        'status': json['status'],
        'effectiveAt': (json['effectiveAt'] == null ? json['effectiveAt'] : parseDateTime(json['effectiveAt'])),
        'documentUrl': json['documentUrl'],
    };
}

export function LegalGetPublishedTermsContent200ResponseTermsToJSON(json: any): LegalGetPublishedTermsContent200ResponseTerms {
    return LegalGetPublishedTermsContent200ResponseTermsToJSONTyped(json, false);
}

export function LegalGetPublishedTermsContent200ResponseTermsToJSONTyped(value?: LegalGetPublishedTermsContent200ResponseTerms | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'version': value['version'],
        'contentDigest': value['contentDigest'],
        'status': value['status'],
        'effectiveAt': value['effectiveAt'] == null ? value['effectiveAt'] : serializeDateTime(value['effectiveAt']),
        'documentUrl': value['documentUrl'],
    };
}
