/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LegalAcceptCurrentTermsRequest
 */
export interface LegalAcceptCurrentTermsRequest {
    /**
     *
     */
    acceptTerms: LegalAcceptCurrentTermsRequestAcceptTermsEnum;
    /**
     *
     */
    declareAge16OrOlder: LegalAcceptCurrentTermsRequestDeclareAge16OrOlderEnum;
    /**
     *
     */
    termsVersionId: string;
    /**
     *
     */
    contentDigest: string;
}


/**
 * @export
 */
export const LegalAcceptCurrentTermsRequestAcceptTermsEnum = {
    True: true,
} as const;
export type LegalAcceptCurrentTermsRequestAcceptTermsEnum = typeof LegalAcceptCurrentTermsRequestAcceptTermsEnum[keyof typeof LegalAcceptCurrentTermsRequestAcceptTermsEnum];

/**
 * @export
 */
export const LegalAcceptCurrentTermsRequestDeclareAge16OrOlderEnum = {
    True: true,
} as const;
export type LegalAcceptCurrentTermsRequestDeclareAge16OrOlderEnum = typeof LegalAcceptCurrentTermsRequestDeclareAge16OrOlderEnum[keyof typeof LegalAcceptCurrentTermsRequestDeclareAge16OrOlderEnum];


/**
 * Check if a given object implements the LegalAcceptCurrentTermsRequest interface.
 */
export function instanceOfLegalAcceptCurrentTermsRequest(value: object): value is LegalAcceptCurrentTermsRequest {
    if (!('acceptTerms' in value) || value['acceptTerms'] === undefined) return false;

    if (value['acceptTerms'] !== true) return false;
    if (!('declareAge16OrOlder' in value) || value['declareAge16OrOlder'] === undefined) return false;

    if (value['declareAge16OrOlder'] !== true) return false;
    if (!('termsVersionId' in value) || value['termsVersionId'] === undefined) return false;
    if (!('contentDigest' in value) || value['contentDigest'] === undefined) return false;
    return true;
}

export function LegalAcceptCurrentTermsRequestFromJSON(json: any): LegalAcceptCurrentTermsRequest {
    return LegalAcceptCurrentTermsRequestFromJSONTyped(json, false);
}

export function LegalAcceptCurrentTermsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalAcceptCurrentTermsRequest {
    if (json == null) {
        return json;
    }
    return {

        'acceptTerms': json['acceptTerms'],
        'declareAge16OrOlder': json['declareAge16OrOlder'],
        'termsVersionId': json['termsVersionId'],
        'contentDigest': json['contentDigest'],
    };
}

export function LegalAcceptCurrentTermsRequestToJSON(json: any): LegalAcceptCurrentTermsRequest {
    return LegalAcceptCurrentTermsRequestToJSONTyped(json, false);
}

export function LegalAcceptCurrentTermsRequestToJSONTyped(value?: LegalAcceptCurrentTermsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'acceptTerms': value['acceptTerms'],
        'declareAge16OrOlder': value['declareAge16OrOlder'],
        'termsVersionId': value['termsVersionId'],
        'contentDigest': value['contentDigest'],
    };
}
