/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface LegalAcceptanceResponse
 */
export interface LegalAcceptanceResponse {
    /**
     *
     */
    termsVersionId: string;
    /**
     *
     */
    acceptedAt: Date;
    /**
     *
     */
    declaredAt: Date;
}

/**
 * Check if a given object implements the LegalAcceptanceResponse interface.
 */
export function instanceOfLegalAcceptanceResponse(value: object): value is LegalAcceptanceResponse {
    if (!('termsVersionId' in value) || value['termsVersionId'] === undefined) return false;
    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    if (!('declaredAt' in value) || value['declaredAt'] === undefined) return false;
    return true;
}

export function LegalAcceptanceResponseFromJSON(json: any): LegalAcceptanceResponse {
    return LegalAcceptanceResponseFromJSONTyped(json, false);
}

export function LegalAcceptanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalAcceptanceResponse {
    if (json == null) {
        return json;
    }
    return {

        'termsVersionId': json['termsVersionId'],
        'acceptedAt': (json['acceptedAt'] == null ? json['acceptedAt'] : parseDateTime(json['acceptedAt'])),
        'declaredAt': (json['declaredAt'] == null ? json['declaredAt'] : parseDateTime(json['declaredAt'])),
    };
}

export function LegalAcceptanceResponseToJSON(json: any): LegalAcceptanceResponse {
    return LegalAcceptanceResponseToJSONTyped(json, false);
}

export function LegalAcceptanceResponseToJSONTyped(value?: LegalAcceptanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'termsVersionId': value['termsVersionId'],
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : serializeDateTime(value['acceptedAt']),
        'declaredAt': value['declaredAt'] == null ? value['declaredAt'] : serializeDateTime(value['declaredAt']),
    };
}
