/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Conversation } from './Conversation';
import {
    ConversationFromJSON,
    ConversationFromJSONTyped,
    ConversationToJSON,
    ConversationToJSONTyped,
} from './Conversation';

/**
 *
 * @export
 * @interface ListConversations200Response
 */
export interface ListConversations200Response {
    /**
     *
     */
    items: Array<Conversation>;
    /**
     *
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ListConversations200Response interface.
 */
export function instanceOfListConversations200Response(value: object): value is ListConversations200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function ListConversations200ResponseFromJSON(json: any): ListConversations200Response {
    return ListConversations200ResponseFromJSONTyped(json, false);
}

export function ListConversations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConversations200Response {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ConversationFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function ListConversations200ResponseToJSON(json: any): ListConversations200Response {
    return ListConversations200ResponseToJSONTyped(json, false);
}

export function ListConversations200ResponseToJSONTyped(value?: ListConversations200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ConversationToJSON)),
        'nextCursor': value['nextCursor'],
    };
}
