/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListConversationChanges200ResponseItemsInner } from './ListConversationChanges200ResponseItemsInner';
import {
    ListConversationChanges200ResponseItemsInnerFromJSON,
    ListConversationChanges200ResponseItemsInnerFromJSONTyped,
    ListConversationChanges200ResponseItemsInnerToJSON,
    ListConversationChanges200ResponseItemsInnerToJSONTyped,
} from './ListConversationChanges200ResponseItemsInner';

/**
 *
 * @export
 * @interface ListConversationChanges200Response
 */
export interface ListConversationChanges200Response {
    /**
     *
     */
    items: Array<ListConversationChanges200ResponseItemsInner>;
    /**
     *
     */
    nextChangeSequence: string | null;
    /**
     *
     */
    hasMore: boolean;
    /**
     *
     */
    highWatermark: string;
}

/**
 * Check if a given object implements the ListConversationChanges200Response interface.
 */
export function instanceOfListConversationChanges200Response(value: object): value is ListConversationChanges200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextChangeSequence' in value) || value['nextChangeSequence'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('highWatermark' in value) || value['highWatermark'] === undefined) return false;
    return true;
}

export function ListConversationChanges200ResponseFromJSON(json: any): ListConversationChanges200Response {
    return ListConversationChanges200ResponseFromJSONTyped(json, false);
}

export function ListConversationChanges200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConversationChanges200Response {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ListConversationChanges200ResponseItemsInnerFromJSON)),
        'nextChangeSequence': json['nextChangeSequence'],
        'hasMore': json['hasMore'],
        'highWatermark': json['highWatermark'],
    };
}

export function ListConversationChanges200ResponseToJSON(json: any): ListConversationChanges200Response {
    return ListConversationChanges200ResponseToJSONTyped(json, false);
}

export function ListConversationChanges200ResponseToJSONTyped(value?: ListConversationChanges200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ListConversationChanges200ResponseItemsInnerToJSON)),
        'nextChangeSequence': value['nextChangeSequence'],
        'hasMore': value['hasMore'],
        'highWatermark': value['highWatermark'],
    };
}
