/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MarkConversationRead200Response
 */
export interface MarkConversationRead200Response {
    /**
     *
     */
    lastReadSequence: string;
    /**
     *
     */
    receiptSequence: string;
    /**
     *
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the MarkConversationRead200Response interface.
 */
export function instanceOfMarkConversationRead200Response(value: object): value is MarkConversationRead200Response {
    if (!('lastReadSequence' in value) || value['lastReadSequence'] === undefined) return false;
    if (!('receiptSequence' in value) || value['receiptSequence'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function MarkConversationRead200ResponseFromJSON(json: any): MarkConversationRead200Response {
    return MarkConversationRead200ResponseFromJSONTyped(json, false);
}

export function MarkConversationRead200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkConversationRead200Response {
    if (json == null) {
        return json;
    }
    return {

        'lastReadSequence': json['lastReadSequence'],
        'receiptSequence': json['receiptSequence'],
        'unreadCount': json['unreadCount'],
    };
}

export function MarkConversationRead200ResponseToJSON(json: any): MarkConversationRead200Response {
    return MarkConversationRead200ResponseToJSONTyped(json, false);
}

export function MarkConversationRead200ResponseToJSONTyped(value?: MarkConversationRead200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'lastReadSequence': value['lastReadSequence'],
        'receiptSequence': value['receiptSequence'],
        'unreadCount': value['unreadCount'],
    };
}
