/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Null when unset or when the bio is hidden.
 * @export
 */
export const Mbti = {
    Intj: 'INTJ',
    Intp: 'INTP',
    Entj: 'ENTJ',
    Entp: 'ENTP',
    Infj: 'INFJ',
    Infp: 'INFP',
    Enfj: 'ENFJ',
    Enfp: 'ENFP',
    Istj: 'ISTJ',
    Isfj: 'ISFJ',
    Estj: 'ESTJ',
    Esfj: 'ESFJ',
    Istp: 'ISTP',
    Isfp: 'ISFP',
    Estp: 'ESTP',
    Esfp: 'ESFP',
} as const;
export type Mbti = typeof Mbti[keyof typeof Mbti];


export function instanceOfMbti(value: any): boolean {
    for (const key in Mbti) {
        if (Object.prototype.hasOwnProperty.call(Mbti, key)) {
            if (Mbti[key as keyof typeof Mbti] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MbtiFromJSON(json: any): Mbti {
    return MbtiFromJSONTyped(json, false);
}

export function MbtiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mbti {
    return json as Mbti;
}

export function MbtiToJSON(value?: Mbti | null): any {
    return value as any;
}

export function MbtiToJSONTyped(value: any, ignoreDiscriminator: boolean): Mbti {
    return value as Mbti;
}
