/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { MediaContentType } from './MediaContentType';
import {
    MediaContentTypeFromJSON,
    MediaContentTypeFromJSONTyped,
    MediaContentTypeToJSON,
    MediaContentTypeToJSONTyped,
} from './MediaContentType';
import type { MediaValidationFailureReason } from './MediaValidationFailureReason';
import {
    MediaValidationFailureReasonFromJSON,
    MediaValidationFailureReasonFromJSONTyped,
    MediaValidationFailureReasonToJSON,
    MediaValidationFailureReasonToJSONTyped,
} from './MediaValidationFailureReason';
import type { MediaReservationStatus } from './MediaReservationStatus';
import {
    MediaReservationStatusFromJSON,
    MediaReservationStatusFromJSONTyped,
    MediaReservationStatusToJSON,
    MediaReservationStatusToJSONTyped,
} from './MediaReservationStatus';

/**
 *
 * @export
 * @interface MediaReservation
 */
export interface MediaReservation {
    /**
     *
     */
    id: string;
    /**
     *
     */
    contentType: MediaContentType;
    /**
     *
     */
    byteSize: number;
    /**
     *
     */
    status: MediaReservationStatus;
    /**
     *
     */
    failureReason?: MediaValidationFailureReason;
    /**
     *
     */
    createdAt: Date;
    /**
     *
     */
    validatedAt?: Date;
    /**
     *
     */
    expiresAt: Date;
}



/**
 * Check if a given object implements the MediaReservation interface.
 */
export function instanceOfMediaReservation(value: object): value is MediaReservation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('byteSize' in value) || value['byteSize'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function MediaReservationFromJSON(json: any): MediaReservation {
    return MediaReservationFromJSONTyped(json, false);
}

export function MediaReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaReservation {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'contentType': MediaContentTypeFromJSON(json['contentType']),
        'byteSize': json['byteSize'],
        'status': MediaReservationStatusFromJSON(json['status']),
        'failureReason': json['failureReason'] == null ? undefined : MediaValidationFailureReasonFromJSON(json['failureReason']),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'validatedAt': json['validatedAt'] == null ? undefined : (parseDateTime(json['validatedAt'])),
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
    };
}

export function MediaReservationToJSON(json: any): MediaReservation {
    return MediaReservationToJSONTyped(json, false);
}

export function MediaReservationToJSONTyped(value?: MediaReservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'contentType': MediaContentTypeToJSON(value['contentType']),
        'byteSize': value['byteSize'],
        'status': MediaReservationStatusToJSON(value['status']),
        'failureReason': MediaValidationFailureReasonToJSON(value['failureReason']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'validatedAt': value['validatedAt'] == null ? value['validatedAt'] : serializeDateTime(value['validatedAt']),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}
