/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MediaReservationUpload
 */
export interface MediaReservationUpload {
    /**
     *
     */
    url: string;
    /**
     *
     */
    method: MediaReservationUploadMethodEnum;
    /**
     *
     */
    requiredHeaders: { [key: string]: string; };
}


/**
 * @export
 */
export const MediaReservationUploadMethodEnum = {
    Put: 'PUT',
} as const;
export type MediaReservationUploadMethodEnum = typeof MediaReservationUploadMethodEnum[keyof typeof MediaReservationUploadMethodEnum];


/**
 * Check if a given object implements the MediaReservationUpload interface.
 */
export function instanceOfMediaReservationUpload(value: object): value is MediaReservationUpload {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (value['method'] !== 'PUT') return false;

    if (!('requiredHeaders' in value) || value['requiredHeaders'] === undefined) return false;
    return true;
}

export function MediaReservationUploadFromJSON(json: any): MediaReservationUpload {
    return MediaReservationUploadFromJSONTyped(json, false);
}

export function MediaReservationUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaReservationUpload {
    if (json == null) {
        return json;
    }
    return {

        'url': json['url'],
        'method': json['method'],
        'requiredHeaders': json['requiredHeaders'],
    };
}

export function MediaReservationUploadToJSON(json: any): MediaReservationUpload {
    return MediaReservationUploadToJSONTyped(json, false);
}

export function MediaReservationUploadToJSONTyped(value?: MediaReservationUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'url': value['url'],
        'method': value['method'],
        'requiredHeaders': value['requiredHeaders'],
    };
}
