/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface MessageReplyPreview
 */
export interface MessageReplyPreview {
    /**
     *
     */
    id: string;
    /**
     *
     */
    senderId: string;
    /**
     *
     */
    text: string | null;
    /**
     *
     */
    unsentAt: Date | null;
}

/**
 * Check if a given object implements the MessageReplyPreview interface.
 */
export function instanceOfMessageReplyPreview(value: object): value is MessageReplyPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('unsentAt' in value) || value['unsentAt'] === undefined) return false;
    return true;
}

export function MessageReplyPreviewFromJSON(json: any): MessageReplyPreview {
    return MessageReplyPreviewFromJSONTyped(json, false);
}

export function MessageReplyPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageReplyPreview {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'senderId': json['senderId'],
        'text': json['text'],
        'unsentAt': (json['unsentAt'] == null ? null : parseDateTime(json['unsentAt'])),
    };
}

export function MessageReplyPreviewToJSON(json: any): MessageReplyPreview {
    return MessageReplyPreviewToJSONTyped(json, false);
}

export function MessageReplyPreviewToJSONTyped(value?: MessageReplyPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'senderId': value['senderId'],
        'text': value['text'],
        'unsentAt': value['unsentAt'] == null ? value['unsentAt'] : serializeDateTime(value['unsentAt']),
    };
}
