/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MessageReactionsInnerReactorsInner
 */
export interface MessageReactionsInnerReactorsInner {
    /**
     *
     */
    id: string;
    /**
     *
     */
    name: string;
}

/**
 * Check if a given object implements the MessageReactionsInnerReactorsInner interface.
 */
export function instanceOfMessageReactionsInnerReactorsInner(value: object): value is MessageReactionsInnerReactorsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MessageReactionsInnerReactorsInnerFromJSON(json: any): MessageReactionsInnerReactorsInner {
    return MessageReactionsInnerReactorsInnerFromJSONTyped(json, false);
}

export function MessageReactionsInnerReactorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageReactionsInnerReactorsInner {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
    };
}

export function MessageReactionsInnerReactorsInnerToJSON(json: any): MessageReactionsInnerReactorsInner {
    return MessageReactionsInnerReactorsInnerToJSONTyped(json, false);
}

export function MessageReactionsInnerReactorsInnerToJSONTyped(value?: MessageReactionsInnerReactorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
    };
}
