/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DirectMessageSendQuotaError } from './DirectMessageSendQuotaError';
import {
    DirectMessageSendQuotaErrorFromJSON,
    DirectMessageSendQuotaErrorFromJSONTyped,
    DirectMessageSendQuotaErrorToJSON,
    DirectMessageSendQuotaErrorToJSONTyped,
} from './DirectMessageSendQuotaError';
import type { DirectMessageSendQuotaErrorError } from './DirectMessageSendQuotaErrorError';
import {
    DirectMessageSendQuotaErrorErrorFromJSON,
    DirectMessageSendQuotaErrorErrorFromJSONTyped,
    DirectMessageSendQuotaErrorErrorToJSON,
    DirectMessageSendQuotaErrorErrorToJSONTyped,
} from './DirectMessageSendQuotaErrorError';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 *
 * @export
 * @interface MessageCreationRateLimitError
 */
export interface MessageCreationRateLimitError {
    /**
     *
     */
    error: DirectMessageSendQuotaErrorError;
}

/**
 * Check if a given object implements the MessageCreationRateLimitError interface.
 */
export function instanceOfMessageCreationRateLimitError(value: object): value is MessageCreationRateLimitError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function MessageCreationRateLimitErrorFromJSON(json: any): MessageCreationRateLimitError {
    return MessageCreationRateLimitErrorFromJSONTyped(json, false);
}

export function MessageCreationRateLimitErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageCreationRateLimitError {
    if (json == null) {
        return json;
    }
    return {

        'error': DirectMessageSendQuotaErrorErrorFromJSON(json['error']),
    };
}

export function MessageCreationRateLimitErrorToJSON(json: any): MessageCreationRateLimitError {
    return MessageCreationRateLimitErrorToJSONTyped(json, false);
}

export function MessageCreationRateLimitErrorToJSONTyped(value?: MessageCreationRateLimitError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': DirectMessageSendQuotaErrorErrorToJSON(value['error']),
    };
}
