/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { MessageReplyPreview } from './MessageReplyPreview';
import {
    MessageReplyPreviewFromJSON,
    MessageReplyPreviewFromJSONTyped,
    MessageReplyPreviewToJSON,
    MessageReplyPreviewToJSONTyped,
} from './MessageReplyPreview';
import type { MessageReactionsInner } from './MessageReactionsInner';
import {
    MessageReactionsInnerFromJSON,
    MessageReactionsInnerFromJSONTyped,
    MessageReactionsInnerToJSON,
    MessageReactionsInnerToJSONTyped,
} from './MessageReactionsInner';

/**
 *
 * @export
 * @interface Message
 */
export interface Message {
    /**
     *
     */
    id: string;
    /**
     *
     */
    conversationId: string;
    /**
     *
     */
    sequence: string;
    /**
     *
     */
    senderId: string;
    /**
     *
     */
    clientMessageId: string;
    /**
     *
     */
    text: string | null;
    /**
     *
     */
    replyToMessageId: string | null;
    /**
     *
     */
    replyPreview: MessageReplyPreview | null;
    /**
     *
     */
    version: number;
    /**
     *
     */
    createdAt: Date;
    /**
     *
     */
    editedAt: Date | null;
    /**
     *
     */
    unsentAt: Date | null;
    /**
     *
     */
    reactions: Array<MessageReactionsInner>;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('clientMessageId' in value) || value['clientMessageId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('replyToMessageId' in value) || value['replyToMessageId'] === undefined) return false;
    if (!('replyPreview' in value) || value['replyPreview'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('editedAt' in value) || value['editedAt'] === undefined) return false;
    if (!('unsentAt' in value) || value['unsentAt'] === undefined) return false;
    if (!('reactions' in value) || value['reactions'] === undefined) return false;
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'conversationId': json['conversationId'],
        'sequence': json['sequence'],
        'senderId': json['senderId'],
        'clientMessageId': json['clientMessageId'],
        'text': json['text'],
        'replyToMessageId': json['replyToMessageId'],
        'replyPreview': MessageReplyPreviewFromJSON(json['replyPreview']),
        'version': json['version'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'editedAt': (json['editedAt'] == null ? null : parseDateTime(json['editedAt'])),
        'unsentAt': (json['unsentAt'] == null ? null : parseDateTime(json['unsentAt'])),
        'reactions': ((json['reactions'] as Array<any>).map(MessageReactionsInnerFromJSON)),
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'conversationId': value['conversationId'],
        'sequence': value['sequence'],
        'senderId': value['senderId'],
        'clientMessageId': value['clientMessageId'],
        'text': value['text'],
        'replyToMessageId': value['replyToMessageId'],
        'replyPreview': MessageReplyPreviewToJSON(value['replyPreview']),
        'version': value['version'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'editedAt': value['editedAt'] == null ? value['editedAt'] : serializeDateTime(value['editedAt']),
        'unsentAt': value['unsentAt'] == null ? value['unsentAt'] : serializeDateTime(value['unsentAt']),
        'reactions': ((value['reactions'] as Array<any>).map(MessageReactionsInnerToJSON)),
    };
}
