/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MessageReactionsInner
 */
export interface MessageReactionsInner {
    /**
     *
     */
    reaction: MessageReactionsInnerReactionEnum;
    /**
     *
     */
    count: number;
    /**
     *
     */
    reactedByActor: boolean;
}


/**
 * @export
 */
export const MessageReactionsInnerReactionEnum = {
    Like: 'like',
    Love: 'love',
    Laugh: 'laugh',
    Surprised: 'surprised',
    Sad: 'sad',
    Thanks: 'thanks',
} as const;
export type MessageReactionsInnerReactionEnum = typeof MessageReactionsInnerReactionEnum[keyof typeof MessageReactionsInnerReactionEnum];


/**
 * Check if a given object implements the MessageReactionsInner interface.
 */
export function instanceOfMessageReactionsInner(value: object): value is MessageReactionsInner {
    if (!('reaction' in value) || value['reaction'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('reactedByActor' in value) || value['reactedByActor'] === undefined) return false;
    return true;
}

export function MessageReactionsInnerFromJSON(json: any): MessageReactionsInner {
    return MessageReactionsInnerFromJSONTyped(json, false);
}

export function MessageReactionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageReactionsInner {
    if (json == null) {
        return json;
    }
    return {

        'reaction': json['reaction'],
        'count': json['count'],
        'reactedByActor': json['reactedByActor'],
    };
}

export function MessageReactionsInnerToJSON(json: any): MessageReactionsInner {
    return MessageReactionsInnerToJSONTyped(json, false);
}

export function MessageReactionsInnerToJSONTyped(value?: MessageReactionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reaction': value['reaction'],
        'count': value['count'],
        'reactedByActor': value['reactedByActor'],
    };
}
