/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MoodDay
 */
export interface MoodDay {
    /**
     *
     */
    localDate: string;
    /**
     *
     */
    rating: number;
}

/**
 * Check if a given object implements the MoodDay interface.
 */
export function instanceOfMoodDay(value: object): value is MoodDay {
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function MoodDayFromJSON(json: any): MoodDay {
    return MoodDayFromJSONTyped(json, false);
}

export function MoodDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoodDay {
    if (json == null) {
        return json;
    }
    return {

        'localDate': json['localDate'],
        'rating': json['rating'],
    };
}

export function MoodDayToJSON(json: any): MoodDay {
    return MoodDayToJSONTyped(json, false);
}

export function MoodDayToJSONTyped(value?: MoodDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'localDate': value['localDate'],
        'rating': value['rating'],
    };
}
