/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The requested range, ending today.
 * @export
 * @interface MoodPeriodSummary
 */
export interface MoodPeriodSummary {
    /**
     *
     */
    from: string;
    /**
     *
     */
    to: string;
    /**
     * Days in the period since the account's first day. Earlier days are not missing data.
     */
    trackedDays: number;
    /**
     * Days with a rating the caller can see.
     */
    postedDays: number;
    /**
     * Tracked days that ended without any post. A post the caller can't see is not missing, and today is not missing while it is still open.
     */
    missingDays: number;
    /**
     * Mean visible rating to one decimal place, or null with none.
     */
    average: number | null;
    /**
     *
     */
    lowest: number | null;
    /**
     *
     */
    highest: number | null;
}

/**
 * Check if a given object implements the MoodPeriodSummary interface.
 */
export function instanceOfMoodPeriodSummary(value: object): value is MoodPeriodSummary {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('trackedDays' in value) || value['trackedDays'] === undefined) return false;
    if (!('postedDays' in value) || value['postedDays'] === undefined) return false;
    if (!('missingDays' in value) || value['missingDays'] === undefined) return false;
    if (!('average' in value) || value['average'] === undefined) return false;
    if (!('lowest' in value) || value['lowest'] === undefined) return false;
    if (!('highest' in value) || value['highest'] === undefined) return false;
    return true;
}

export function MoodPeriodSummaryFromJSON(json: any): MoodPeriodSummary {
    return MoodPeriodSummaryFromJSONTyped(json, false);
}

export function MoodPeriodSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoodPeriodSummary {
    if (json == null) {
        return json;
    }
    return {

        'from': json['from'],
        'to': json['to'],
        'trackedDays': json['trackedDays'],
        'postedDays': json['postedDays'],
        'missingDays': json['missingDays'],
        'average': json['average'],
        'lowest': json['lowest'],
        'highest': json['highest'],
    };
}

export function MoodPeriodSummaryToJSON(json: any): MoodPeriodSummary {
    return MoodPeriodSummaryToJSONTyped(json, false);
}

export function MoodPeriodSummaryToJSONTyped(value?: MoodPeriodSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'from': value['from'],
        'to': value['to'],
        'trackedDays': value['trackedDays'],
        'postedDays': value['postedDays'],
        'missingDays': value['missingDays'],
        'average': value['average'],
        'lowest': value['lowest'],
        'highest': value['highest'],
    };
}
