/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MoodDay } from './MoodDay';
import {
    MoodDayFromJSON,
    MoodDayFromJSONTyped,
    MoodDayToJSON,
    MoodDayToJSONTyped,
} from './MoodDay';
import type { MoodPeriodSummary } from './MoodPeriodSummary';
import {
    MoodPeriodSummaryFromJSON,
    MoodPeriodSummaryFromJSONTyped,
    MoodPeriodSummaryToJSON,
    MoodPeriodSummaryToJSONTyped,
} from './MoodPeriodSummary';

/**
 * The caller's own ratings, including solo and unreleased posts. Deleted posts are left out.
 * @export
 * @interface MoodHistory
 */
export interface MoodHistory {
    /**
     *
     */
    range: MoodHistoryRangeEnum;
    /**
     * The account's first Auckland day, or its earliest post if that is sooner.
     */
    trackedFrom: string;
    /**
     * Posted days in the current period, oldest first. Days without a post are left out.
     */
    days: Array<MoodDay>;
    /**
     *
     */
    current: MoodPeriodSummary;
    /**
     * The same-length range just before it, for comparison.
     */
    previous: MoodPeriodSummary;
}


/**
 * @export
 */
export const MoodHistoryRangeEnum = {
    _30d: '30d',
    _90d: '90d',
    _1y: '1y',
} as const;
export type MoodHistoryRangeEnum = typeof MoodHistoryRangeEnum[keyof typeof MoodHistoryRangeEnum];


/**
 * Check if a given object implements the MoodHistory interface.
 */
export function instanceOfMoodHistory(value: object): value is MoodHistory {
    if (!('range' in value) || value['range'] === undefined) return false;
    if (!('trackedFrom' in value) || value['trackedFrom'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    return true;
}

export function MoodHistoryFromJSON(json: any): MoodHistory {
    return MoodHistoryFromJSONTyped(json, false);
}

export function MoodHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoodHistory {
    if (json == null) {
        return json;
    }
    return {

        'range': json['range'],
        'trackedFrom': json['trackedFrom'],
        'days': ((json['days'] as Array<any>).map(MoodDayFromJSON)),
        'current': MoodPeriodSummaryFromJSON(json['current']),
        'previous': MoodPeriodSummaryFromJSON(json['previous']),
    };
}

export function MoodHistoryToJSON(json: any): MoodHistory {
    return MoodHistoryToJSONTyped(json, false);
}

export function MoodHistoryToJSONTyped(value?: MoodHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'range': value['range'],
        'trackedFrom': value['trackedFrom'],
        'days': ((value['days'] as Array<any>).map(MoodDayToJSON)),
        'current': MoodPeriodSummaryToJSON(value['current']),
        'previous': MoodPeriodSummaryToJSON(value['previous']),
    };
}
