/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnThisDayMemory } from './OnThisDayMemory';
import {
    OnThisDayMemoryFromJSON,
    OnThisDayMemoryFromJSONTyped,
    OnThisDayMemoryToJSON,
    OnThisDayMemoryToJSONTyped,
} from './OnThisDayMemory';

/**
 *
 * @export
 * @interface OnThisDayMemories
 */
export interface OnThisDayMemories {
    /**
     * Today's Auckland date, chosen by the server.
     */
    date: string;
    /**
     * At most one memory per earlier year, newest year first.
     */
    items: Array<OnThisDayMemory>;
}

/**
 * Check if a given object implements the OnThisDayMemories interface.
 */
export function instanceOfOnThisDayMemories(value: object): value is OnThisDayMemories {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function OnThisDayMemoriesFromJSON(json: any): OnThisDayMemories {
    return OnThisDayMemoriesFromJSONTyped(json, false);
}

export function OnThisDayMemoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnThisDayMemories {
    if (json == null) {
        return json;
    }
    return {

        'date': json['date'],
        'items': ((json['items'] as Array<any>).map(OnThisDayMemoryFromJSON)),
    };
}

export function OnThisDayMemoriesToJSON(json: any): OnThisDayMemories {
    return OnThisDayMemoriesToJSONTyped(json, false);
}

export function OnThisDayMemoriesToJSONTyped(value?: OnThisDayMemories | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'date': value['date'],
        'items': ((value['items'] as Array<any>).map(OnThisDayMemoryToJSON)),
    };
}
