/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostMedia } from './PostMedia';
import {
    PostMediaFromJSON,
    PostMediaFromJSONTyped,
    PostMediaToJSON,
    PostMediaToJSONTyped,
} from './PostMedia';
import type { OnThisDayMemoryPrompt } from './OnThisDayMemoryPrompt';
import {
    OnThisDayMemoryPromptFromJSON,
    OnThisDayMemoryPromptFromJSONTyped,
    OnThisDayMemoryPromptToJSON,
    OnThisDayMemoryPromptToJSONTyped,
} from './OnThisDayMemoryPrompt';

/**
 * One of the caller's own earlier posts. Tomorrow notes are not part of this projection.
 * @export
 * @interface OnThisDayMemory
 */
export interface OnThisDayMemory {
    /**
     *
     */
    id: string;
    /**
     * The Auckland day the post was written for.
     */
    localDate: string;
    /**
     * Whole years between the post's Auckland day and today.
     */
    yearsAgo: number;
    /**
     *
     */
    rating: number;
    /**
     * Who could read the post. Memories are owner-only either way; this labels the original audience.
     */
    audience: OnThisDayMemoryAudienceEnum;
    /**
     *
     */
    prompt: OnThisDayMemoryPrompt;
    /**
     *
     */
    reflectiveAnswer: string;
    /**
     *
     */
    caption: string | null;
    /**
     * True when the author has edited the post since it was accepted.
     */
    edited: boolean;
    /**
     * Attached photos or video in display order, each with a private download URL that expires after 5 minutes.
     */
    media: Array<PostMedia>;
}


/**
 * @export
 */
export const OnThisDayMemoryAudienceEnum = {
    Solo: 'solo',
    Friends: 'friends',
} as const;
export type OnThisDayMemoryAudienceEnum = typeof OnThisDayMemoryAudienceEnum[keyof typeof OnThisDayMemoryAudienceEnum];


/**
 * Check if a given object implements the OnThisDayMemory interface.
 */
export function instanceOfOnThisDayMemory(value: object): value is OnThisDayMemory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('yearsAgo' in value) || value['yearsAgo'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('reflectiveAnswer' in value) || value['reflectiveAnswer'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('edited' in value) || value['edited'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function OnThisDayMemoryFromJSON(json: any): OnThisDayMemory {
    return OnThisDayMemoryFromJSONTyped(json, false);
}

export function OnThisDayMemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnThisDayMemory {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'localDate': json['localDate'],
        'yearsAgo': json['yearsAgo'],
        'rating': json['rating'],
        'audience': json['audience'],
        'prompt': OnThisDayMemoryPromptFromJSON(json['prompt']),
        'reflectiveAnswer': json['reflectiveAnswer'],
        'caption': json['caption'],
        'edited': json['edited'],
        'media': ((json['media'] as Array<any>).map(PostMediaFromJSON)),
    };
}

export function OnThisDayMemoryToJSON(json: any): OnThisDayMemory {
    return OnThisDayMemoryToJSONTyped(json, false);
}

export function OnThisDayMemoryToJSONTyped(value?: OnThisDayMemory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'localDate': value['localDate'],
        'yearsAgo': value['yearsAgo'],
        'rating': value['rating'],
        'audience': value['audience'],
        'prompt': OnThisDayMemoryPromptToJSON(value['prompt']),
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'edited': value['edited'],
        'media': ((value['media'] as Array<any>).map(PostMediaToJSON)),
    };
}
