/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PasswordReauthenticationRequest
 */
export interface PasswordReauthenticationRequest {
    /**
     *
     */
    action: PasswordReauthenticationRequestActionEnum;
    /**
     *
     */
    password: string;
}


/**
 * @export
 */
export const PasswordReauthenticationRequestActionEnum = {
    RequestDeletion: 'request_deletion',
    CancelDeletion: 'cancel_deletion',
} as const;
export type PasswordReauthenticationRequestActionEnum = typeof PasswordReauthenticationRequestActionEnum[keyof typeof PasswordReauthenticationRequestActionEnum];


/**
 * Check if a given object implements the PasswordReauthenticationRequest interface.
 */
export function instanceOfPasswordReauthenticationRequest(value: object): value is PasswordReauthenticationRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PasswordReauthenticationRequestFromJSON(json: any): PasswordReauthenticationRequest {
    return PasswordReauthenticationRequestFromJSONTyped(json, false);
}

export function PasswordReauthenticationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordReauthenticationRequest {
    if (json == null) {
        return json;
    }
    return {

        'action': json['action'],
        'password': json['password'],
    };
}

export function PasswordReauthenticationRequestToJSON(json: any): PasswordReauthenticationRequest {
    return PasswordReauthenticationRequestToJSONTyped(json, false);
}

export function PasswordReauthenticationRequestToJSONTyped(value?: PasswordReauthenticationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'action': value['action'],
        'password': value['password'],
    };
}
