/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface PasswordReauthenticationGrant
 */
export interface PasswordReauthenticationGrant {
    /**
     *
     */
    token: string;
    /**
     *
     */
    expiresAt: Date;
    /**
     *
     */
    action: PasswordReauthenticationGrantActionEnum;
}


/**
 * @export
 */
export const PasswordReauthenticationGrantActionEnum = {
    RequestDeletion: 'request_deletion',
    CancelDeletion: 'cancel_deletion',
} as const;
export type PasswordReauthenticationGrantActionEnum = typeof PasswordReauthenticationGrantActionEnum[keyof typeof PasswordReauthenticationGrantActionEnum];


/**
 * Check if a given object implements the PasswordReauthenticationGrant interface.
 */
export function instanceOfPasswordReauthenticationGrant(value: object): value is PasswordReauthenticationGrant {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function PasswordReauthenticationGrantFromJSON(json: any): PasswordReauthenticationGrant {
    return PasswordReauthenticationGrantFromJSONTyped(json, false);
}

export function PasswordReauthenticationGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordReauthenticationGrant {
    if (json == null) {
        return json;
    }
    return {

        'token': json['token'],
        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
        'action': json['action'],
    };
}

export function PasswordReauthenticationGrantToJSON(json: any): PasswordReauthenticationGrant {
    return PasswordReauthenticationGrantToJSONTyped(json, false);
}

export function PasswordReauthenticationGrantToJSONTyped(value?: PasswordReauthenticationGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'token': value['token'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'action': value['action'],
    };
}
