/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface PendingRelationshipRequest
 */
export interface PendingRelationshipRequest {
    /**
     *
     */
    id: string;
    /**
     *
     */
    senderId: string;
    /**
     *
     */
    recipientId: string;
    /**
     *
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PendingRelationshipRequest interface.
 */
export function instanceOfPendingRelationshipRequest(value: object): value is PendingRelationshipRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('recipientId' in value) || value['recipientId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PendingRelationshipRequestFromJSON(json: any): PendingRelationshipRequest {
    return PendingRelationshipRequestFromJSONTyped(json, false);
}

export function PendingRelationshipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingRelationshipRequest {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'senderId': json['senderId'],
        'recipientId': json['recipientId'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function PendingRelationshipRequestToJSON(json: any): PendingRelationshipRequest {
    return PendingRelationshipRequestToJSONTyped(json, false);
}

export function PendingRelationshipRequestToJSONTyped(value?: PendingRelationshipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'senderId': value['senderId'],
        'recipientId': value['recipientId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}
