/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PendingRelationshipRequest } from './PendingRelationshipRequest';
import {
    PendingRelationshipRequestFromJSON,
    PendingRelationshipRequestFromJSONTyped,
    PendingRelationshipRequestToJSON,
    PendingRelationshipRequestToJSONTyped,
} from './PendingRelationshipRequest';

/**
 *
 * @export
 * @interface PendingRequestPage
 */
export interface PendingRequestPage {
    /**
     *
     */
    items: Array<PendingRelationshipRequest>;
    /**
     *
     */
    nextCursor: string | null;
    /**
     *
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PendingRequestPage interface.
 */
export function instanceOfPendingRequestPage(value: object): value is PendingRequestPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function PendingRequestPageFromJSON(json: any): PendingRequestPage {
    return PendingRequestPageFromJSONTyped(json, false);
}

export function PendingRequestPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingRequestPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(PendingRelationshipRequestFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function PendingRequestPageToJSON(json: any): PendingRequestPage {
    return PendingRequestPageToJSONTyped(json, false);
}

export function PendingRequestPageToJSONTyped(value?: PendingRequestPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(PendingRelationshipRequestToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
