/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The prompt stored with the post, not the current day's prompt.
 * @export
 * @interface PostDetailPrompt
 */
export interface PostDetailPrompt {
    /**
     *
     */
    id: string;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the PostDetailPrompt interface.
 */
export function instanceOfPostDetailPrompt(value: object): value is PostDetailPrompt {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PostDetailPromptFromJSON(json: any): PostDetailPrompt {
    return PostDetailPromptFromJSONTyped(json, false);
}

export function PostDetailPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetailPrompt {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'text': json['text'],
    };
}

export function PostDetailPromptToJSON(json: any): PostDetailPrompt {
    return PostDetailPromptToJSONTyped(json, false);
}

export function PostDetailPromptToJSONTyped(value?: PostDetailPrompt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'text': value['text'],
    };
}
