/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const PostAudience = {
    Solo: 'solo',
    Friends: 'friends',
} as const;
export type PostAudience = typeof PostAudience[keyof typeof PostAudience];


export function instanceOfPostAudience(value: any): boolean {
    for (const key in PostAudience) {
        if (Object.prototype.hasOwnProperty.call(PostAudience, key)) {
            if (PostAudience[key as keyof typeof PostAudience] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PostAudienceFromJSON(json: any): PostAudience {
    return PostAudienceFromJSONTyped(json, false);
}

export function PostAudienceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAudience {
    return json as PostAudience;
}

export function PostAudienceToJSON(value?: PostAudience | null): any {
    return value as any;
}

export function PostAudienceToJSONTyped(value: any, ignoreDiscriminator: boolean): PostAudience {
    return value as PostAudience;
}
