/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { PostAudience } from './PostAudience';
import {
    PostAudienceFromJSON,
    PostAudienceFromJSONTyped,
    PostAudienceToJSON,
    PostAudienceToJSONTyped,
} from './PostAudience';

/**
 * An earlier version of a post, which an edit replaced at `replacedAt`. The prompt, day and media are the same as the current post.
 * @export
 * @interface PostRevision
 */
export interface PostRevision {
    /**
     * 1 is the version first posted.
     */
    revisionNumber: number;
    /**
     *
     */
    reflectiveAnswer: string;
    /**
     *
     */
    caption: string | null;
    /**
     *
     */
    rating: number;
    /**
     *
     */
    audience: PostAudience;
    /**
     *
     */
    replacedAt: Date;
}



/**
 * Check if a given object implements the PostRevision interface.
 */
export function instanceOfPostRevision(value: object): value is PostRevision {
    if (!('revisionNumber' in value) || value['revisionNumber'] === undefined) return false;
    if (!('reflectiveAnswer' in value) || value['reflectiveAnswer'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if (!('replacedAt' in value) || value['replacedAt'] === undefined) return false;
    return true;
}

export function PostRevisionFromJSON(json: any): PostRevision {
    return PostRevisionFromJSONTyped(json, false);
}

export function PostRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRevision {
    if (json == null) {
        return json;
    }
    return {

        'revisionNumber': json['revisionNumber'],
        'reflectiveAnswer': json['reflectiveAnswer'],
        'caption': json['caption'],
        'rating': json['rating'],
        'audience': PostAudienceFromJSON(json['audience']),
        'replacedAt': (json['replacedAt'] == null ? json['replacedAt'] : parseDateTime(json['replacedAt'])),
    };
}

export function PostRevisionToJSON(json: any): PostRevision {
    return PostRevisionToJSONTyped(json, false);
}

export function PostRevisionToJSONTyped(value?: PostRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'revisionNumber': value['revisionNumber'],
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'rating': value['rating'],
        'audience': PostAudienceToJSON(value['audience']),
        'replacedAt': value['replacedAt'] == null ? value['replacedAt'] : serializeDateTime(value['replacedAt']),
    };
}
