/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostWeatherCondition } from './PostWeatherCondition';
import {
    PostWeatherConditionFromJSON,
    PostWeatherConditionFromJSONTyped,
    PostWeatherConditionToJSON,
    PostWeatherConditionToJSONTyped,
} from './PostWeatherCondition';

/**
 * A post's weather snapshot as its author's phone reported it. Not verified by the server.
 * @export
 * @interface PostWeather
 */
export interface PostWeather {
    /**
     *
     */
    condition: PostWeatherCondition;
    /**
     * Whole degrees Celsius.
     */
    temperatureC: number;
    /**
     * A place name such as a city, trimmed, 1 to 80 characters, with no control characters. Never an address or coordinates.
     */
    placeName: string;
}



/**
 * Check if a given object implements the PostWeather interface.
 */
export function instanceOfPostWeather(value: object): value is PostWeather {
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if (!('temperatureC' in value) || value['temperatureC'] === undefined) return false;
    if (!('placeName' in value) || value['placeName'] === undefined) return false;
    return true;
}

export function PostWeatherFromJSON(json: any): PostWeather {
    return PostWeatherFromJSONTyped(json, false);
}

export function PostWeatherFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWeather {
    if (json == null) {
        return json;
    }
    return {

        'condition': PostWeatherConditionFromJSON(json['condition']),
        'temperatureC': json['temperatureC'],
        'placeName': json['placeName'],
    };
}

export function PostWeatherToJSON(json: any): PostWeather {
    return PostWeatherToJSONTyped(json, false);
}

export function PostWeatherToJSONTyped(value?: PostWeather | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'condition': PostWeatherConditionToJSON(value['condition']),
        'temperatureC': value['temperatureC'],
        'placeName': value['placeName'],
    };
}
