/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostsRestore200Response
 */
export interface PostsRestore200Response {
    /**
     *
     */
    status: PostsRestore200ResponseStatusEnum;
}


/**
 * @export
 */
export const PostsRestore200ResponseStatusEnum = {
    Restored: 'restored',
} as const;
export type PostsRestore200ResponseStatusEnum = typeof PostsRestore200ResponseStatusEnum[keyof typeof PostsRestore200ResponseStatusEnum];


/**
 * Check if a given object implements the PostsRestore200Response interface.
 */
export function instanceOfPostsRestore200Response(value: object): value is PostsRestore200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'restored') return false;

    return true;
}

export function PostsRestore200ResponseFromJSON(json: any): PostsRestore200Response {
    return PostsRestore200ResponseFromJSONTyped(json, false);
}

export function PostsRestore200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsRestore200Response {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'],
    };
}

export function PostsRestore200ResponseToJSON(json: any): PostsRestore200Response {
    return PostsRestore200ResponseToJSONTyped(json, false);
}

export function PostsRestore200ResponseToJSONTyped(value?: PostsRestore200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status': value['status'],
    };
}
