/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { VoiceMemoContentType } from './VoiceMemoContentType';
import {
    VoiceMemoContentTypeFromJSON,
    VoiceMemoContentTypeFromJSONTyped,
    VoiceMemoContentTypeToJSON,
    VoiceMemoContentTypeToJSONTyped,
} from './VoiceMemoContentType';

/**
 *
 * @export
 * @interface PostVoiceMemo
 */
export interface PostVoiceMemo {
    /**
     *
     */
    id: string;
    /**
     *
     */
    contentType: VoiceMemoContentType;
    /**
     * A private download URL that expires at expiresAt. When media storage is unavailable, a response that would include a voice memo is a 503 instead.
     */
    url: string;
    /**
     * When a signed private URL stops working. Null for a Worker URL that reauthorizes every request.
     */
    expiresAt: Date | null;
}



/**
 * Check if a given object implements the PostVoiceMemo interface.
 */
export function instanceOfPostVoiceMemo(value: object): value is PostVoiceMemo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function PostVoiceMemoFromJSON(json: any): PostVoiceMemo {
    return PostVoiceMemoFromJSONTyped(json, false);
}

export function PostVoiceMemoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVoiceMemo {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'contentType': VoiceMemoContentTypeFromJSON(json['contentType']),
        'url': json['url'],
        'expiresAt': (json['expiresAt'] == null ? null : parseDateTime(json['expiresAt'])),
    };
}

export function PostVoiceMemoToJSON(json: any): PostVoiceMemo {
    return PostVoiceMemoToJSONTyped(json, false);
}

export function PostVoiceMemoToJSONTyped(value?: PostVoiceMemo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'contentType': VoiceMemoContentTypeToJSON(value['contentType']),
        'url': value['url'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}
