/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { PostVoiceMemo } from './PostVoiceMemo';
import {
    PostVoiceMemoFromJSON,
    PostVoiceMemoFromJSONTyped,
    PostVoiceMemoToJSON,
    PostVoiceMemoToJSONTyped,
} from './PostVoiceMemo';
import type { PostMedia } from './PostMedia';
import {
    PostMediaFromJSON,
    PostMediaFromJSONTyped,
    PostMediaToJSON,
    PostMediaToJSONTyped,
} from './PostMedia';
import type { PostDetailPrompt } from './PostDetailPrompt';
import {
    PostDetailPromptFromJSON,
    PostDetailPromptFromJSONTyped,
    PostDetailPromptToJSON,
    PostDetailPromptToJSONTyped,
} from './PostDetailPrompt';
import type { PostDetailAuthor } from './PostDetailAuthor';
import {
    PostDetailAuthorFromJSON,
    PostDetailAuthorFromJSONTyped,
    PostDetailAuthorToJSON,
    PostDetailAuthorToJSONTyped,
} from './PostDetailAuthor';

/**
 * One post the caller may read, including an anonymously readable public-profile post. Tomorrow notes are not part of this projection.
 * @export
 * @interface PostDetail
 */
export interface PostDetail {
    /**
     *
     */
    id: string;
    /**
     *
     */
    author: PostDetailAuthor;
    /**
     *
     */
    localDate: string;
    /**
     *
     */
    prompt: PostDetailPrompt;
    /**
     *
     */
    reflectiveAnswer: string;
    /**
     *
     */
    caption: string | null;
    /**
     *
     */
    rating: number;
    /**
     *
     */
    audience: PostDetailAudienceEnum;
    /**
     *
     */
    acceptedAt: Date;
    /**
     *
     */
    releasedAt: Date;
    /**
     * True when the caller can read an earlier version of the post.
     */
    edited: boolean;
    /**
     * Earlier versions the caller can read. The author sees every saved edit and sends this as `expectedRevisionCount` when editing. Anyone else sees only versions that were already shared with friends.
     */
    revisionCount: number;
    /**
     *
     */
    viewerIsAuthor: boolean;
    /**
     * Attached photos or video in display order, each with a private download URL that expires after 5 minutes.
     */
    media: Array<PostMedia>;
    /**
     * The post's voice memo with a private download URL that expires after 5 minutes, or null when the post has none. Only post detail carries it; feeds and profile lists do not.
     */
    voiceMemo: PostVoiceMemo | null;
}


/**
 * @export
 */
export const PostDetailAudienceEnum = {
    Solo: 'solo',
    Friends: 'friends',
} as const;
export type PostDetailAudienceEnum = typeof PostDetailAudienceEnum[keyof typeof PostDetailAudienceEnum];


/**
 * Check if a given object implements the PostDetail interface.
 */
export function instanceOfPostDetail(value: object): value is PostDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('reflectiveAnswer' in value) || value['reflectiveAnswer'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    if (!('releasedAt' in value) || value['releasedAt'] === undefined) return false;
    if (!('edited' in value) || value['edited'] === undefined) return false;
    if (!('revisionCount' in value) || value['revisionCount'] === undefined) return false;
    if (!('viewerIsAuthor' in value) || value['viewerIsAuthor'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    if (!('voiceMemo' in value) || value['voiceMemo'] === undefined) return false;
    return true;
}

export function PostDetailFromJSON(json: any): PostDetail {
    return PostDetailFromJSONTyped(json, false);
}

export function PostDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetail {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'author': PostDetailAuthorFromJSON(json['author']),
        'localDate': json['localDate'],
        'prompt': PostDetailPromptFromJSON(json['prompt']),
        'reflectiveAnswer': json['reflectiveAnswer'],
        'caption': json['caption'],
        'rating': json['rating'],
        'audience': json['audience'],
        'acceptedAt': (json['acceptedAt'] == null ? json['acceptedAt'] : parseDateTime(json['acceptedAt'])),
        'releasedAt': (json['releasedAt'] == null ? json['releasedAt'] : parseDateTime(json['releasedAt'])),
        'edited': json['edited'],
        'revisionCount': json['revisionCount'],
        'viewerIsAuthor': json['viewerIsAuthor'],
        'media': ((json['media'] as Array<any>).map(PostMediaFromJSON)),
        'voiceMemo': PostVoiceMemoFromJSON(json['voiceMemo']),
    };
}

export function PostDetailToJSON(json: any): PostDetail {
    return PostDetailToJSONTyped(json, false);
}

export function PostDetailToJSONTyped(value?: PostDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'author': PostDetailAuthorToJSON(value['author']),
        'localDate': value['localDate'],
        'prompt': PostDetailPromptToJSON(value['prompt']),
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'rating': value['rating'],
        'audience': value['audience'],
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : serializeDateTime(value['acceptedAt']),
        'releasedAt': value['releasedAt'] == null ? value['releasedAt'] : serializeDateTime(value['releasedAt']),
        'edited': value['edited'],
        'revisionCount': value['revisionCount'],
        'viewerIsAuthor': value['viewerIsAuthor'],
        'media': ((value['media'] as Array<any>).map(PostMediaToJSON)),
        'voiceMemo': PostVoiceMemoToJSON(value['voiceMemo']),
    };
}
