/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const PostWeatherCondition = {
    Clear: 'clear',
    PartlyCloudy: 'partly_cloudy',
    Cloudy: 'cloudy',
    Fog: 'fog',
    Drizzle: 'drizzle',
    Rain: 'rain',
    Snow: 'snow',
    Thunderstorm: 'thunderstorm',
} as const;
export type PostWeatherCondition = typeof PostWeatherCondition[keyof typeof PostWeatherCondition];


export function instanceOfPostWeatherCondition(value: any): boolean {
    for (const key in PostWeatherCondition) {
        if (Object.prototype.hasOwnProperty.call(PostWeatherCondition, key)) {
            if (PostWeatherCondition[key as keyof typeof PostWeatherCondition] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PostWeatherConditionFromJSON(json: any): PostWeatherCondition {
    return PostWeatherConditionFromJSONTyped(json, false);
}

export function PostWeatherConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWeatherCondition {
    return json as PostWeatherCondition;
}

export function PostWeatherConditionToJSON(value?: PostWeatherCondition | null): any {
    return value as any;
}

export function PostWeatherConditionToJSONTyped(value: any, ignoreDiscriminator: boolean): PostWeatherCondition {
    return value as PostWeatherCondition;
}
