/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostDetailAuthor
 */
export interface PostDetailAuthor {
    /**
     *
     */
    id: string;
    /**
     *
     */
    username: string;
    /**
     *
     */
    displayName: string;
}

/**
 * Check if a given object implements the PostDetailAuthor interface.
 */
export function instanceOfPostDetailAuthor(value: object): value is PostDetailAuthor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function PostDetailAuthorFromJSON(json: any): PostDetailAuthor {
    return PostDetailAuthorFromJSONTyped(json, false);
}

export function PostDetailAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetailAuthor {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'username': json['username'],
        'displayName': json['displayName'],
    };
}

export function PostDetailAuthorToJSON(json: any): PostDetailAuthor {
    return PostDetailAuthorToJSONTyped(json, false);
}

export function PostDetailAuthorToJSONTyped(value?: PostDetailAuthor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'username': value['username'],
        'displayName': value['displayName'],
    };
}
