/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostLikeSummary
 */
export interface PostLikeSummary {
    /**
     *
     */
    likeCount: number;
    /**
     *
     */
    viewerHasLiked: boolean;
}

/**
 * Check if a given object implements the PostLikeSummary interface.
 */
export function instanceOfPostLikeSummary(value: object): value is PostLikeSummary {
    if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
    if (!('viewerHasLiked' in value) || value['viewerHasLiked'] === undefined) return false;
    return true;
}

export function PostLikeSummaryFromJSON(json: any): PostLikeSummary {
    return PostLikeSummaryFromJSONTyped(json, false);
}

export function PostLikeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLikeSummary {
    if (json == null) {
        return json;
    }
    return {

        'likeCount': json['likeCount'],
        'viewerHasLiked': json['viewerHasLiked'],
    };
}

export function PostLikeSummaryToJSON(json: any): PostLikeSummary {
    return PostLikeSummaryToJSONTyped(json, false);
}

export function PostLikeSummaryToJSONTyped(value?: PostLikeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'likeCount': value['likeCount'],
        'viewerHasLiked': value['viewerHasLiked'],
    };
}
