/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostLike } from './PostLike';
import {
    PostLikeFromJSON,
    PostLikeFromJSONTyped,
    PostLikeToJSON,
    PostLikeToJSONTyped,
} from './PostLike';

/**
 *
 * @export
 * @interface PostLikesPage
 */
export interface PostLikesPage {
    /**
     *
     */
    items: Array<PostLike>;
    /**
     *
     */
    nextCursor: string | null;
    /**
     *
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PostLikesPage interface.
 */
export function instanceOfPostLikesPage(value: object): value is PostLikesPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function PostLikesPageFromJSON(json: any): PostLikesPage {
    return PostLikesPageFromJSONTyped(json, false);
}

export function PostLikesPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLikesPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(PostLikeFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function PostLikesPageToJSON(json: any): PostLikesPage {
    return PostLikesPageToJSONTyped(json, false);
}

export function PostLikesPageToJSONTyped(value?: PostLikesPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(PostLikeToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
