/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileOwnerSettings } from './ProfileOwnerSettings';
import {
    ProfileOwnerSettingsFromJSON,
    ProfileOwnerSettingsFromJSONTyped,
    ProfileOwnerSettingsToJSON,
    ProfileOwnerSettingsToJSONTyped,
} from './ProfileOwnerSettings';
import type { ProfileStats } from './ProfileStats';
import {
    ProfileStatsFromJSON,
    ProfileStatsFromJSONTyped,
    ProfileStatsToJSON,
    ProfileStatsToJSONTyped,
} from './ProfileStats';
import type { PostingStreak } from './PostingStreak';
import {
    PostingStreakFromJSON,
    PostingStreakFromJSONTyped,
    PostingStreakToJSON,
    PostingStreakToJSONTyped,
} from './PostingStreak';

/**
 *
 * @export
 * @interface ProfileDetails
 */
export interface ProfileDetails {
    /**
     *
     */
    id: string;
    /**
     * The current handle. It differs from the requested one when that was a handle the owner has since changed.
     */
    username: string;
    /**
     *
     */
    displayName: string;
    /**
     * False when the account is private and the caller is not an active friend. The bio is then null.
     */
    detailsVisible: boolean;
    /**
     *
     */
    bio: string;
    /**
     *
     */
    streak: PostingStreak;
    /**
     *
     */
    stats: ProfileStats;
    /**
     *
     */
    owner: ProfileOwnerSettings;
}

/**
 * Check if a given object implements the ProfileDetails interface.
 */
export function instanceOfProfileDetails(value: object): value is ProfileDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('detailsVisible' in value) || value['detailsVisible'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('streak' in value) || value['streak'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function ProfileDetailsFromJSON(json: any): ProfileDetails {
    return ProfileDetailsFromJSONTyped(json, false);
}

export function ProfileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDetails {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'username': json['username'],
        'displayName': json['displayName'],
        'detailsVisible': json['detailsVisible'],
        'bio': json['bio'],
        'streak': PostingStreakFromJSON(json['streak']),
        'stats': ProfileStatsFromJSON(json['stats']),
        'owner': ProfileOwnerSettingsFromJSON(json['owner']),
    };
}

export function ProfileDetailsToJSON(json: any): ProfileDetails {
    return ProfileDetailsToJSONTyped(json, false);
}

export function ProfileDetailsToJSONTyped(value?: ProfileDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'username': value['username'],
        'displayName': value['displayName'],
        'detailsVisible': value['detailsVisible'],
        'bio': value['bio'],
        'streak': PostingStreakToJSON(value['streak']),
        'stats': ProfileStatsToJSON(value['stats']),
        'owner': ProfileOwnerSettingsToJSON(value['owner']),
    };
}
