/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Null whenever the bio is hidden.
 * @export
 * @interface ProfileStats
 */
export interface ProfileStats {
    /**
     * Accepted posts, solo ones included; the streak already reveals which days had one.
     */
    posts: number;
    /**
     *
     */
    friends: number;
    /**
     * Likes on the person's posts that haven't been deleted.
     */
    loved: number;
}

/**
 * Check if a given object implements the ProfileStats interface.
 */
export function instanceOfProfileStats(value: object): value is ProfileStats {
    if (!('posts' in value) || value['posts'] === undefined) return false;
    if (!('friends' in value) || value['friends'] === undefined) return false;
    if (!('loved' in value) || value['loved'] === undefined) return false;
    return true;
}

export function ProfileStatsFromJSON(json: any): ProfileStats {
    return ProfileStatsFromJSONTyped(json, false);
}

export function ProfileStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileStats {
    if (json == null) {
        return json;
    }
    return {

        'posts': json['posts'],
        'friends': json['friends'],
        'loved': json['loved'],
    };
}

export function ProfileStatsToJSON(json: any): ProfileStats {
    return ProfileStatsToJSONTyped(json, false);
}

export function ProfileStatsToJSONTyped(value?: ProfileStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'posts': value['posts'],
        'friends': value['friends'],
        'loved': value['loved'],
    };
}
