/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ProfilePostPrompt } from './ProfilePostPrompt';
import {
    ProfilePostPromptFromJSON,
    ProfilePostPromptFromJSONTyped,
    ProfilePostPromptToJSON,
    ProfilePostPromptToJSONTyped,
} from './ProfilePostPrompt';
import type { PostMedia } from './PostMedia';
import {
    PostMediaFromJSON,
    PostMediaFromJSONTyped,
    PostMediaToJSON,
    PostMediaToJSONTyped,
} from './PostMedia';
import type { ProfilePostAuthor } from './ProfilePostAuthor';
import {
    ProfilePostAuthorFromJSON,
    ProfilePostAuthorFromJSONTyped,
    ProfilePostAuthorToJSON,
    ProfilePostAuthorToJSONTyped,
} from './ProfilePostAuthor';

/**
 * One post on a profile. Tomorrow notes are not part of this projection.
 * @export
 * @interface ProfilePost
 */
export interface ProfilePost {
    /**
     *
     */
    id: string;
    /**
     *
     */
    author: ProfilePostAuthor;
    /**
     *
     */
    localDate: string;
    /**
     *
     */
    prompt: ProfilePostPrompt;
    /**
     *
     */
    reflectiveAnswer: string;
    /**
     *
     */
    caption: string | null;
    /**
     *
     */
    rating: number;
    /**
     * `solo` appears only on the caller's own profile.
     */
    audience: ProfilePostAudienceEnum;
    /**
     *
     */
    acceptedAt: Date;
    /**
     *
     */
    releasedAt: Date;
    /**
     * False only on the caller's own profile, for a post whose day has not been released yet.
     */
    released: boolean;
    /**
     * True when the author has edited the post since it was accepted.
     */
    edited: boolean;
    /**
     * Attached photos or video in display order, each with a private download URL that expires after 5 minutes.
     */
    media: Array<PostMedia>;
}


/**
 * @export
 */
export const ProfilePostAudienceEnum = {
    Solo: 'solo',
    Friends: 'friends',
} as const;
export type ProfilePostAudienceEnum = typeof ProfilePostAudienceEnum[keyof typeof ProfilePostAudienceEnum];


/**
 * Check if a given object implements the ProfilePost interface.
 */
export function instanceOfProfilePost(value: object): value is ProfilePost {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('reflectiveAnswer' in value) || value['reflectiveAnswer'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    if (!('releasedAt' in value) || value['releasedAt'] === undefined) return false;
    if (!('released' in value) || value['released'] === undefined) return false;
    if (!('edited' in value) || value['edited'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function ProfilePostFromJSON(json: any): ProfilePost {
    return ProfilePostFromJSONTyped(json, false);
}

export function ProfilePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilePost {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'author': ProfilePostAuthorFromJSON(json['author']),
        'localDate': json['localDate'],
        'prompt': ProfilePostPromptFromJSON(json['prompt']),
        'reflectiveAnswer': json['reflectiveAnswer'],
        'caption': json['caption'],
        'rating': json['rating'],
        'audience': json['audience'],
        'acceptedAt': (json['acceptedAt'] == null ? json['acceptedAt'] : parseDateTime(json['acceptedAt'])),
        'releasedAt': (json['releasedAt'] == null ? json['releasedAt'] : parseDateTime(json['releasedAt'])),
        'released': json['released'],
        'edited': json['edited'],
        'media': ((json['media'] as Array<any>).map(PostMediaFromJSON)),
    };
}

export function ProfilePostToJSON(json: any): ProfilePost {
    return ProfilePostToJSONTyped(json, false);
}

export function ProfilePostToJSONTyped(value?: ProfilePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'author': ProfilePostAuthorToJSON(value['author']),
        'localDate': value['localDate'],
        'prompt': ProfilePostPromptToJSON(value['prompt']),
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'rating': value['rating'],
        'audience': value['audience'],
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : serializeDateTime(value['acceptedAt']),
        'releasedAt': value['releasedAt'] == null ? value['releasedAt'] : serializeDateTime(value['releasedAt']),
        'released': value['released'],
        'edited': value['edited'],
        'media': ((value['media'] as Array<any>).map(PostMediaToJSON)),
    };
}
