/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileOwnerSettings } from './ProfileOwnerSettings';
import {
    ProfileOwnerSettingsFromJSON,
    ProfileOwnerSettingsFromJSONTyped,
    ProfileOwnerSettingsToJSON,
    ProfileOwnerSettingsToJSONTyped,
} from './ProfileOwnerSettings';
import type { ProfileStats } from './ProfileStats';
import {
    ProfileStatsFromJSON,
    ProfileStatsFromJSONTyped,
    ProfileStatsToJSON,
    ProfileStatsToJSONTyped,
} from './ProfileStats';
import type { PostingStreak } from './PostingStreak';
import {
    PostingStreakFromJSON,
    PostingStreakFromJSONTyped,
    PostingStreakToJSON,
    PostingStreakToJSONTyped,
} from './PostingStreak';
import type { Mbti } from './Mbti';
import {
    MbtiFromJSON,
    MbtiFromJSONTyped,
    MbtiToJSON,
    MbtiToJSONTyped,
} from './Mbti';

/**
 * A restricted response has only kind and username. A public response adds displayName, bio, avatarUrl, and streak. An authorized response has every ProfileDetails field.
 * @export
 * @interface ReadableProfile
 */
export interface ReadableProfile {
    /**
     *
     */
    kind: ReadableProfileKindEnum;
    /**
     *
     */
    username: string;
    /**
     *
     */
    id?: string;
    /**
     *
     */
    displayName?: string;
    /**
     * False when the account is private and the caller is not an active friend. The bio is then null.
     */
    detailsVisible?: boolean;
    /**
     *
     */
    bio?: string | null;
    /**
     *
     */
    mbti?: Mbti | null;
    /**
     * Null when unset or when the bio is hidden.
     */
    whatIDo?: string | null;
    /**
     * Null when unset or when the bio is hidden.
     */
    listeningTo?: string | null;
    /**
     * A link to the profile photo that expires after 10 minutes. Null when there is no photo or the bio is hidden.
     */
    avatarUrl?: string | null;
    /**
     *
     */
    streak?: PostingStreak | null;
    /**
     *
     */
    stats?: ProfileStats | null;
    /**
     *
     */
    owner?: ProfileOwnerSettings | null;
}


/**
 * @export
 */
export const ReadableProfileKindEnum = {
    Authorized: 'authorized',
    Public: 'public',
    Restricted: 'restricted',
} as const;
export type ReadableProfileKindEnum = typeof ReadableProfileKindEnum[keyof typeof ReadableProfileKindEnum];


/**
 * Check if a given object implements the ReadableProfile interface.
 */
export function instanceOfReadableProfile(value: object): value is ReadableProfile {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ReadableProfileFromJSON(json: any): ReadableProfile {
    return ReadableProfileFromJSONTyped(json, false);
}

export function ReadableProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadableProfile {
    if (json == null) {
        return json;
    }
    return {

        'kind': json['kind'],
        'username': json['username'],
        'id': json['id'] == null ? undefined : json['id'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'detailsVisible': json['detailsVisible'] == null ? undefined : json['detailsVisible'],
        'bio': json['bio'] === undefined ? undefined : json['bio'] === null ? null : json['bio'],
        'mbti': json['mbti'] === undefined ? undefined : json['mbti'] === null ? null : MbtiFromJSON(json['mbti']),
        'whatIDo': json['whatIDo'] === undefined ? undefined : json['whatIDo'] === null ? null : json['whatIDo'],
        'listeningTo': json['listeningTo'] === undefined ? undefined : json['listeningTo'] === null ? null : json['listeningTo'],
        'avatarUrl': json['avatarUrl'] === undefined ? undefined : json['avatarUrl'] === null ? null : json['avatarUrl'],
        'streak': json['streak'] === undefined ? undefined : json['streak'] === null ? null : PostingStreakFromJSON(json['streak']),
        'stats': json['stats'] === undefined ? undefined : json['stats'] === null ? null : ProfileStatsFromJSON(json['stats']),
        'owner': json['owner'] === undefined ? undefined : json['owner'] === null ? null : ProfileOwnerSettingsFromJSON(json['owner']),
    };
}

export function ReadableProfileToJSON(json: any): ReadableProfile {
    return ReadableProfileToJSONTyped(json, false);
}

export function ReadableProfileToJSONTyped(value?: ReadableProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kind': value['kind'],
        'username': value['username'],
        'id': value['id'],
        'displayName': value['displayName'],
        'detailsVisible': value['detailsVisible'],
        'bio': value['bio'],
        'mbti': MbtiToJSON(value['mbti']),
        'whatIDo': value['whatIDo'],
        'listeningTo': value['listeningTo'],
        'avatarUrl': value['avatarUrl'],
        'streak': PostingStreakToJSON(value['streak']),
        'stats': ProfileStatsToJSON(value['stats']),
        'owner': ProfileOwnerSettingsToJSON(value['owner']),
    };
}
