/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfilePost } from './ProfilePost';
import {
    ProfilePostFromJSON,
    ProfilePostFromJSONTyped,
    ProfilePostToJSON,
    ProfilePostToJSONTyped,
} from './ProfilePost';

/**
 * A restricted response has only kind and username. An archive response has kind and every ProfilePostsPage field.
 * @export
 * @interface ReadableProfilePosts
 */
export interface ReadableProfilePosts {
    /**
     *
     */
    kind: ReadableProfilePostsKindEnum;
    /**
     *
     */
    username?: string;
    /**
     *
     */
    items?: Array<ProfilePost>;
    /**
     *
     */
    nextCursor?: string | null;
    /**
     *
     */
    hasMore?: boolean;
}


/**
 * @export
 */
export const ReadableProfilePostsKindEnum = {
    Archive: 'archive',
    Restricted: 'restricted',
} as const;
export type ReadableProfilePostsKindEnum = typeof ReadableProfilePostsKindEnum[keyof typeof ReadableProfilePostsKindEnum];


/**
 * Check if a given object implements the ReadableProfilePosts interface.
 */
export function instanceOfReadableProfilePosts(value: object): value is ReadableProfilePosts {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function ReadableProfilePostsFromJSON(json: any): ReadableProfilePosts {
    return ReadableProfilePostsFromJSONTyped(json, false);
}

export function ReadableProfilePostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadableProfilePosts {
    if (json == null) {
        return json;
    }
    return {

        'kind': json['kind'],
        'username': json['username'] == null ? undefined : json['username'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ProfilePostFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : json['nextCursor'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function ReadableProfilePostsToJSON(json: any): ReadableProfilePosts {
    return ReadableProfilePostsToJSONTyped(json, false);
}

export function ReadableProfilePostsToJSONTyped(value?: ReadableProfilePosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kind': value['kind'],
        'username': value['username'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ProfilePostToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
