/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegistrationIntentRequest
 */
export interface RegistrationIntentRequest {
    /**
     *
     */
    flow: RegistrationIntentRequestFlowEnum;
    /**
     *
     */
    termsVersionId: string;
    /**
     *
     */
    termsContentDigest: string;
    /**
     *
     */
    acceptedTermsAndDeclaredAge16: boolean;
}


/**
 * @export
 */
export const RegistrationIntentRequestFlowEnum = {
    Email: 'email',
    GoogleNative: 'google_native',
    GoogleBrowser: 'google_browser',
} as const;
export type RegistrationIntentRequestFlowEnum = typeof RegistrationIntentRequestFlowEnum[keyof typeof RegistrationIntentRequestFlowEnum];


/**
 * Check if a given object implements the RegistrationIntentRequest interface.
 */
export function instanceOfRegistrationIntentRequest(value: object): value is RegistrationIntentRequest {
    if (!('flow' in value) || value['flow'] === undefined) return false;
    if (!('termsVersionId' in value) || value['termsVersionId'] === undefined) return false;
    if (!('termsContentDigest' in value) || value['termsContentDigest'] === undefined) return false;
    if (!('acceptedTermsAndDeclaredAge16' in value) || value['acceptedTermsAndDeclaredAge16'] === undefined) return false;
    return true;
}

export function RegistrationIntentRequestFromJSON(json: any): RegistrationIntentRequest {
    return RegistrationIntentRequestFromJSONTyped(json, false);
}

export function RegistrationIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationIntentRequest {
    if (json == null) {
        return json;
    }
    return {

        'flow': json['flow'],
        'termsVersionId': json['termsVersionId'],
        'termsContentDigest': json['termsContentDigest'],
        'acceptedTermsAndDeclaredAge16': json['acceptedTermsAndDeclaredAge16'],
    };
}

export function RegistrationIntentRequestToJSON(json: any): RegistrationIntentRequest {
    return RegistrationIntentRequestToJSONTyped(json, false);
}

export function RegistrationIntentRequestToJSONTyped(value?: RegistrationIntentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'flow': value['flow'],
        'termsVersionId': value['termsVersionId'],
        'termsContentDigest': value['termsContentDigest'],
        'acceptedTermsAndDeclaredAge16': value['acceptedTermsAndDeclaredAge16'],
    };
}
