/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipUserCard } from './RelationshipUserCard';
import {
    RelationshipUserCardFromJSON,
    RelationshipUserCardFromJSONTyped,
    RelationshipUserCardToJSON,
    RelationshipUserCardToJSONTyped,
} from './RelationshipUserCard';

/**
 *
 * @export
 * @interface RelationshipUserPage
 */
export interface RelationshipUserPage {
    /**
     *
     */
    items: Array<RelationshipUserCard>;
    /**
     *
     */
    nextCursor: string | null;
    /**
     *
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the RelationshipUserPage interface.
 */
export function instanceOfRelationshipUserPage(value: object): value is RelationshipUserPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function RelationshipUserPageFromJSON(json: any): RelationshipUserPage {
    return RelationshipUserPageFromJSONTyped(json, false);
}

export function RelationshipUserPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipUserPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(RelationshipUserCardFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function RelationshipUserPageToJSON(json: any): RelationshipUserPage {
    return RelationshipUserPageToJSONTyped(json, false);
}

export function RelationshipUserPageToJSONTyped(value?: RelationshipUserPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(RelationshipUserCardToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
