/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const RelationshipState = {
    None: 'none',
    OutgoingPending: 'outgoing_pending',
    IncomingPending: 'incoming_pending',
    Friends: 'friends',
    Blocked: 'blocked',
} as const;
export type RelationshipState = typeof RelationshipState[keyof typeof RelationshipState];


export function instanceOfRelationshipState(value: any): boolean {
    for (const key in RelationshipState) {
        if (Object.prototype.hasOwnProperty.call(RelationshipState, key)) {
            if (RelationshipState[key as keyof typeof RelationshipState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RelationshipStateFromJSON(json: any): RelationshipState {
    return RelationshipStateFromJSONTyped(json, false);
}

export function RelationshipStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipState {
    return json as RelationshipState;
}

export function RelationshipStateToJSON(value?: RelationshipState | null): any {
    return value as any;
}

export function RelationshipStateToJSONTyped(value: any, ignoreDiscriminator: boolean): RelationshipState {
    return value as RelationshipState;
}
