/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipState } from './RelationshipState';
import {
    RelationshipStateFromJSON,
    RelationshipStateFromJSONTyped,
    RelationshipStateToJSON,
    RelationshipStateToJSONTyped,
} from './RelationshipState';

/**
 * Minimal discovery card. It grants no profile access and never contains email, bio, image, or visibility.
 * @export
 * @interface RelationshipUserCard
 */
export interface RelationshipUserCard {
    /**
     *
     */
    id: string;
    /**
     *
     */
    username: string;
    /**
     *
     */
    displayName: string;
    /**
     *
     */
    relationship: RelationshipState;
}



/**
 * Check if a given object implements the RelationshipUserCard interface.
 */
export function instanceOfRelationshipUserCard(value: object): value is RelationshipUserCard {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('relationship' in value) || value['relationship'] === undefined) return false;
    return true;
}

export function RelationshipUserCardFromJSON(json: any): RelationshipUserCard {
    return RelationshipUserCardFromJSONTyped(json, false);
}

export function RelationshipUserCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipUserCard {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'username': json['username'],
        'displayName': json['displayName'],
        'relationship': RelationshipStateFromJSON(json['relationship']),
    };
}

export function RelationshipUserCardToJSON(json: any): RelationshipUserCard {
    return RelationshipUserCardToJSONTyped(json, false);
}

export function RelationshipUserCardToJSONTyped(value?: RelationshipUserCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'username': value['username'],
        'displayName': value['displayName'],
        'relationship': RelationshipStateToJSON(value['relationship']),
    };
}
