/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipState } from './RelationshipState';
import {
    RelationshipStateFromJSON,
    RelationshipStateFromJSONTyped,
    RelationshipStateToJSON,
    RelationshipStateToJSONTyped,
} from './RelationshipState';
import type { PendingRelationshipRequest } from './PendingRelationshipRequest';
import {
    PendingRelationshipRequestFromJSON,
    PendingRelationshipRequestFromJSONTyped,
    PendingRelationshipRequestToJSON,
    PendingRelationshipRequestToJSONTyped,
} from './PendingRelationshipRequest';

/**
 *
 * @export
 * @interface RelationshipStatus
 */
export interface RelationshipStatus {
    /**
     *
     */
    userId: string;
    /**
     *
     */
    status: RelationshipState;
    /**
     *
     */
    incomingRequest: PendingRelationshipRequest | null;
    /**
     *
     */
    outgoingRequest: PendingRelationshipRequest | null;
}



/**
 * Check if a given object implements the RelationshipStatus interface.
 */
export function instanceOfRelationshipStatus(value: object): value is RelationshipStatus {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('incomingRequest' in value) || value['incomingRequest'] === undefined) return false;
    if (!('outgoingRequest' in value) || value['outgoingRequest'] === undefined) return false;
    return true;
}

export function RelationshipStatusFromJSON(json: any): RelationshipStatus {
    return RelationshipStatusFromJSONTyped(json, false);
}

export function RelationshipStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipStatus {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['userId'],
        'status': RelationshipStateFromJSON(json['status']),
        'incomingRequest': PendingRelationshipRequestFromJSON(json['incomingRequest']),
        'outgoingRequest': PendingRelationshipRequestFromJSON(json['outgoingRequest']),
    };
}

export function RelationshipStatusToJSON(json: any): RelationshipStatus {
    return RelationshipStatusToJSONTyped(json, false);
}

export function RelationshipStatusToJSONTyped(value?: RelationshipStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'userId': value['userId'],
        'status': RelationshipStateToJSON(value['status']),
        'incomingRequest': PendingRelationshipRequestToJSON(value['incomingRequest']),
        'outgoingRequest': PendingRelationshipRequestToJSON(value['outgoingRequest']),
    };
}
