/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResolveMessageRequestRequest
 */
export interface ResolveMessageRequestRequest {
    /**
     *
     */
    decision: ResolveMessageRequestRequestDecisionEnum;
}


/**
 * @export
 */
export const ResolveMessageRequestRequestDecisionEnum = {
    Accept: 'accept',
    Decline: 'decline',
} as const;
export type ResolveMessageRequestRequestDecisionEnum = typeof ResolveMessageRequestRequestDecisionEnum[keyof typeof ResolveMessageRequestRequestDecisionEnum];


/**
 * Check if a given object implements the ResolveMessageRequestRequest interface.
 */
export function instanceOfResolveMessageRequestRequest(value: object): value is ResolveMessageRequestRequest {
    if (!('decision' in value) || value['decision'] === undefined) return false;
    return true;
}

export function ResolveMessageRequestRequestFromJSON(json: any): ResolveMessageRequestRequest {
    return ResolveMessageRequestRequestFromJSONTyped(json, false);
}

export function ResolveMessageRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolveMessageRequestRequest {
    if (json == null) {
        return json;
    }
    return {

        'decision': json['decision'],
    };
}

export function ResolveMessageRequestRequestToJSON(json: any): ResolveMessageRequestRequest {
    return ResolveMessageRequestRequestToJSONTyped(json, false);
}

export function ResolveMessageRequestRequestToJSONTyped(value?: ResolveMessageRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'decision': value['decision'],
    };
}
