/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The complete archive response for a private account when the caller is neither its owner nor an active friend.
 * @export
 * @interface RestrictedProfilePosts
 */
export interface RestrictedProfilePosts {
    /**
     *
     */
    kind: RestrictedProfilePostsKindEnum;
    /**
     *
     */
    username: string;
}


/**
 * @export
 */
export const RestrictedProfilePostsKindEnum = {
    Restricted: 'restricted',
} as const;
export type RestrictedProfilePostsKindEnum = typeof RestrictedProfilePostsKindEnum[keyof typeof RestrictedProfilePostsKindEnum];


/**
 * Check if a given object implements the RestrictedProfilePosts interface.
 */
export function instanceOfRestrictedProfilePosts(value: object): value is RestrictedProfilePosts {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (value['kind'] !== 'restricted') return false;

    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function RestrictedProfilePostsFromJSON(json: any): RestrictedProfilePosts {
    return RestrictedProfilePostsFromJSONTyped(json, false);
}

export function RestrictedProfilePostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestrictedProfilePosts {
    if (json == null) {
        return json;
    }
    return {

        'kind': json['kind'],
        'username': json['username'],
    };
}

export function RestrictedProfilePostsToJSON(json: any): RestrictedProfilePosts {
    return RestrictedProfilePostsToJSONTyped(json, false);
}

export function RestrictedProfilePostsToJSONTyped(value?: RestrictedProfilePosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kind': value['kind'],
        'username': value['username'],
    };
}
