/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     *
     */
    clientMessageId: string;
    /**
     * 1 through 4,000 Unicode code points. The 8,000 code-unit cap preserves valid astral Unicode text.
     */
    text: string;
    /**
     *
     */
    replyToMessageId?: string;
}

/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): value is SendMessageRequest {
    if (!('clientMessageId' in value) || value['clientMessageId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if (json == null) {
        return json;
    }
    return {

        'clientMessageId': json['clientMessageId'],
        'text': json['text'],
        'replyToMessageId': json['replyToMessageId'] == null ? undefined : json['replyToMessageId'],
    };
}

export function SendMessageRequestToJSON(json: any): SendMessageRequest {
    return SendMessageRequestToJSONTyped(json, false);
}

export function SendMessageRequestToJSONTyped(value?: SendMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'clientMessageId': value['clientMessageId'],
        'text': value['text'],
        'replyToMessageId': value['replyToMessageId'],
    };
}
