/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SendRelationshipRequest
 */
export interface SendRelationshipRequest {
    /**
     *
     */
    recipientId: string;
}

/**
 * Check if a given object implements the SendRelationshipRequest interface.
 */
export function instanceOfSendRelationshipRequest(value: object): value is SendRelationshipRequest {
    if (!('recipientId' in value) || value['recipientId'] === undefined) return false;
    return true;
}

export function SendRelationshipRequestFromJSON(json: any): SendRelationshipRequest {
    return SendRelationshipRequestFromJSONTyped(json, false);
}

export function SendRelationshipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRelationshipRequest {
    if (json == null) {
        return json;
    }
    return {

        'recipientId': json['recipientId'],
    };
}

export function SendRelationshipRequestToJSON(json: any): SendRelationshipRequest {
    return SendRelationshipRequestToJSONTyped(json, false);
}

export function SendRelationshipRequestToJSONTyped(value?: SendRelationshipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'recipientId': value['recipientId'],
    };
}
