/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SetAvatarRequest
 */
export interface SetAvatarRequest {
    /**
     * A validated upload from `POST /api/v1/media-reservations` of a JPEG, PNG, or WebP image.
     */
    reservationId: string;
}

/**
 * Check if a given object implements the SetAvatarRequest interface.
 */
export function instanceOfSetAvatarRequest(value: object): value is SetAvatarRequest {
    if (!('reservationId' in value) || value['reservationId'] === undefined) return false;
    return true;
}

export function SetAvatarRequestFromJSON(json: any): SetAvatarRequest {
    return SetAvatarRequestFromJSONTyped(json, false);
}

export function SetAvatarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetAvatarRequest {
    if (json == null) {
        return json;
    }
    return {

        'reservationId': json['reservationId'],
    };
}

export function SetAvatarRequestToJSON(json: any): SetAvatarRequest {
    return SetAvatarRequestToJSONTyped(json, false);
}

export function SetAvatarRequestToJSONTyped(value?: SetAvatarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reservationId': value['reservationId'],
    };
}
