/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SetMessageReactionRequest
 */
export interface SetMessageReactionRequest {
    /**
     *
     */
    reaction: SetMessageReactionRequestReactionEnum;
}


/**
 * @export
 */
export const SetMessageReactionRequestReactionEnum = {
    Like: 'like',
    Love: 'love',
    Laugh: 'laugh',
    Surprised: 'surprised',
    Sad: 'sad',
    Thanks: 'thanks',
} as const;
export type SetMessageReactionRequestReactionEnum = typeof SetMessageReactionRequestReactionEnum[keyof typeof SetMessageReactionRequestReactionEnum];


/**
 * Check if a given object implements the SetMessageReactionRequest interface.
 */
export function instanceOfSetMessageReactionRequest(value: object): value is SetMessageReactionRequest {
    if (!('reaction' in value) || value['reaction'] === undefined) return false;
    return true;
}

export function SetMessageReactionRequestFromJSON(json: any): SetMessageReactionRequest {
    return SetMessageReactionRequestFromJSONTyped(json, false);
}

export function SetMessageReactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetMessageReactionRequest {
    if (json == null) {
        return json;
    }
    return {

        'reaction': json['reaction'],
    };
}

export function SetMessageReactionRequestToJSON(json: any): SetMessageReactionRequest {
    return SetMessageReactionRequestToJSONTyped(json, false);
}

export function SetMessageReactionRequestToJSONTyped(value?: SetMessageReactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reaction': value['reaction'],
    };
}
