/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface TestResponse
 */
export interface TestResponse {
    /**
     *
     */
    message: TestResponseMessageEnum;
    /**
     *
     */
    timestamp: Date;
    /**
     *
     */
    aucklandDate: string;
    /**
     *
     */
    requestedLimit: number;
}


/**
 * @export
 */
export const TestResponseMessageEnum = {
    DayliApiContractsAreAvailable: 'Dayli API contracts are available.',
} as const;
export type TestResponseMessageEnum = typeof TestResponseMessageEnum[keyof typeof TestResponseMessageEnum];


/**
 * Check if a given object implements the TestResponse interface.
 */
export function instanceOfTestResponse(value: object): value is TestResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (value['message'] !== 'Dayli API contracts are available.') return false;

    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('aucklandDate' in value) || value['aucklandDate'] === undefined) return false;
    if (!('requestedLimit' in value) || value['requestedLimit'] === undefined) return false;
    return true;
}

export function TestResponseFromJSON(json: any): TestResponse {
    return TestResponseFromJSONTyped(json, false);
}

export function TestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResponse {
    if (json == null) {
        return json;
    }
    return {

        'message': json['message'],
        'timestamp': (json['timestamp'] == null ? json['timestamp'] : parseDateTime(json['timestamp'])),
        'aucklandDate': json['aucklandDate'],
        'requestedLimit': json['requestedLimit'],
    };
}

export function TestResponseToJSON(json: any): TestResponse {
    return TestResponseToJSONTyped(json, false);
}

export function TestResponseToJSONTyped(value?: TestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'message': value['message'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : serializeDateTime(value['timestamp']),
        'aucklandDate': value['aucklandDate'],
        'requestedLimit': value['requestedLimit'],
    };
}
