/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileVisibility } from './ProfileVisibility';
import {
    ProfileVisibilityFromJSON,
    ProfileVisibilityFromJSONTyped,
    ProfileVisibilityToJSON,
    ProfileVisibilityToJSONTyped,
} from './ProfileVisibility';

/**
 *
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     *
     */
    bio?: string;
    /**
     * The name shown instead of the username. Null or blank shows the username.
     */
    publicName?: string;
    /**
     *
     */
    profileVisibility?: ProfileVisibility;
}



/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
    return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if (json == null) {
        return json;
    }
    return {

        'bio': json['bio'] == null ? undefined : json['bio'],
        'publicName': json['publicName'] == null ? undefined : json['publicName'],
        'profileVisibility': json['profileVisibility'] == null ? undefined : ProfileVisibilityFromJSON(json['profileVisibility']),
    };
}

export function UpdateProfileRequestToJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestToJSONTyped(json, false);
}

export function UpdateProfileRequestToJSONTyped(value?: UpdateProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'bio': value['bio'],
        'publicName': value['publicName'],
        'profileVisibility': ProfileVisibilityToJSON(value['profileVisibility']),
    };
}
