/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdatePostCommentRequest
 */
export interface UpdatePostCommentRequest {
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the UpdatePostCommentRequest interface.
 */
export function instanceOfUpdatePostCommentRequest(value: object): value is UpdatePostCommentRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function UpdatePostCommentRequestFromJSON(json: any): UpdatePostCommentRequest {
    return UpdatePostCommentRequestFromJSONTyped(json, false);
}

export function UpdatePostCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePostCommentRequest {
    if (json == null) {
        return json;
    }
    return {

        'text': json['text'],
    };
}

export function UpdatePostCommentRequestToJSON(json: any): UpdatePostCommentRequest {
    return UpdatePostCommentRequestToJSONTyped(json, false);
}

export function UpdatePostCommentRequestToJSONTyped(value?: UpdatePostCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'text': value['text'],
    };
}
