/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAudience } from './PostAudience';
import {
    PostAudienceFromJSON,
    PostAudienceFromJSONTyped,
    PostAudienceToJSON,
    PostAudienceToJSONTyped,
} from './PostAudience';

/**
 * Fields left out stay unchanged. The prompt, day, media and tomorrow note cannot be edited.
 * @export
 * @interface UpdatePostRequest
 */
export interface UpdatePostRequest {
    /**
     * The `revisionCount` of the post the author last read. If another edit has been saved since, the request is a 409.
     */
    expectedRevisionCount: number;
    /**
     *
     */
    reflectiveAnswer?: string;
    /**
     * Null removes the caption.
     */
    caption?: string | null;
    /**
     *
     */
    rating?: number;
    /**
     *
     */
    audience?: PostAudience;
}



/**
 * Check if a given object implements the UpdatePostRequest interface.
 */
export function instanceOfUpdatePostRequest(value: object): value is UpdatePostRequest {
    if (!('expectedRevisionCount' in value) || value['expectedRevisionCount'] === undefined) return false;
    return true;
}

export function UpdatePostRequestFromJSON(json: any): UpdatePostRequest {
    return UpdatePostRequestFromJSONTyped(json, false);
}

export function UpdatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePostRequest {
    if (json == null) {
        return json;
    }
    return {

        'expectedRevisionCount': json['expectedRevisionCount'],
        'reflectiveAnswer': json['reflectiveAnswer'] == null ? undefined : json['reflectiveAnswer'],
        'caption': json['caption'] === undefined ? undefined : json['caption'] === null ? null : json['caption'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'audience': json['audience'] == null ? undefined : PostAudienceFromJSON(json['audience']),
    };
}

export function UpdatePostRequestToJSON(json: any): UpdatePostRequest {
    return UpdatePostRequestToJSONTyped(json, false);
}

export function UpdatePostRequestToJSONTyped(value?: UpdatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedRevisionCount': value['expectedRevisionCount'],
        'reflectiveAnswer': value['reflectiveAnswer'],
        'caption': value['caption'],
        'rating': value['rating'],
        'audience': PostAudienceToJSON(value['audience']),
    };
}
