/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateFutureSelfNoteRequest
 */
export interface UpdateFutureSelfNoteRequest {
    /**
     * The note text, trimmed, 1 to 1,000 characters. It is never readable before its delivery date.
     */
    body?: string;
    /**
     * The Auckland calendar date the note is delivered on. When creating or rescheduling it must be from tomorrow (Auckland, decided by the server) up to 10 years after today.
     */
    deliverOn?: string;
}

/**
 * Check if a given object implements the UpdateFutureSelfNoteRequest interface.
 */
export function instanceOfUpdateFutureSelfNoteRequest(value: object): value is UpdateFutureSelfNoteRequest {
    return true;
}

export function UpdateFutureSelfNoteRequestFromJSON(json: any): UpdateFutureSelfNoteRequest {
    return UpdateFutureSelfNoteRequestFromJSONTyped(json, false);
}

export function UpdateFutureSelfNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFutureSelfNoteRequest {
    if (json == null) {
        return json;
    }
    return {

        'body': json['body'] == null ? undefined : json['body'],
        'deliverOn': json['deliverOn'] == null ? undefined : json['deliverOn'],
    };
}

export function UpdateFutureSelfNoteRequestToJSON(json: any): UpdateFutureSelfNoteRequest {
    return UpdateFutureSelfNoteRequestToJSONTyped(json, false);
}

export function UpdateFutureSelfNoteRequestToJSONTyped(value?: UpdateFutureSelfNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'body': value['body'],
        'deliverOn': value['deliverOn'],
    };
}
