/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UsernameSetupRequest
 */
export interface UsernameSetupRequest {
    /**
     *
     */
    username: string;
    /**
     *
     */
    publicName?: string;
}

/**
 * Check if a given object implements the UsernameSetupRequest interface.
 */
export function instanceOfUsernameSetupRequest(value: object): value is UsernameSetupRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UsernameSetupRequestFromJSON(json: any): UsernameSetupRequest {
    return UsernameSetupRequestFromJSONTyped(json, false);
}

export function UsernameSetupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsernameSetupRequest {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'],
        'publicName': json['publicName'] == null ? undefined : json['publicName'],
    };
}

export function UsernameSetupRequestToJSON(json: any): UsernameSetupRequest {
    return UsernameSetupRequestToJSONTyped(json, false);
}

export function UsernameSetupRequestToJSONTyped(value?: UsernameSetupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'username': value['username'],
        'publicName': value['publicName'],
    };
}
