/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccountGoogleProofBegin200Response,
    AccountGoogleProofBegin200ResponseFromJSON,
    AccountGoogleProofBegin200ResponseToJSON,
} from '../models/AccountGoogleProofBegin200Response';
import {
    type AccountGoogleProofBeginRequest,
    AccountGoogleProofBeginRequestFromJSON,
    AccountGoogleProofBeginRequestToJSON,
} from '../models/AccountGoogleProofBeginRequest';
import {
    type AccountGoogleProofComplete200Response,
    AccountGoogleProofComplete200ResponseFromJSON,
    AccountGoogleProofComplete200ResponseToJSON,
} from '../models/AccountGoogleProofComplete200Response';
import {
    type AccountGoogleProofCompleteRequest,
    AccountGoogleProofCompleteRequestFromJSON,
    AccountGoogleProofCompleteRequestToJSON,
} from '../models/AccountGoogleProofCompleteRequest';

export interface AccountGoogleProofBeginOperationRequest {
    /**
     *
     */
    accountGoogleProofBeginRequest?: AccountGoogleProofBeginRequest;
}

export interface AccountGoogleProofCallbackRequest {
    /**
     *
     */
    state: string;
    /**
     *
     */
    code?: string;
}

export interface AccountGoogleProofCompleteOperationRequest {
    /**
     *
     */
    accountGoogleProofCompleteRequest?: AccountGoogleProofCompleteRequest;
}

/**
 *
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     * Creates request options for accountGoogleProofBegin without sending the request
     */
    async accountGoogleProofBeginRequestOpts(requestParameters: AccountGoogleProofBeginOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/account/reauthenticate/google/begin`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountGoogleProofBeginRequestToJSON(requestParameters['accountGoogleProofBeginRequest']),
        };
    }

    /**
     */
    async accountGoogleProofBeginRaw(requestParameters: AccountGoogleProofBeginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountGoogleProofBegin200Response>> {
        const requestOptions = await this.accountGoogleProofBeginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountGoogleProofBegin200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async accountGoogleProofBegin(requestParameters: AccountGoogleProofBeginOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountGoogleProofBegin200Response> {
        const response = await this.accountGoogleProofBeginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for accountGoogleProofCallback without sending the request
     */
    async accountGoogleProofCallbackRequestOpts(requestParameters: AccountGoogleProofCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling accountGoogleProofCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/account/reauthenticate/google/callback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async accountGoogleProofCallbackRaw(requestParameters: AccountGoogleProofCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.accountGoogleProofCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async accountGoogleProofCallback(requestParameters: AccountGoogleProofCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountGoogleProofCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for accountGoogleProofComplete without sending the request
     */
    async accountGoogleProofCompleteRequestOpts(requestParameters: AccountGoogleProofCompleteOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/account/reauthenticate/google/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountGoogleProofCompleteRequestToJSON(requestParameters['accountGoogleProofCompleteRequest']),
        };
    }

    /**
     */
    async accountGoogleProofCompleteRaw(requestParameters: AccountGoogleProofCompleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountGoogleProofComplete200Response>> {
        const requestOptions = await this.accountGoogleProofCompleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountGoogleProofComplete200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async accountGoogleProofComplete(requestParameters: AccountGoogleProofCompleteOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountGoogleProofComplete200Response> {
        const response = await this.accountGoogleProofCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
