/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type LegalAcceptCurrentTerms200Response,
    LegalAcceptCurrentTerms200ResponseFromJSON,
    LegalAcceptCurrentTerms200ResponseToJSON,
} from '../models/LegalAcceptCurrentTerms200Response';
import {
    type LegalAcceptCurrentTermsRequest,
    LegalAcceptCurrentTermsRequestFromJSON,
    LegalAcceptCurrentTermsRequestToJSON,
} from '../models/LegalAcceptCurrentTermsRequest';
import {
    type LegalGetCurrentTerms200Response,
    LegalGetCurrentTerms200ResponseFromJSON,
    LegalGetCurrentTerms200ResponseToJSON,
} from '../models/LegalGetCurrentTerms200Response';
import {
    type LegalGetCurrentTermsContent200Response,
    LegalGetCurrentTermsContent200ResponseFromJSON,
    LegalGetCurrentTermsContent200ResponseToJSON,
} from '../models/LegalGetCurrentTermsContent200Response';
import {
    type LegalGetTermsNotice200Response,
    LegalGetTermsNotice200ResponseFromJSON,
    LegalGetTermsNotice200ResponseToJSON,
} from '../models/LegalGetTermsNotice200Response';
import {
    type LegalIssueRegistrationIntent201Response,
    LegalIssueRegistrationIntent201ResponseFromJSON,
    LegalIssueRegistrationIntent201ResponseToJSON,
} from '../models/LegalIssueRegistrationIntent201Response';
import {
    type LegalIssueRegistrationIntentRequest,
    LegalIssueRegistrationIntentRequestFromJSON,
    LegalIssueRegistrationIntentRequestToJSON,
} from '../models/LegalIssueRegistrationIntentRequest';

export interface LegalAcceptCurrentTermsOperationRequest {
    /**
     *
     */
    legalAcceptCurrentTermsRequest?: LegalAcceptCurrentTermsRequest;
}

export interface LegalIssueRegistrationIntentOperationRequest {
    /**
     *
     */
    legalIssueRegistrationIntentRequest?: LegalIssueRegistrationIntentRequest;
}

/**
 *
 */
export class LegalApi extends runtime.BaseAPI {

    /**
     * Creates request options for legalAcceptCurrentTerms without sending the request
     */
    async legalAcceptCurrentTermsRequestOpts(requestParameters: LegalAcceptCurrentTermsOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/account/legal/acceptance`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LegalAcceptCurrentTermsRequestToJSON(requestParameters['legalAcceptCurrentTermsRequest']),
        };
    }

    /**
     */
    async legalAcceptCurrentTermsRaw(requestParameters: LegalAcceptCurrentTermsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalAcceptCurrentTerms200Response>> {
        const requestOptions = await this.legalAcceptCurrentTermsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalAcceptCurrentTerms200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async legalAcceptCurrentTerms(requestParameters: LegalAcceptCurrentTermsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalAcceptCurrentTerms200Response> {
        const response = await this.legalAcceptCurrentTermsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for legalGetCurrentTerms without sending the request
     */
    async legalGetCurrentTermsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/legal/terms/current`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async legalGetCurrentTermsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalGetCurrentTerms200Response>> {
        const requestOptions = await this.legalGetCurrentTermsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalGetCurrentTerms200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async legalGetCurrentTerms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalGetCurrentTerms200Response> {
        const response = await this.legalGetCurrentTermsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for legalGetCurrentTermsContent without sending the request
     */
    async legalGetCurrentTermsContentRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/legal/terms/current/content`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async legalGetCurrentTermsContentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalGetCurrentTermsContent200Response>> {
        const requestOptions = await this.legalGetCurrentTermsContentRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalGetCurrentTermsContent200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async legalGetCurrentTermsContent(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalGetCurrentTermsContent200Response> {
        const response = await this.legalGetCurrentTermsContentRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for legalGetTermsNotice without sending the request
     */
    async legalGetTermsNoticeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/legal/terms/notice`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async legalGetTermsNoticeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalGetTermsNotice200Response>> {
        const requestOptions = await this.legalGetTermsNoticeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalGetTermsNotice200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async legalGetTermsNotice(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalGetTermsNotice200Response> {
        const response = await this.legalGetTermsNoticeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for legalIssueRegistrationIntent without sending the request
     */
    async legalIssueRegistrationIntentRequestOpts(requestParameters: LegalIssueRegistrationIntentOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/legal/registration-intents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LegalIssueRegistrationIntentRequestToJSON(requestParameters['legalIssueRegistrationIntentRequest']),
        };
    }

    /**
     */
    async legalIssueRegistrationIntentRaw(requestParameters: LegalIssueRegistrationIntentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalIssueRegistrationIntent201Response>> {
        const requestOptions = await this.legalIssueRegistrationIntentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalIssueRegistrationIntent201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async legalIssueRegistrationIntent(requestParameters: LegalIssueRegistrationIntentOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalIssueRegistrationIntent201Response> {
        const response = await this.legalIssueRegistrationIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
