/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CurrentLegalRegistrationTerms,
    CurrentLegalRegistrationTermsFromJSON,
    CurrentLegalRegistrationTermsToJSON,
} from '../models/CurrentLegalRegistrationTerms';
import {
    type LegalAcceptanceRequest,
    LegalAcceptanceRequestFromJSON,
    LegalAcceptanceRequestToJSON,
} from '../models/LegalAcceptanceRequest';
import {
    type LegalAcceptanceResponse,
    LegalAcceptanceResponseFromJSON,
    LegalAcceptanceResponseToJSON,
} from '../models/LegalAcceptanceResponse';
import {
    type RegistrationIntentRequest,
    RegistrationIntentRequestFromJSON,
    RegistrationIntentRequestToJSON,
} from '../models/RegistrationIntentRequest';
import {
    type RegistrationIntentResponse,
    RegistrationIntentResponseFromJSON,
    RegistrationIntentResponseToJSON,
} from '../models/RegistrationIntentResponse';

export interface LegalIssueRegistrationIntentRequest {
    /**
     *
     */
    registrationIntentRequest: RegistrationIntentRequest;
}

export interface LegalRecordAcceptanceRequest {
    /**
     *
     */
    legalAcceptanceRequest: LegalAcceptanceRequest;
}

/**
 *
 */
export class LegalApi extends runtime.BaseAPI {

    /**
     * Creates request options for legalCurrentRegistrationTerms without sending the request
     */
    async legalCurrentRegistrationTermsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/legal/current`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read current published signup Terms metadata
     */
    async legalCurrentRegistrationTermsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentLegalRegistrationTerms>> {
        const requestOptions = await this.legalCurrentRegistrationTermsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentLegalRegistrationTermsFromJSON(jsonValue));
    }

    /**
     * Read current published signup Terms metadata
     */
    async legalCurrentRegistrationTerms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentLegalRegistrationTerms> {
        const response = await this.legalCurrentRegistrationTermsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for legalIssueRegistrationIntent without sending the request
     */
    async legalIssueRegistrationIntentRequestOpts(requestParameters: LegalIssueRegistrationIntentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registrationIntentRequest'] == null) {
            throw new runtime.RequiredError(
                'registrationIntentRequest',
                'Required parameter "registrationIntentRequest" was null or undefined when calling legalIssueRegistrationIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/legal/registration-intent`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationIntentRequestToJSON(requestParameters['registrationIntentRequest']),
        };
    }

    /**
     * Requires current approved documents and one affirmative Terms, Privacy notice, and 16+ action before account creation.
     * Start one explicit email or Google registration action
     */
    async legalIssueRegistrationIntentRaw(requestParameters: LegalIssueRegistrationIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegistrationIntentResponse>> {
        const requestOptions = await this.legalIssueRegistrationIntentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationIntentResponseFromJSON(jsonValue));
    }

    /**
     * Requires current approved documents and one affirmative Terms, Privacy notice, and 16+ action before account creation.
     * Start one explicit email or Google registration action
     */
    async legalIssueRegistrationIntent(requestParameters: LegalIssueRegistrationIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegistrationIntentResponse> {
        const response = await this.legalIssueRegistrationIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for legalRecordAcceptance without sending the request
     */
    async legalRecordAcceptanceRequestOpts(requestParameters: LegalRecordAcceptanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['legalAcceptanceRequest'] == null) {
            throw new runtime.RequiredError(
                'legalAcceptanceRequest',
                'Required parameter "legalAcceptanceRequest" was null or undefined when calling legalRecordAcceptance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/legal/acceptance`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LegalAcceptanceRequestToJSON(requestParameters['legalAcceptanceRequest']),
        };
    }

    /**
     * Available only for an effective Terms version. The Privacy Policy is a notice, not consent. No draft document can be accepted.
     * Record an explicit current Terms and 16+ action
     */
    async legalRecordAcceptanceRaw(requestParameters: LegalRecordAcceptanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegalAcceptanceResponse>> {
        const requestOptions = await this.legalRecordAcceptanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegalAcceptanceResponseFromJSON(jsonValue));
    }

    /**
     * Available only for an effective Terms version. The Privacy Policy is a notice, not consent. No draft document can be accepted.
     * Record an explicit current Terms and 16+ action
     */
    async legalRecordAcceptance(requestParameters: LegalRecordAcceptanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegalAcceptanceResponse> {
        const response = await this.legalRecordAcceptanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
