/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateMediaReservationRequest,
    CreateMediaReservationRequestFromJSON,
    CreateMediaReservationRequestToJSON,
} from '../models/CreateMediaReservationRequest';
import {
    type CreateMediaReservationResponse,
    CreateMediaReservationResponseFromJSON,
    CreateMediaReservationResponseToJSON,
} from '../models/CreateMediaReservationResponse';
import {
    type MediaReservation,
    MediaReservationFromJSON,
    MediaReservationToJSON,
} from '../models/MediaReservation';

export interface MediaReservationsCompleteRequest {
    /**
     *
     */
    id: string;
}

export interface MediaReservationsCreateRequest {
    /**
     *
     */
    createMediaReservationRequest?: CreateMediaReservationRequest;
}

export interface MediaReservationsGetRequest {
    /**
     *
     */
    id: string;
}

/**
 *
 */
export class MediaApi extends runtime.BaseAPI {

    /**
     * Creates request options for mediaReservationsComplete without sending the request
     */
    async mediaReservationsCompleteRequestOpts(requestParameters: MediaReservationsCompleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaReservationsComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/media-reservations/{id}/complete`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verify a caller\'s uploaded object and record a validated/failed outcome
     */
    async mediaReservationsCompleteRaw(requestParameters: MediaReservationsCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MediaReservation>> {
        const requestOptions = await this.mediaReservationsCompleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaReservationFromJSON(jsonValue));
    }

    /**
     * Verify a caller\'s uploaded object and record a validated/failed outcome
     */
    async mediaReservationsComplete(requestParameters: MediaReservationsCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MediaReservation> {
        const response = await this.mediaReservationsCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mediaReservationsCreate without sending the request
     */
    async mediaReservationsCreateRequestOpts(requestParameters: MediaReservationsCreateRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/media-reservations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMediaReservationRequestToJSON(requestParameters['createMediaReservationRequest']),
        };
    }

    /**
     * Reserve an opaque, owned R2 object path for a direct upload
     */
    async mediaReservationsCreateRaw(requestParameters: MediaReservationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateMediaReservationResponse>> {
        const requestOptions = await this.mediaReservationsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateMediaReservationResponseFromJSON(jsonValue));
    }

    /**
     * Reserve an opaque, owned R2 object path for a direct upload
     */
    async mediaReservationsCreate(requestParameters: MediaReservationsCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateMediaReservationResponse> {
        const response = await this.mediaReservationsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mediaReservationsGet without sending the request
     */
    async mediaReservationsGetRequestOpts(requestParameters: MediaReservationsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaReservationsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/media-reservations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read the caller\'s own media reservation
     */
    async mediaReservationsGetRaw(requestParameters: MediaReservationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MediaReservation>> {
        const requestOptions = await this.mediaReservationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaReservationFromJSON(jsonValue));
    }

    /**
     * Read the caller\'s own media reservation
     */
    async mediaReservationsGet(requestParameters: MediaReservationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MediaReservation> {
        const response = await this.mediaReservationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
