/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetNotificationPreference200Response,
    GetNotificationPreference200ResponseFromJSON,
    GetNotificationPreference200ResponseToJSON,
} from '../models/GetNotificationPreference200Response';
import {
    type UpdateNotificationPreferenceRequest,
    UpdateNotificationPreferenceRequestFromJSON,
    UpdateNotificationPreferenceRequestToJSON,
} from '../models/UpdateNotificationPreferenceRequest';

export interface UpdateNotificationPreferenceOperationRequest {
    /**
     *
     */
    updateNotificationPreferenceRequest: UpdateNotificationPreferenceRequest;
}

/**
 *
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getNotificationPreference without sending the request
     */
    async getNotificationPreferenceRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/notifications/preference`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationPreferenceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNotificationPreference200Response>> {
        const requestOptions = await this.getNotificationPreferenceRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNotificationPreference200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getNotificationPreference(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNotificationPreference200Response> {
        const response = await this.getNotificationPreferenceRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateNotificationPreference without sending the request
     */
    async updateNotificationPreferenceRequestOpts(requestParameters: UpdateNotificationPreferenceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateNotificationPreferenceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateNotificationPreferenceRequest',
                'Required parameter "updateNotificationPreferenceRequest" was null or undefined when calling updateNotificationPreference().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/notifications/preference`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateNotificationPreferenceRequestToJSON(requestParameters['updateNotificationPreferenceRequest']),
        };
    }

    /**
     */
    async updateNotificationPreferenceRaw(requestParameters: UpdateNotificationPreferenceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNotificationPreference200Response>> {
        const requestOptions = await this.updateNotificationPreferenceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNotificationPreference200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateNotificationPreference(requestParameters: UpdateNotificationPreferenceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNotificationPreference200Response> {
        const response = await this.updateNotificationPreferenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
