/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateDailyPostRequest,
    CreateDailyPostRequestFromJSON,
    CreateDailyPostRequestToJSON,
} from '../models/CreateDailyPostRequest';
import {
    type DailyPost,
    DailyPostFromJSON,
    DailyPostToJSON,
} from '../models/DailyPost';
import {
    type FeedPage,
    FeedPageFromJSON,
    FeedPageToJSON,
} from '../models/FeedPage';
import {
    type PostDetail,
    PostDetailFromJSON,
    PostDetailToJSON,
} from '../models/PostDetail';
import {
    type PostMedia,
    PostMediaFromJSON,
    PostMediaToJSON,
} from '../models/PostMedia';
import {
    type PostVoiceMemo,
    PostVoiceMemoFromJSON,
    PostVoiceMemoToJSON,
} from '../models/PostVoiceMemo';
import {
    type PostsListTrash200Response,
    PostsListTrash200ResponseFromJSON,
    PostsListTrash200ResponseToJSON,
} from '../models/PostsListTrash200Response';
import {
    type PostsRestore200Response,
    PostsRestore200ResponseFromJSON,
    PostsRestore200ResponseToJSON,
} from '../models/PostsRestore200Response';
import {
    type ProfilePostsPage,
    ProfilePostsPageFromJSON,
    ProfilePostsPageToJSON,
} from '../models/ProfilePostsPage';
import {
    type TrashedPostStatus,
    TrashedPostStatusFromJSON,
    TrashedPostStatusToJSON,
} from '../models/TrashedPostStatus';

export interface PostsCreateRequest {
    /**
     * A client-generated key reused for every retry of this submission, such as a UUID stored with the draft.
     */
    idempotencyKey: string;
    /**
     *
     */
    createDailyPostRequest: CreateDailyPostRequest;
}

export interface PostsGetRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsGetMediaRequest {
    /**
     *
     */
    postId: string;
    /**
     *
     */
    mediaId: string;
}

export interface PostsGetVoiceMemoRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsListFeedRequest {
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
}

export interface PostsListProfilePostsRequest {
    /**
     *
     */
    username: string;
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
}

export interface PostsRestoreRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsTrashRequest {
    /**
     *
     */
    postId: string;
}

/**
 *
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Creates request options for postsCreate without sending the request
     */
    async postsCreateRequestOpts(requestParameters: PostsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling postsCreate().'
            );
        }

        if (requestParameters['createDailyPostRequest'] == null) {
            throw new runtime.RequiredError(
                'createDailyPostRequest',
                'Required parameter "createDailyPostRequest" was null or undefined when calling postsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDailyPostRequestToJSON(requestParameters['createDailyPostRequest']),
        };
    }

    /**
     * Creates the authenticated user\'s one post for the current Auckland day. Retry a lost response with the same `Idempotency-Key`: an identical retry returns the original post with `Idempotent-Replayed: true`, even after the deadline, while a changed request conflicts.
     * Submit today\'s daily post
     */
    async postsCreateRaw(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyPost>> {
        const requestOptions = await this.postsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DailyPostFromJSON(jsonValue));
    }

    /**
     * Creates the authenticated user\'s one post for the current Auckland day. Retry a lost response with the same `Idempotency-Key`: an identical retry returns the original post with `Idempotent-Replayed: true`, even after the deadline, while a changed request conflicts.
     * Submit today\'s daily post
     */
    async postsCreate(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyPost> {
        const response = await this.postsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGet without sending the request
     */
    async postsGetRequestOpts(requestParameters: PostsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a post the caller may read. Authors can read their own solo and unreleased posts. Anyone else needs a released `friends` post by an active friend with no block in either direction. A missing post and a post the caller may not read both return 404.
     * Read one post
     */
    async postsGetRaw(requestParameters: PostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetail>> {
        const requestOptions = await this.postsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailFromJSON(jsonValue));
    }

    /**
     * Returns a post the caller may read. Authors can read their own solo and unreleased posts. Anyone else needs a released `friends` post by an active friend with no block in either direction. A missing post and a post the caller may not read both return 404.
     * Read one post
     */
    async postsGet(requestParameters: PostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetail> {
        const response = await this.postsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetMedia without sending the request
     */
    async postsGetMediaRequestOpts(requestParameters: PostsGetMediaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGetMedia().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling postsGetMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/media/{mediaId}`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the media must still be attached to it.
     * Get a fresh download URL for one attached photo or video
     */
    async postsGetMediaRaw(requestParameters: PostsGetMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostMedia>> {
        const requestOptions = await this.postsGetMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostMediaFromJSON(jsonValue));
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the media must still be attached to it.
     * Get a fresh download URL for one attached photo or video
     */
    async postsGetMedia(requestParameters: PostsGetMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostMedia> {
        const response = await this.postsGetMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetVoiceMemo without sending the request
     */
    async postsGetVoiceMemoRequestOpts(requestParameters: PostsGetVoiceMemoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGetVoiceMemo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/voice-memo`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the voice memo must still be attached to it.
     * Get a fresh download URL for a post\'s voice memo
     */
    async postsGetVoiceMemoRaw(requestParameters: PostsGetVoiceMemoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostVoiceMemo>> {
        const requestOptions = await this.postsGetVoiceMemoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostVoiceMemoFromJSON(jsonValue));
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the voice memo must still be attached to it.
     * Get a fresh download URL for a post\'s voice memo
     */
    async postsGetVoiceMemo(requestParameters: PostsGetVoiceMemoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostVoiceMemo> {
        const response = await this.postsGetVoiceMemoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListFeed without sending the request
     */
    async postsListFeedRequestOpts(requestParameters: PostsListFeedRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/feed`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns yesterday\'s `friends` posts by the authenticated user\'s active friends: the Auckland day released at the most recent midnight. Earlier days are on each friend\'s profile. Solo posts, the caller\'s own posts, and posts by blocked or blocking users are never included. Access is re-checked on every page.
     * List yesterday\'s posts from friends
     */
    async postsListFeedRaw(requestParameters: PostsListFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedPage>> {
        const requestOptions = await this.postsListFeedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedPageFromJSON(jsonValue));
    }

    /**
     * Returns yesterday\'s `friends` posts by the authenticated user\'s active friends: the Auckland day released at the most recent midnight. Earlier days are on each friend\'s profile. Solo posts, the caller\'s own posts, and posts by blocked or blocking users are never included. Access is re-checked on every page.
     * List yesterday\'s posts from friends
     */
    async postsListFeed(requestParameters: PostsListFeedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedPage> {
        const response = await this.postsListFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListProfilePosts without sending the request
     */
    async postsListProfilePostsRequestOpts(requestParameters: PostsListProfilePostsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling postsListProfilePosts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profiles/{username}/posts`;
        urlPath = urlPath.replace('{username}', encodeURIComponent(String(requestParameters['username'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one person\'s posts, newest Auckland day first. On the caller\'s own profile this includes solo and unreleased posts. On anyone else\'s it includes only released `friends` posts, and only while the two are active friends; otherwise the page is empty. Access is re-checked on every page. Unknown, banned and blocked profiles all return 404.
     * List the posts on a profile
     */
    async postsListProfilePostsRaw(requestParameters: PostsListProfilePostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfilePostsPage>> {
        const requestOptions = await this.postsListProfilePostsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfilePostsPageFromJSON(jsonValue));
    }

    /**
     * Returns one person\'s posts, newest Auckland day first. On the caller\'s own profile this includes solo and unreleased posts. On anyone else\'s it includes only released `friends` posts, and only while the two are active friends; otherwise the page is empty. Access is re-checked on every page. Unknown, banned and blocked profiles all return 404.
     * List the posts on a profile
     */
    async postsListProfilePosts(requestParameters: PostsListProfilePostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfilePostsPage> {
        const response = await this.postsListProfilePostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListTrash without sending the request
     */
    async postsListTrashRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/trash`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the authenticated owner\'s trashed posts
     */
    async postsListTrashRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsListTrash200Response>> {
        const requestOptions = await this.postsListTrashRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsListTrash200ResponseFromJSON(jsonValue));
    }

    /**
     * List the authenticated owner\'s trashed posts
     */
    async postsListTrash(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsListTrash200Response> {
        const response = await this.postsListTrashRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsRestore without sending the request
     */
    async postsRestoreRequestOpts(requestParameters: PostsRestoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsRestore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/restore`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Restore an owned post from Trash
     */
    async postsRestoreRaw(requestParameters: PostsRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsRestore200Response>> {
        const requestOptions = await this.postsRestoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsRestore200ResponseFromJSON(jsonValue));
    }

    /**
     * Restore an owned post from Trash
     */
    async postsRestore(requestParameters: PostsRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsRestore200Response> {
        const response = await this.postsRestoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsTrash without sending the request
     */
    async postsTrashRequestOpts(requestParameters: PostsTrashRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsTrash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/trash`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Move an owned post to Trash
     */
    async postsTrashRaw(requestParameters: PostsTrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrashedPostStatus>> {
        const requestOptions = await this.postsTrashRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrashedPostStatusFromJSON(jsonValue));
    }

    /**
     * Move an owned post to Trash
     */
    async postsTrash(requestParameters: PostsTrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrashedPostStatus> {
        const response = await this.postsTrashRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
