/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateDailyPostRequest,
    CreateDailyPostRequestFromJSON,
    CreateDailyPostRequestToJSON,
} from '../models/CreateDailyPostRequest';
import {
    type DailyPost,
    DailyPostFromJSON,
    DailyPostToJSON,
} from '../models/DailyPost';

export interface PostsCreateRequest {
    /**
     * A client-generated key reused for every retry of this submission, such as a UUID stored with the draft.
     */
    idempotencyKey: string;
    /**
     *
     */
    createDailyPostRequest: CreateDailyPostRequest;
}

/**
 *
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Creates request options for postsCreate without sending the request
     */
    async postsCreateRequestOpts(requestParameters: PostsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling postsCreate().'
            );
        }

        if (requestParameters['createDailyPostRequest'] == null) {
            throw new runtime.RequiredError(
                'createDailyPostRequest',
                'Required parameter "createDailyPostRequest" was null or undefined when calling postsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDailyPostRequestToJSON(requestParameters['createDailyPostRequest']),
        };
    }

    /**
     * Creates the authenticated user\'s one post for the current Auckland day. Retry a lost response with the same `Idempotency-Key`: an identical retry returns the original post with `Idempotent-Replayed: true`, even after the deadline, while a changed request conflicts.
     * Submit today\'s daily post
     */
    async postsCreateRaw(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyPost>> {
        const requestOptions = await this.postsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DailyPostFromJSON(jsonValue));
    }

    /**
     * Creates the authenticated user\'s one post for the current Auckland day. Retry a lost response with the same `Idempotency-Key`: an identical retry returns the original post with `Idempotent-Replayed: true`, even after the deadline, while a changed request conflicts.
     * Submit today\'s daily post
     */
    async postsCreate(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyPost> {
        const response = await this.postsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
