/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateDailyPostRequest,
    CreateDailyPostRequestFromJSON,
    CreateDailyPostRequestToJSON,
} from '../models/CreateDailyPostRequest';
import {
    type DailyPost,
    DailyPostFromJSON,
    DailyPostToJSON,
} from '../models/DailyPost';
import {
    type FeedPage,
    FeedPageFromJSON,
    FeedPageToJSON,
} from '../models/FeedPage';
import {
    type MoodHistory,
    MoodHistoryFromJSON,
    MoodHistoryToJSON,
} from '../models/MoodHistory';
import {
    type OnThisDayMemories,
    OnThisDayMemoriesFromJSON,
    OnThisDayMemoriesToJSON,
} from '../models/OnThisDayMemories';
import {
    type PostDetail,
    PostDetailFromJSON,
    PostDetailToJSON,
} from '../models/PostDetail';
import {
    type PostMedia,
    PostMediaFromJSON,
    PostMediaToJSON,
} from '../models/PostMedia';
import {
    type PostRevisionsPage,
    PostRevisionsPageFromJSON,
    PostRevisionsPageToJSON,
} from '../models/PostRevisionsPage';
import {
    type PostVoiceMemo,
    PostVoiceMemoFromJSON,
    PostVoiceMemoToJSON,
} from '../models/PostVoiceMemo';
import {
    type PostsListTrash200Response,
    PostsListTrash200ResponseFromJSON,
    PostsListTrash200ResponseToJSON,
} from '../models/PostsListTrash200Response';
import {
    type PostsRestore200Response,
    PostsRestore200ResponseFromJSON,
    PostsRestore200ResponseToJSON,
} from '../models/PostsRestore200Response';
import {
    type ReadableProfilePosts,
    ReadableProfilePostsFromJSON,
    ReadableProfilePostsToJSON,
} from '../models/ReadableProfilePosts';
import {
    type TrashedPostStatus,
    TrashedPostStatusFromJSON,
    TrashedPostStatusToJSON,
} from '../models/TrashedPostStatus';
import {
    type UpdatePostRequest,
    UpdatePostRequestFromJSON,
    UpdatePostRequestToJSON,
} from '../models/UpdatePostRequest';

export interface PostsCreateRequest {
    /**
     * A client-generated key reused for every retry of this submission, such as a UUID stored with the draft.
     */
    idempotencyKey: string;
    /**
     *
     */
    createDailyPostRequest: CreateDailyPostRequest;
}

export interface PostsGetRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsGetMediaRequest {
    /**
     *
     */
    postId: string;
    /**
     *
     */
    mediaId: string;
}

export interface PostsGetMediaContentRequest {
    /**
     *
     */
    postId: string;
    /**
     *
     */
    mediaId: string;
}

export interface PostsGetProfileMoodRequest {
    /**
     *
     */
    username: string;
    /**
     * The last 30 days, 90 days, or 365 days, ending today in Auckland.
     */
    range?: PostsGetProfileMoodRangeEnum;
}

export interface PostsGetVoiceMemoRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsGetVoiceMemoContentRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsListFeedRequest {
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
}

export interface PostsListProfilePostsRequest {
    /**
     *
     */
    username: string;
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
}

export interface PostsListRevisionsRequest {
    /**
     *
     */
    postId: string;
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
}

export interface PostsRestoreRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsTrashRequest {
    /**
     *
     */
    postId: string;
}

export interface PostsUpdateRequest {
    /**
     *
     */
    postId: string;
    /**
     *
     */
    updatePostRequest: UpdatePostRequest;
}

/**
 *
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Creates request options for postsCreate without sending the request
     */
    async postsCreateRequestOpts(requestParameters: PostsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling postsCreate().'
            );
        }

        if (requestParameters['createDailyPostRequest'] == null) {
            throw new runtime.RequiredError(
                'createDailyPostRequest',
                'Required parameter "createDailyPostRequest" was null or undefined when calling postsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDailyPostRequestToJSON(requestParameters['createDailyPostRequest']),
        };
    }

    /**
     * Creates the authenticated user\'s one post for the current Auckland day. Retry a lost response with the same `Idempotency-Key`: an identical retry returns the original post with `Idempotent-Replayed: true`, even after the deadline, while a changed request conflicts.
     * Submit today\'s daily post
     */
    async postsCreateRaw(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyPost>> {
        const requestOptions = await this.postsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DailyPostFromJSON(jsonValue));
    }

    /**
     * Creates the authenticated user\'s one post for the current Auckland day. Retry a lost response with the same `Idempotency-Key`: an identical retry returns the original post with `Idempotent-Replayed: true`, even after the deadline, while a changed request conflicts.
     * Submit today\'s daily post
     */
    async postsCreate(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyPost> {
        const response = await this.postsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGet without sending the request
     */
    async postsGetRequestOpts(requestParameters: PostsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a post the caller may read. Authors can read their own solo and unreleased posts. Released `friends` posts are also readable by active friends and by anyone when the author has a public profile. A known signed-in block is denied before public-profile access. A missing post and a post the caller may not read both return 404.
     * Read one post
     */
    async postsGetRaw(requestParameters: PostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetail>> {
        const requestOptions = await this.postsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailFromJSON(jsonValue));
    }

    /**
     * Returns a post the caller may read. Authors can read their own solo and unreleased posts. Released `friends` posts are also readable by active friends and by anyone when the author has a public profile. A known signed-in block is denied before public-profile access. A missing post and a post the caller may not read both return 404.
     * Read one post
     */
    async postsGet(requestParameters: PostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetail> {
        const response = await this.postsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetMedia without sending the request
     */
    async postsGetMediaRequestOpts(requestParameters: PostsGetMediaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGetMedia().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling postsGetMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/media/{mediaId}`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the media must still be attached to it.
     * Get a fresh download URL for one attached photo or video
     */
    async postsGetMediaRaw(requestParameters: PostsGetMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostMedia>> {
        const requestOptions = await this.postsGetMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostMediaFromJSON(jsonValue));
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the media must still be attached to it.
     * Get a fresh download URL for one attached photo or video
     */
    async postsGetMedia(requestParameters: PostsGetMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostMedia> {
        const response = await this.postsGetMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetMediaContent without sending the request
     */
    async postsGetMediaContentRequestOpts(requestParameters: PostsGetMediaContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGetMediaContent().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling postsGetMediaContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/media/{mediaId}/content`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Rechecks the current post and attachment on every request, then streams the private object without exposing a provider URL or object key.
     * Read currently authorized post media bytes
     */
    async postsGetMediaContentRaw(requestParameters: PostsGetMediaContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.postsGetMediaContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Rechecks the current post and attachment on every request, then streams the private object without exposing a provider URL or object key.
     * Read currently authorized post media bytes
     */
    async postsGetMediaContent(requestParameters: PostsGetMediaContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postsGetMediaContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetProfileMood without sending the request
     */
    async postsGetProfileMoodRequestOpts(requestParameters: PostsGetProfileMoodRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling postsGetProfileMood().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profiles/{username}/mood`;
        urlPath = urlPath.replace('{username}', encodeURIComponent(String(requestParameters['username'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one person\'s daily ratings over the last 30 days, 90 days or year, with a summary of that range and of the same-length range before it. It reaches the same people as their posts: the owner, including solo and unreleased posts, and active friends, who see released `friends` posts only. Anyone else gets 403. Unknown, banned and blocked profiles all return 404.
     * Read a profile\'s mood history
     */
    async postsGetProfileMoodRaw(requestParameters: PostsGetProfileMoodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MoodHistory>> {
        const requestOptions = await this.postsGetProfileMoodRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MoodHistoryFromJSON(jsonValue));
    }

    /**
     * Returns one person\'s daily ratings over the last 30 days, 90 days or year, with a summary of that range and of the same-length range before it. It reaches the same people as their posts: the owner, including solo and unreleased posts, and active friends, who see released `friends` posts only. Anyone else gets 403. Unknown, banned and blocked profiles all return 404.
     * Read a profile\'s mood history
     */
    async postsGetProfileMood(requestParameters: PostsGetProfileMoodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MoodHistory> {
        const response = await this.postsGetProfileMoodRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetVoiceMemo without sending the request
     */
    async postsGetVoiceMemoRequestOpts(requestParameters: PostsGetVoiceMemoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGetVoiceMemo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/voice-memo`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the voice memo must still be attached to it.
     * Get a fresh download URL for a post\'s voice memo
     */
    async postsGetVoiceMemoRaw(requestParameters: PostsGetVoiceMemoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostVoiceMemo>> {
        const requestOptions = await this.postsGetVoiceMemoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostVoiceMemoFromJSON(jsonValue));
    }

    /**
     * Returns a new private download URL, valid for 5 minutes, when an earlier one has expired. The same rules as reading the post apply, and the voice memo must still be attached to it.
     * Get a fresh download URL for a post\'s voice memo
     */
    async postsGetVoiceMemo(requestParameters: PostsGetVoiceMemoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostVoiceMemo> {
        const response = await this.postsGetVoiceMemoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsGetVoiceMemoContent without sending the request
     */
    async postsGetVoiceMemoContentRequestOpts(requestParameters: PostsGetVoiceMemoContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsGetVoiceMemoContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/voice-memo/content`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Rechecks the current post and attachment on every request, then streams the private object without exposing a provider URL or object key.
     * Read currently authorized voice memo bytes
     */
    async postsGetVoiceMemoContentRaw(requestParameters: PostsGetVoiceMemoContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.postsGetVoiceMemoContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Rechecks the current post and attachment on every request, then streams the private object without exposing a provider URL or object key.
     * Read currently authorized voice memo bytes
     */
    async postsGetVoiceMemoContent(requestParameters: PostsGetVoiceMemoContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.postsGetVoiceMemoContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListFeed without sending the request
     */
    async postsListFeedRequestOpts(requestParameters: PostsListFeedRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/feed`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns yesterday\'s `friends` posts by the authenticated user\'s active friends: the Auckland day released at the most recent midnight. Earlier days are on each friend\'s profile. Solo posts, the caller\'s own posts, and posts by blocked or blocking users are never included. Access is re-checked on every page.
     * List yesterday\'s posts from friends
     */
    async postsListFeedRaw(requestParameters: PostsListFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedPage>> {
        const requestOptions = await this.postsListFeedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedPageFromJSON(jsonValue));
    }

    /**
     * Returns yesterday\'s `friends` posts by the authenticated user\'s active friends: the Auckland day released at the most recent midnight. Earlier days are on each friend\'s profile. Solo posts, the caller\'s own posts, and posts by blocked or blocking users are never included. Access is re-checked on every page.
     * List yesterday\'s posts from friends
     */
    async postsListFeed(requestParameters: PostsListFeedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedPage> {
        const response = await this.postsListFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListOnThisDay without sending the request
     */
    async postsListOnThisDayRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/me/memories/on-this-day`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the caller\'s own posts from today\'s Auckland month and day in earlier years, newest year first, at most one per year. Only the caller\'s posts are ever returned, solo and friends alike. Posts in Trash or awaiting purge, and posts from the current year, are left out. A 29 February post is a memory only on 29 February of a later leap year. The date is the server\'s current Auckland date and cannot be supplied by the client.
     * List the caller\'s On This Day memories
     */
    async postsListOnThisDayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnThisDayMemories>> {
        const requestOptions = await this.postsListOnThisDayRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OnThisDayMemoriesFromJSON(jsonValue));
    }

    /**
     * Returns the caller\'s own posts from today\'s Auckland month and day in earlier years, newest year first, at most one per year. Only the caller\'s posts are ever returned, solo and friends alike. Posts in Trash or awaiting purge, and posts from the current year, are left out. A 29 February post is a memory only on 29 February of a later leap year. The date is the server\'s current Auckland date and cannot be supplied by the client.
     * List the caller\'s On This Day memories
     */
    async postsListOnThisDay(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnThisDayMemories> {
        const response = await this.postsListOnThisDayRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListProfilePosts without sending the request
     */
    async postsListProfilePostsRequestOpts(requestParameters: PostsListProfilePostsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling postsListProfilePosts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profiles/{username}/posts`;
        urlPath = urlPath.replace('{username}', encodeURIComponent(String(requestParameters['username'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one person\'s posts, newest Auckland day first. Owners retain solo and unreleased posts. Active friends and public-profile readers receive released `friends` posts. A private non-friend receives only the username and a generic restricted state, with no page metadata. Access is re-checked on every page. Unknown, inactive, banned, and blocked profiles all return 404.
     * List the posts on a profile
     */
    async postsListProfilePostsRaw(requestParameters: PostsListProfilePostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadableProfilePosts>> {
        const requestOptions = await this.postsListProfilePostsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadableProfilePostsFromJSON(jsonValue));
    }

    /**
     * Returns one person\'s posts, newest Auckland day first. Owners retain solo and unreleased posts. Active friends and public-profile readers receive released `friends` posts. A private non-friend receives only the username and a generic restricted state, with no page metadata. Access is re-checked on every page. Unknown, inactive, banned, and blocked profiles all return 404.
     * List the posts on a profile
     */
    async postsListProfilePosts(requestParameters: PostsListProfilePostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadableProfilePosts> {
        const response = await this.postsListProfilePostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListRevisions without sending the request
     */
    async postsListRevisionsRequestOpts(requestParameters: PostsListRevisionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsListRevisions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/revisions`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns earlier versions of a post the caller may read, newest first. The author sees every version. Anyone else sees only versions that were already shared with friends, so text written while the post was solo stays private. A missing post and a post the caller may not read both return 404.
     * List a post\'s earlier versions
     */
    async postsListRevisionsRaw(requestParameters: PostsListRevisionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostRevisionsPage>> {
        const requestOptions = await this.postsListRevisionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostRevisionsPageFromJSON(jsonValue));
    }

    /**
     * Returns earlier versions of a post the caller may read, newest first. The author sees every version. Anyone else sees only versions that were already shared with friends, so text written while the post was solo stays private. A missing post and a post the caller may not read both return 404.
     * List a post\'s earlier versions
     */
    async postsListRevisions(requestParameters: PostsListRevisionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostRevisionsPage> {
        const response = await this.postsListRevisionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsListTrash without sending the request
     */
    async postsListTrashRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/trash`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the authenticated owner\'s trashed posts
     */
    async postsListTrashRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsListTrash200Response>> {
        const requestOptions = await this.postsListTrashRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsListTrash200ResponseFromJSON(jsonValue));
    }

    /**
     * List the authenticated owner\'s trashed posts
     */
    async postsListTrash(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsListTrash200Response> {
        const response = await this.postsListTrashRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsRestore without sending the request
     */
    async postsRestoreRequestOpts(requestParameters: PostsRestoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsRestore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/restore`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Restore an owned post from Trash
     */
    async postsRestoreRaw(requestParameters: PostsRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsRestore200Response>> {
        const requestOptions = await this.postsRestoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsRestore200ResponseFromJSON(jsonValue));
    }

    /**
     * Restore an owned post from Trash
     */
    async postsRestore(requestParameters: PostsRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsRestore200Response> {
        const response = await this.postsRestoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsTrash without sending the request
     */
    async postsTrashRequestOpts(requestParameters: PostsTrashRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsTrash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}/trash`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Move an owned post to Trash
     */
    async postsTrashRaw(requestParameters: PostsTrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrashedPostStatus>> {
        const requestOptions = await this.postsTrashRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrashedPostStatusFromJSON(jsonValue));
    }

    /**
     * Move an owned post to Trash
     */
    async postsTrash(requestParameters: PostsTrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrashedPostStatus> {
        const response = await this.postsTrashRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postsUpdate without sending the request
     */
    async postsUpdateRequestOpts(requestParameters: PostsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsUpdate().'
            );
        }

        if (requestParameters['updatePostRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePostRequest',
                'Required parameter "updatePostRequest" was null or undefined when calling postsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/posts/{postId}`;
        urlPath = urlPath.replace('{postId}', encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePostRequestToJSON(requestParameters['updatePostRequest']),
        };
    }

    /**
     * Lets the author change the reflective answer, caption, rating, and audience of their post, before or after release. The request carries all four, and only values that differ are saved. Each saved edit keeps the previous version as a revision. Send the `revisionCount` you last read as `expectedRevisionCount`; a 409 means another edit was saved first. Repeating an edit that is already saved returns the post without adding a revision.
     * Edit a post
     */
    async postsUpdateRaw(requestParameters: PostsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostDetail>> {
        const requestOptions = await this.postsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostDetailFromJSON(jsonValue));
    }

    /**
     * Lets the author change the reflective answer, caption, rating, and audience of their post, before or after release. The request carries all four, and only values that differ are saved. Each saved edit keeps the previous version as a revision. Send the `revisionCount` you last read as `expectedRevisionCount`; a 409 means another edit was saved first. Repeating an edit that is already saved returns the post without adding a revision.
     * Edit a post
     */
    async postsUpdate(requestParameters: PostsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostDetail> {
        const response = await this.postsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const PostsGetProfileMoodRangeEnum = {
    _30d: '30d',
    _90d: '90d',
    _1y: '1y',
} as const;
export type PostsGetProfileMoodRangeEnum = typeof PostsGetProfileMoodRangeEnum[keyof typeof PostsGetProfileMoodRangeEnum];
