/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type ChangeUsernameRequest,
    ChangeUsernameRequestFromJSON,
    ChangeUsernameRequestToJSON,
} from '../models/ChangeUsernameRequest';
import {
    type ChangeUsernameResponse,
    ChangeUsernameResponseFromJSON,
    ChangeUsernameResponseToJSON,
} from '../models/ChangeUsernameResponse';
import {
    type ProfileDetails,
    ProfileDetailsFromJSON,
    ProfileDetailsToJSON,
} from '../models/ProfileDetails';
import {
    type SetAvatarRequest,
    SetAvatarRequestFromJSON,
    SetAvatarRequestToJSON,
} from '../models/SetAvatarRequest';
import {
    type UpdateProfileRequest,
    UpdateProfileRequestFromJSON,
    UpdateProfileRequestToJSON,
} from '../models/UpdateProfileRequest';
import {
    type UsernameProfile,
    UsernameProfileFromJSON,
    UsernameProfileToJSON,
} from '../models/UsernameProfile';
import {
    type UsernameSetupRequest,
    UsernameSetupRequestFromJSON,
    UsernameSetupRequestToJSON,
} from '../models/UsernameSetupRequest';

export interface ProfileChangeUsernameRequest {
    /**
     *
     */
    changeUsernameRequest: ChangeUsernameRequest;
}

export interface ProfileClaimInitialUsernameRequest {
    /**
     *
     */
    usernameSetupRequest: UsernameSetupRequest;
}

export interface ProfileGetDetailsRequest {
    /**
     *
     */
    username: string;
}

export interface ProfileSetAvatarRequest {
    /**
     *
     */
    setAvatarRequest: SetAvatarRequest;
}

export interface ProfileUpdateRequest {
    /**
     *
     */
    updateProfileRequest: UpdateProfileRequest;
}

/**
 *
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Creates request options for profileChangeUsername without sending the request
     */
    async profileChangeUsernameRequestOpts(requestParameters: ProfileChangeUsernameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['changeUsernameRequest'] == null) {
            throw new runtime.RequiredError(
                'changeUsernameRequest',
                'Required parameter "changeUsernameRequest" was null or undefined when calling profileChangeUsername().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profile/username`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeUsernameRequestToJSON(requestParameters['changeUsernameRequest']),
        };
    }

    /**
     * Changes an established username. It can change at most once every 30 days. The previous handle stays reserved for this account for 30 days, and profile links to it resolve to the new one. Choosing the current handle again changes nothing.
     * Change your username
     */
    async profileChangeUsernameRaw(requestParameters: ProfileChangeUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangeUsernameResponse>> {
        const requestOptions = await this.profileChangeUsernameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangeUsernameResponseFromJSON(jsonValue));
    }

    /**
     * Changes an established username. It can change at most once every 30 days. The previous handle stays reserved for this account for 30 days, and profile links to it resolve to the new one. Choosing the current handle again changes nothing.
     * Change your username
     */
    async profileChangeUsername(requestParameters: ProfileChangeUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangeUsernameResponse> {
        const response = await this.profileChangeUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileClaimInitialUsername without sending the request
     */
    async profileClaimInitialUsernameRequestOpts(requestParameters: ProfileClaimInitialUsernameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['usernameSetupRequest'] == null) {
            throw new runtime.RequiredError(
                'usernameSetupRequest',
                'Required parameter "usernameSetupRequest" was null or undefined when calling profileClaimInitialUsername().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profile/username`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsernameSetupRequestToJSON(requestParameters['usernameSetupRequest']),
        };
    }

    /**
     * Completes the one-time required username setup for the authenticated account. It never renames an established handle.
     * Claim an initial username
     */
    async profileClaimInitialUsernameRaw(requestParameters: ProfileClaimInitialUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsernameProfile>> {
        const requestOptions = await this.profileClaimInitialUsernameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsernameProfileFromJSON(jsonValue));
    }

    /**
     * Completes the one-time required username setup for the authenticated account. It never renames an established handle.
     * Claim an initial username
     */
    async profileClaimInitialUsername(requestParameters: ProfileClaimInitialUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsernameProfile> {
        const response = await this.profileClaimInitialUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileGetDetails without sending the request
     */
    async profileGetDetailsRequestOpts(requestParameters: ProfileGetDetailsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling profileGetDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profiles/{username}`;
        urlPath = urlPath.replace('{username}', encodeURIComponent(String(requestParameters['username'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the public name and, when the caller may see it, the bio. The owner always sees their bio; anyone else sees it when the account is public or when they are active friends. The owner also gets their visibility and when their username can next change. A handle the owner gave up in the last 30 days resolves to their current profile. Unknown, banned and blocked profiles all return 404.
     * Read a profile\'s details
     */
    async profileGetDetailsRaw(requestParameters: ProfileGetDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDetails>> {
        const requestOptions = await this.profileGetDetailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDetailsFromJSON(jsonValue));
    }

    /**
     * Returns the public name and, when the caller may see it, the bio. The owner always sees their bio; anyone else sees it when the account is public or when they are active friends. The owner also gets their visibility and when their username can next change. A handle the owner gave up in the last 30 days resolves to their current profile. Unknown, banned and blocked profiles all return 404.
     * Read a profile\'s details
     */
    async profileGetDetails(requestParameters: ProfileGetDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDetails> {
        const response = await this.profileGetDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileGetUsername without sending the request
     */
    async profileGetUsernameRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profile/username`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get username setup state
     */
    async profileGetUsernameRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsernameProfile>> {
        const requestOptions = await this.profileGetUsernameRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsernameProfileFromJSON(jsonValue));
    }

    /**
     * Get username setup state
     */
    async profileGetUsername(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsernameProfile> {
        const response = await this.profileGetUsernameRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileRemoveAvatar without sending the request
     */
    async profileRemoveAvatarRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profile/avatar`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the profile photo. Profiles then show the first letter of the name.
     * Remove your profile photo
     */
    async profileRemoveAvatarRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDetails>> {
        const requestOptions = await this.profileRemoveAvatarRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDetailsFromJSON(jsonValue));
    }

    /**
     * Removes the profile photo. Profiles then show the first letter of the name.
     * Remove your profile photo
     */
    async profileRemoveAvatar(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDetails> {
        const response = await this.profileRemoveAvatarRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileSetAvatar without sending the request
     */
    async profileSetAvatarRequestOpts(requestParameters: ProfileSetAvatarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['setAvatarRequest'] == null) {
            throw new runtime.RequiredError(
                'setAvatarRequest',
                'Required parameter "setAvatarRequest" was null or undefined when calling profileSetAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profile/avatar`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetAvatarRequestToJSON(requestParameters['setAvatarRequest']),
        };
    }

    /**
     * Uses one of your validated JPEG, PNG, or WebP uploads as your profile photo, replacing any previous one. Upload it first through the media reservation flow.
     * Set your profile photo
     */
    async profileSetAvatarRaw(requestParameters: ProfileSetAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDetails>> {
        const requestOptions = await this.profileSetAvatarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDetailsFromJSON(jsonValue));
    }

    /**
     * Uses one of your validated JPEG, PNG, or WebP uploads as your profile photo, replacing any previous one. Upload it first through the media reservation flow.
     * Set your profile photo
     */
    async profileSetAvatar(requestParameters: ProfileSetAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDetails> {
        const response = await this.profileSetAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileUpdate without sending the request
     */
    async profileUpdateRequestOpts(requestParameters: ProfileUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProfileRequest',
                'Required parameter "updateProfileRequest" was null or undefined when calling profileUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/profile`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileRequestToJSON(requestParameters['updateProfileRequest']),
        };
    }

    /**
     * Changes any of the bio, public name, profile visibility, MBTI, what you do, and what you are listening to for the authenticated account. Fields left out are unchanged; null or blank text clears a field.
     * Update your profile
     */
    async profileUpdateRaw(requestParameters: ProfileUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDetails>> {
        const requestOptions = await this.profileUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDetailsFromJSON(jsonValue));
    }

    /**
     * Changes any of the bio, public name, profile visibility, MBTI, what you do, and what you are listening to for the authenticated account. Fields left out are unchanged; null or blank text clears a field.
     * Update your profile
     */
    async profileUpdate(requestParameters: ProfileUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDetails> {
        const response = await this.profileUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
