/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type PendingRequestPage,
    PendingRequestPageFromJSON,
    PendingRequestPageToJSON,
} from '../models/PendingRequestPage';
import {
    type RelationshipStatus,
    RelationshipStatusFromJSON,
    RelationshipStatusToJSON,
} from '../models/RelationshipStatus';
import {
    type SendRelationshipRequest,
    SendRelationshipRequestFromJSON,
    SendRelationshipRequestToJSON,
} from '../models/SendRelationshipRequest';

export interface RelationshipsAcceptRequestRequest {
    /**
     *
     */
    requestId: string;
}

export interface RelationshipsBlockRequest {
    /**
     *
     */
    userId: string;
}

export interface RelationshipsCancelRequestRequest {
    /**
     *
     */
    requestId: string;
}

export interface RelationshipsDeclineRequestRequest {
    /**
     *
     */
    requestId: string;
}

export interface RelationshipsGetStatusRequest {
    /**
     *
     */
    userId: string;
}

export interface RelationshipsListPendingRequestsRequest {
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
    /**
     *
     */
    direction?: RelationshipsListPendingRequestsDirectionEnum;
}

export interface RelationshipsRemoveFriendshipRequest {
    /**
     *
     */
    userId: string;
}

export interface RelationshipsSendRequestRequest {
    /**
     *
     */
    sendRelationshipRequest?: SendRelationshipRequest;
}

export interface RelationshipsUnblockRequest {
    /**
     *
     */
    userId: string;
}

/**
 *
 */
export class RelationshipsApi extends runtime.BaseAPI {

    /**
     * Creates request options for relationshipsAcceptRequest without sending the request
     */
    async relationshipsAcceptRequestRequestOpts(requestParameters: RelationshipsAcceptRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling relationshipsAcceptRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/requests/{requestId}/accept`;
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Accept a pending relationship request
     */
    async relationshipsAcceptRequestRaw(requestParameters: RelationshipsAcceptRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsAcceptRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Accept a pending relationship request
     */
    async relationshipsAcceptRequest(requestParameters: RelationshipsAcceptRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsAcceptRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsBlock without sending the request
     */
    async relationshipsBlockRequestOpts(requestParameters: RelationshipsBlockRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling relationshipsBlock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/{userId}/block`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Block a user
     */
    async relationshipsBlockRaw(requestParameters: RelationshipsBlockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsBlockRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Block a user
     */
    async relationshipsBlock(requestParameters: RelationshipsBlockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsBlockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsCancelRequest without sending the request
     */
    async relationshipsCancelRequestRequestOpts(requestParameters: RelationshipsCancelRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling relationshipsCancelRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/requests/{requestId}/cancel`;
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel a pending relationship request
     */
    async relationshipsCancelRequestRaw(requestParameters: RelationshipsCancelRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsCancelRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Cancel a pending relationship request
     */
    async relationshipsCancelRequest(requestParameters: RelationshipsCancelRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsCancelRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsDeclineRequest without sending the request
     */
    async relationshipsDeclineRequestRequestOpts(requestParameters: RelationshipsDeclineRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling relationshipsDeclineRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/requests/{requestId}/decline`;
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Decline a pending relationship request
     */
    async relationshipsDeclineRequestRaw(requestParameters: RelationshipsDeclineRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsDeclineRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Decline a pending relationship request
     */
    async relationshipsDeclineRequest(requestParameters: RelationshipsDeclineRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsDeclineRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsGetStatus without sending the request
     */
    async relationshipsGetStatusRequestOpts(requestParameters: RelationshipsGetStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling relationshipsGetStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/{userId}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get relationship status with a user
     */
    async relationshipsGetStatusRaw(requestParameters: RelationshipsGetStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsGetStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Get relationship status with a user
     */
    async relationshipsGetStatus(requestParameters: RelationshipsGetStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsGetStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsListPendingRequests without sending the request
     */
    async relationshipsListPendingRequestsRequestOpts(requestParameters: RelationshipsListPendingRequestsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List pending relationship requests
     */
    async relationshipsListPendingRequestsRaw(requestParameters: RelationshipsListPendingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PendingRequestPage>> {
        const requestOptions = await this.relationshipsListPendingRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PendingRequestPageFromJSON(jsonValue));
    }

    /**
     * List pending relationship requests
     */
    async relationshipsListPendingRequests(requestParameters: RelationshipsListPendingRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PendingRequestPage> {
        const response = await this.relationshipsListPendingRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsRemoveFriendship without sending the request
     */
    async relationshipsRemoveFriendshipRequestOpts(requestParameters: RelationshipsRemoveFriendshipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling relationshipsRemoveFriendship().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/{userId}/friendship`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * End an active friendship
     */
    async relationshipsRemoveFriendshipRaw(requestParameters: RelationshipsRemoveFriendshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsRemoveFriendshipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * End an active friendship
     */
    async relationshipsRemoveFriendship(requestParameters: RelationshipsRemoveFriendshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsRemoveFriendshipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsSendRequest without sending the request
     */
    async relationshipsSendRequestRequestOpts(requestParameters: RelationshipsSendRequestRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendRelationshipRequestToJSON(requestParameters['sendRelationshipRequest']),
        };
    }

    /**
     * Send a relationship request
     */
    async relationshipsSendRequestRaw(requestParameters: RelationshipsSendRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsSendRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Send a relationship request
     */
    async relationshipsSendRequest(requestParameters: RelationshipsSendRequestRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsSendRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for relationshipsUnblock without sending the request
     */
    async relationshipsUnblockRequestOpts(requestParameters: RelationshipsUnblockRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling relationshipsUnblock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/relationships/{userId}/block`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unblock a user
     */
    async relationshipsUnblockRaw(requestParameters: RelationshipsUnblockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelationshipStatus>> {
        const requestOptions = await this.relationshipsUnblockRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipStatusFromJSON(jsonValue));
    }

    /**
     * Unblock a user
     */
    async relationshipsUnblock(requestParameters: RelationshipsUnblockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelationshipStatus> {
        const response = await this.relationshipsUnblockRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const RelationshipsListPendingRequestsDirectionEnum = {
    Incoming: 'incoming',
    Outgoing: 'outgoing',
    All: 'all',
} as const;
export type RelationshipsListPendingRequestsDirectionEnum = typeof RelationshipsListPendingRequestsDirectionEnum[keyof typeof RelationshipsListPendingRequestsDirectionEnum];
