/* tslint:disable */
/* eslint-disable */
/**
 * Dayli API
 * REST API shared by the Dayli mobile and web clients.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type HealthResponse,
    HealthResponseFromJSON,
    HealthResponseToJSON,
} from '../models/HealthResponse';
import {
    type TestResponse,
    TestResponseFromJSON,
    TestResponseToJSON,
} from '../models/TestResponse';

export interface SystemTestContractsRequest {
    /**
     * Opaque continuation cursor
     */
    cursor?: string;
    /**
     *
     */
    limit?: number;
}

/**
 *
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Creates request options for systemHealth without sending the request
     */
    async systemHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check API availability
     */
    async systemHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const requestOptions = await this.systemHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Check API availability
     */
    async systemHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.systemHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for systemTestContracts without sending the request
     */
    async systemTestContractsRequestOpts(requestParameters: SystemTestContractsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/test`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Exercise common API contracts
     */
    async systemTestContractsRaw(requestParameters: SystemTestContractsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TestResponse>> {
        const requestOptions = await this.systemTestContractsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TestResponseFromJSON(jsonValue));
    }

    /**
     * Exercise common API contracts
     */
    async systemTestContracts(requestParameters: SystemTestContractsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TestResponse> {
        const response = await this.systemTestContractsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
